prebid/prebid.github.io

dev-docs/examples/basic-example.md

Standard keyword targeting setup was linking to http://local/

removed local reference

---

adops/step-by-step.md
assets/css/style.css

Updates to CSS to bring site closer to typography recommendations listed
at:
http://practicaltypography.com/summary-of-key-rules.html
Addresses
https://github.com/prebid/prebid.github.io/issues/9

Changes to site typography for easier reading.

---

dev-docs/bidders.md

Add bidder params for Sonobi bidder to documentation.

Sonobi Bidder Documentation

---

dev-docs/publisher-api-reference.md

Addresses https://github.com/prebid/prebid.github.io/issues/41

Add API doc for `pbjs.enableSendAllBids()`

---

_layouts/example.html
dev-docs/examples/log-all-bids.md

Further addresses https://github.com/prebid/prebid.github.io/issues/41

Add developer example of `pbjs.enableSendAllBids()`

---

dev-docs/publisher-api-reference.md

Addresses https://github.com/prebid/prebid.github.io/issues/47

Add `setPriceGranularity` to API reference

---

adops/deals.md
dev-docs/publisher-api-reference.md

Specifically:
+ Edit/spellcheck Ad Ops deals setup doc
+ Expose Ad Ops deals setup doc
+ Add deal info to the publisher API reference

RAD-898 Update deals docs

---

dev-docs/bidders/admedia.md

Bidder params for Admedia prebid bidder.

Admedia bidder docs

---

dev-docs/bidders/sovrn.md

@cliffliang
Goes with: https://github.com/prebid/Prebid.js/pull/423

Update sovrn docs with new param.

---

_config.yml
dev-docs/testing-prebid.md

See also: https://github.com/prebid/Prebid.js/issues/421
Original version of these docs was written by @matthewlane, I just did
some edits/cleanup.  Thanks Matt!

RAD-972 Add docs for testing the Prebid.js library

---

dev-docs/testing-prebid.md

* Drop the brackets as the adapter will be exporting a default object
* Suggest 'expect' as assertion style

Update example import section

---

dev-docs/bidders/kruxlink.md

Add documentation for Krux Link bidder

Add Krux Link documentation

---

dev-docs/bidder-adaptor.md

Basically, describe how to use the new caching param.

RAD-1038 Add more usage info to 'adloader' docs

---

_posts/2016-04-20-sonobi-brightcom-adequant-adaptors.md
dev-docs/bidders/sonobi.md

Update for Sonobi dev docs to match updated adapter:
https://github.com/prebid/Prebid.js/pull/591/files

Update sonobi dev-docs

---

dev-docs/publisher-api-reference.md

proposed restructuring of the bidderSettings section as noted in #80

updated bidderSettings docs

---

dev-docs/show-video-with-a-dfp-video-tag.md

Added JWPlayer Prebid Video demo link to dev-docs

---

_posts/2016-10-05-show-responsive-ads-with-size-mapping.md
dev-docs/examples/size-mapping.md

Changes:
+ add size mapping example to examples page
+ add blog post on size mapping
@mkendall07 - would you please review the size mapping example and technical description?  I.e.,
+ Is any important information missing?  
+ Can something be more clearly worded for developers?
+ Can the example be better?  The resizing doesn't seem to work inside JSFiddle AFAICT, but I got it working at http://rloveland.devnxs.net:3000/size-mapping3.html so I went with it
@mjacobsonny what do you think of this blog post? I.e.,
+ any other benefits of this feature i'm missing in the post?
+ any other info that should go in there?
Thanks guys!

Issue 102 - size mapping

---

dev-docs/bidders/piximedia.md

Hello Team,
Here is a PR adding documentation for the Piximedia bidder (related to issue #659 on the Prebid.org project).
All the best,
Christopher

Add Piximedia bidder documentation

---

dev-docs/bidders/adbutler.md

Adding the documentation and bid parameters for the AdButler Adapter to the Dev Docs.

Add AdButler Adapter Documentation

---

examples/postbid.html
examples/postbid2.html

The previous name `doNotChange` might confuse developers and ad ops new to prebid.js.

more intuitive name for variable holding the ad unit code

---

dev-docs/publisher-api-reference.md

RAD-1229 add docs for Custom CPM Bucket Sizing

---

dev-docs/examples/adjust-price.md

Specifically, updated the JSFiddle we link to.

Update 'Adjust Price' example: set ratio < 100%

---

_layouts/example.html

Also cleaned up the description of how to use the JSFiddle, and tweaked
some formatting.

Add link to troubleshooting docs to every example

---

dev-docs/bidders/fidelity.md

Could you please use name "Fidelity Media" on the website.

Add Fidelity adapter documentation

---

adops/setting-up-prebid-video-in-dfp.md
dev-docs/examples/custom-price-bucket-using-setpricegranularity.md
dev-docs/publisher-api-reference.md
dev-docs/show-video-with-a-dfp-video-tag.md

@mjacobsonny mind taking a look at these changes?
Added info on setting up custom price buckets to both the dev and ad ops video docs.

RAD-1285 Docs on custom bid buckets for CPMs > $20

---

examples/postbid.html

As written in this issue: https://github.com/prebid/Prebid.js/issues/407

Fixes the problem with browsers that keeps loading with this example

---

dev-docs/bidders/vertoz.md

Vertoz Adapter reference document

---

dev-docs/bidders/smartadserver.md

Hi,
Here is the Smart AdServer adaptor documentation, following the [Prebid.js pull request #853](https://github.com/prebid/Prebid.js/pull/853)
Regards,

Add Smart AdServer bidder documentation

---

dev-docs/bidders/smartadserver.md

Fix domain value sample which was wrongly copy/pasted...

Fix domain sample

---

dev-docs/bidders/twenga.md
download.md

I took the liberty to add a Twenga checkbox to download.md. Hope that's okay.

Add Twenga adapter docs and download checkbox

---

dev-docs/bidders/lifestreet.md
download.md

Add Lifestreet adapter

---

dev-docs/bidders/thoughtleadr.md
download.md
index.md

Add ThoughtLeadr adapter

---

dev-docs/bidders/tapsense.md
download.md
index.md

Related to Adapter PR: https://github.com/prebid/Prebid.js/pull/1004

Add TapSense Adapter

---

assets/css/style.css

Similar to sites like:
+ ampproject.org
+ flutter.io

Top navbar floats in place as you scroll down

---

dev-docs/bidders/audienceNetwork.md

As suggested in https://github.com/prebid/Prebid.js/pull/1068, thank you.

Document Audience Network bidder adaptor

---

dev-docs/bidders/inneractive.md

@rmloveland, 
Thanks!
I've changed the table layout and ran it through Jekyll so that the table will render ok.

docs: changing markdown to contain valid URL + newline

---

dev-docs/bidders/hiromedia.md

Relevant PR on main project repo: https://github.com/prebid/Prebid.js/pull/1107

HIRO Media: Remove unused parameters

---

dev-docs/bidders/quantcast.md

Adding Quantcast as a bidder - complimenting the Prebid.js adaptor
Complimenting https://github.com/prebid/Prebid.js/pull/1063

Adding Quantcast as a bidder - complimenting the Prebid.js adaptor

---

dev-docs/bidders/innity.md

Along with adapter PR.
https://github.com/prebid/Prebid.js/pull/1074
Thanks.

Innity Adapter Documentation

---

dev-docs/bidders/adsupply.md

Added parameters description for AdSupply adapter.

AdSupply docs

---

dev-docs/bidders/conversant.md

Documentation added for:
* tag_id
* position
* mimes
* maxduration
* api
* protocols

Updating Conversant Docs

---

dev-docs/bidders/rubicon.md

Update notes for rubicon multiple zoneIds support according to #496, #763 & #782

Update notes for rubicon multiple zoneIds support

---

dev-docs/publisher-api-reference.md

Docs on auction events
Addresses the following issues:
- #157 
- #81 
Docs are heavily based on https://github.com/prebid/Prebid.js/pull/204

Documentation on auction events

---

dev-docs/bidders/eplanning.md

Added parameters description for E-Planning adapter

E-Planning adaptor docs

---

download.md

Addition of PubWise.io Analytics to downloader. Inserted alphabetically.

Add PubWise.io Analytics to Downloader

---

dev-docs/bidders/carambola.md

Carambola requests for it's new adapter adapter

Carambola new adapter

---

dev-docs/bidders/audienceNetwork.md

Relates to https://github.com/prebid/Prebid.js/pull/1218

Audience Network: document new format parameter

---

adops/setting-up-prebid-for-amp-in-dfp.md

@mkendall07 Do you think we need additional context around this?  If not I'll merge.

RAD-1709 Update AMP page to remove 1x1

---

dev-docs/publisher-api-reference.md

together with JSDoc fix https://github.com/prebid/Prebid.js/pull/1322

Fix incorrect param type of addAdUnits parameter

---

prebid-mobile/prebid-mobile-pbs.md

Links were for old pages, fix links to link to new pages.

Fix broken links on getting started link to ios android code integration

---

dev-docs/bidders/vertoz.md

We have added cpmFloor as request paramter.
Code changes are merged in repository.

cpmFloor request parameter added.

---

dev-docs/bidders/audienceNetwork.md

Relates to https://github.com/prebid/Prebid.js/pull/1292

Audience Network: document video format

---

dev-docs/bidders/kargo.md

RE https://github.com/prebid/Prebid.js/pull/1316

Kargo Adapter docs

---

dev-docs/bidders/adyoulike.md
index.md

Documentation for prebid/Prebid.js#1155

Add Adyoulike adapter

---

_layouts/bidder.html
dev-docs/bidders.md

Addresses #292 and will affect #234

Add docs on which adapters support which media types

---

dev-docs/bidders/c1x.md

add docs for [Prebid/C1X adapter #1369](https://github.com/prebid/Prebid.js/pull/1369)

Bidder's Params For C1X Adapter

---

dev-docs/bidders/aol.md
dev-docs/bidders/onedisplay.md
dev-docs/bidders/onemobile.md

This PR is related to https://github.com/prebid/Prebid.js/pull/1371

Bidder's Params For AOL Adapter aliases

---

dev-docs/get-started-with-prebid-server.md
dev-docs/publisher-api-reference.md

Including:
- Marking deprecated methods
- Change to Prebid Server config

Update API docs with `{set,get}Config`

---

prebid-mobile/code-integration-android.md

This PR includes a update for maven version of Android integration.

Use latest version for maven integration

---

dev-docs/bidders/imonomy.md

Add documentation for the imonomy bidder adapter.

Add imonomy.md for imonomy bidder adapter.

---

prebid-mobile/code-integration-android.md

This PR includes a fix for wrong description of an ad object for code integration of Android.

Fix ad object explanation

---

prebid-mobile/code-integration-android.md

This PR includes description of code integration when auto refresh is enabled for mobile ads.

Add description of auto refresh case

---

dev-docs/bidders/spotx.md

Updated SpotX to be on brand

---

dev-docs/bidders/c1x.md

I would like to add note to our current bidder's params section. Thank you!

Add note for C1X bidder's params

---

prebid-mobile/code-integration-android.md

This PR includes modification of description for Android auto refresh. The original description raised confusion of clients, thus changing it for clarity.

Modification of description for auto refresh

---

dev-docs/bidder-adaptor.md
dev-docs/publisher-api-reference.md

Documentation to go with the User Sync Module submitted in https://github.com/prebid/Prebid.js/pull/1229

User sync updates

---

dev-docs/bidders/rubicon.md

Refining Rubicon params description

---

dev-docs/bidders/prebidServer.md

Add prebid server back to downloads page. 
@rmloveland I think I need your help with formatting the configuration part. I couldn't get it to render properly...

add prebid server to downloads

---

dev-docs/prebid-1.0-API.md

@bretg @rmloveland for review.

add pub docs for 1.0

---

_posts/2017-09-25-announcing-prebid-1.0.md

one more for @rmloveland and @bretg to review. Thanks guys

Prebid 1.0 blogpost

---

dev-docs/bidders/trustx.md

Hello Prebid team!
Please add the provided documentation for the TrustX bidder adapter.

TrustX adapter dev-doc

---

dev-docs/bidders/kumma.md

Adding Kumma md file, for the new Kumma adapter.

Kumma md file

---

dev-docs/bidders/orbitsoft.md

Add documentation for the Orbitsoft bidder adapter.

Orbitsoft adapter dev-doc

---

dev-docs/bidders/centro.md

Hello!
Merge please fixed dev-doc for Centro adapter.
And, if i right understand, after this fix is merged, we'll be able to see the Centro adapter on the download page

Fix Centro dev-doc

---

dev-docs/bidder-adapter-1.md

Worked with snapwich to correct the function signature. We also changed the argument name to be more clear.

Fixing the argument for the buildRequest function

---

prebid-mobile/code-integration-android.md

This PR includes instructions on how to add Proguard settings for DFP users.

Add instructions for proguard

---

dev-docs/publisher-api-reference.md

pointed out here: https://redditadops.slack.com/archives/C0HVALS8P/p1506618438000631

Remove erroneous `cap` value

---

dev-docs/publisher-api-reference.md
dev-docs/show-video-with-a-dfp-video-tag.md

Also, add some explanation for why it's necessary.

Update 'Show Video Ads' to use (required) cache

---

prebid-mobile/code-integration-ios.md

Better docs for iOS API methods.

Update Prebid Mobile iOS docs to more clearly state the API methods

---

dev-docs/bidder-adapter-1.md

Just did this for Rubicon's adapter, and it doesn't look very good without some formatting.

Adding formatting to markdown example

---

dev-docs/bidders/connectad.md
dev-docs/bidders/serverbid.md

Added Serverbid and ConnectAd bidders so that they show up on the Downloads page and in the docs.

Added Serverbid and ConnectAd bidders

---

index.md

Adding PubWise to the Partner list on the front page.

Updates for Partner List

---

dev-docs/integrate-with-the-prebid-analytics-api.md

Adds notice about changes to data emitted from events in Prebid 1.0.
@rmloveland Let me know if I used the appropriate notice type, if this seems like a good location for the note, and anything else I can improve.
cc @bretg

Add analytics breaking change notice

---

dev-docs/bidders/appnexus-ast.md

Move nested bulleted lists into a table for ease of reading/scanning.

Fix formatting for `appnexusAst` bidder params

---

dev-docs/bidders/kumma.md

adding placement id and bid floor as Kumma adapter parameters.

New paramters in Kumma bidder

---

dev-docs/bidders/optimatic.md

Prebid Optimatic Bidder Adapter Documentation - https://github.com/prebid/Prebid.js/pull/1837

+ Add Optimatic Bidder integration documentation

---

dev-docs/bidders/arteebee.md

The this document for Arteebee bid adapter related with pull request:
https://github.com/prebid/Prebid.js/pull/1849

add document for Arteebee bid adapter

---

dev-docs/bidders/pulsepointlite.md

Fixes the download page but this is the wrong bidderCode.

Pulsepoint wrong filename

---

dev-docs/bidders/readpeak.md

Documentation for the ReadPeak Bid Adapter
Adapter itself in prebid/Prebid.js#1838

Add ReadPeak Bid Adapter Documentation

---

dev-docs/bidders/featureforward.md

Old parameters and implementation notes are updated and adjusted to the most recent adapter implementation

Update docs for Feature Forward adapter 

---

dev-docs/bidders/somoaudience.md

This is the bidder docs for the Somo Audience bid adapter.

Somo Audience Dev Docs

---

_posts/2017-12-11-prebid-1-is-released.md

Addresses https://github.com/prebid/prebid.github.io/issues/485

Add Prebid.js 1.0 release announcement blog post

---

dev-docs/bidders/bridgewell.md

We would like to add Bridgewell adapter to the download page.

Add: documentation for Bridgewell

---

dev-docs/bidders/undertone.md

Changed unertone adapter title from undertone to Undertone

Update undertone adapter title

---

dev-docs/bidders/vertamedia.md

The `placementId` parameter is not used in vertamedia adapter

Fix VertaMedia adapter parameter

---

dev-docs/get-started-with-prebid-server.md
dev-docs/publisher-api-reference.md

Addresses
https://github.com/prebid/prebid.github.io/issues/497

Update `s2sConfig` with configurable endpoints

---

README.md

Addresses https://github.com/prebid/prebid.github.io/issues/521

Update bundler install instructions

---

dev-docs/publisher-api-reference.md

In reference to: [Source](https://github.com/prebid/Prebid.js/blob/d4e1e9853f0c02e8fd83d05476ab2688b1156315/src/prebid.js#L341)

Updated Docs pbjs.addAdUnits arguments

---

dev-docs/bidders/brealtime.md
dev-docs/bidders/defymedia.md
dev-docs/bidders/featureforward.md
dev-docs/bidders/gourmetads.md
dev-docs/bidders/matomy.md
dev-docs/bidders/onedisplay.md
dev-docs/bidders/onemobile.md
dev-docs/bidders/pagescience.md

Adding aliases that are supported in 1.0

add some missing aliases to download page

---

dev-docs/bidder-adaptor.md

Related to https://github.com/prebid/Prebid.js/pull/1919

Add docs for native image-type asset dimensions

---

dev-docs/bidders/rxrtb.md

adapter pull request [https://github.com/prebid/Prebid.js/pull/1950](url)

Add: documentation for rxrtbBidAdapter

---

dev-docs/publisher-api-reference.md

Chopped off some needed trailing spaces in #541, adding those back in

Re-add trailing spaces to info boxes

---

dev-docs/bidders/vi.md
dev-docs/bidders/viBidAdapter.md

Documentation for Video intelligence Bid Adapter

vi bid adapter docs

---

dev-docs/bidders/nasmediaAdmixer.md

The this document for nasmediaAdmixer bid adapter related with pull request :
prebid/prebid.js#1937

Add : docs for NasmediaAdmixer Adapter

---

dev-docs/bidders/inskin.md

Docs for Inskin bid adapter PR - https://github.com/prebid/Prebid.js/pull/2016

Added Inskin bid adapter docs

---

dev-docs/toubleshooting-tips.md

Related to https://github.com/prebid/Prebid.js/issues/2094

updating see-all-bids snippet

---

dev-docs/bidders/eplanning.md

Reference https://github.com/prebid/Prebid.js/pull/2003

Added prebid_1_0_supported key to E-Planning doc

---

dev-docs/bidders/atomx.md

See: https://github.com/prebid/Prebid.js/pull/2026

Add prebid_1_0_supported to Atomx

---

dev-docs/bidders/adform.md

See: https://github.com/prebid/Prebid.js/pull/1947

Added prebid-1-0-supported to docs

---

dev-docs/bidders/peak226.md
index.md

Documentation for Peak226 PR: prebid/Prebid.js#2040

add peak226 adapter

---

dev-docs/bidders/xendiz.md

https://github.com/prebid/Prebid.js/pull/1985

Xendiz bid adaptor docs

---

dev-docs/bidders/adgeneration.md

Ad Generation Adapter dev docs

Add adgeneration docs

---

dev-docs/modules/currency.md

Added documentation to go along with feature added to the currency module here: https://github.com/prebid/Prebid.js/pull/2134

added documentation for currency.defaultRates

---

dev-docs/modules/currency.md

Reverts prebid/prebid.github.io#610

Revert "added documentation for currency.defaultRates"

---

dev-docs/publisher-api-reference.md

Update to docs as requested here: https://github.com/prebid/Prebid.js/pull/2114

added required to description of sizeConfig.mediaQuery

---

dev-docs/bidders/unruly.md

Changes to Unruly Bidder config to correct quotes.

Unruly doc changes 

---

dev-docs/get-started-with-prebid-server.md

Pending https://github.com/prebid/Prebid.js/pull/2102

Add note about OpenRTB endpoint config

---

dev-docs/bidders/yieldone.md

We would like to add YIELDONE adapter to the download page.

add YIELDONE docs

---

dev-docs/bidder-adaptor.md

Related to https://github.com/prebid/Prebid.js/issues/1882
We also need to add this convention to a general setConfig reference.

Adding pageUrl convention

---

dev-docs/bidders/prebidServer.md
dev-docs/get-started-with-prebid-server.md
dev-docs/publisher-api-reference.md

Added new information regarding new optional setting for the s2sConfig.
Relates to PR https://github.com/prebid/Prebid.js/pull/2073 (which is still open at time of submission).

added information on new s2sConfig option

---

dev-docs/bidders/sonobi.md

Adding a new parameter to the docs.

Sonobi add hfa docs

---

Gemfile
Gemfile~

had an issue with an older version of github pages. This forces an update with the latest ruby

clean up gemfile

---

assets/js/pbjs_home.js

Parse has been dead for awhile. This removes the annoying error in console.

remove parse

---

_config.yml
_includes/main_nav.html
videos/index.md
videos/prebid-video.md
videos/setup.md
videos/troubleshooting.md

Includes a bunch of videos created by the AppNexus training group.

Add new section 'Support > Videos'

---

dev-docs/bidders/quantum.md

Quantum Adapter Dev docs

---

dev-docs/bidders/fairtrade.md

Hello!
Add please doc file for FairTrade Bidder Adapter

Add doc for FairTrade Bidder Adapter

---

dev-docs/bidders/innity.md

Innity Adapter Documentation Support for Prebid.js 1.0

---

dev-docs/bidders/vuble.md

Add the doc for the vuble adapter.

Add: vuble adapter doc

---

dev-docs/bidders/vertoz.md

Reverts prebid/prebid.github.io#616 till download page is updated to 1.5.0

Revert "Vertozbid Adapter: doc update for prebid 1.0"

---

dev-docs/bidders/vuble.md

Small changes to the vuble doc

mod vuble doc example

---

dev-docs/conditional-ad-units.md
dev-docs/publisher-api-reference.md

Clarification driven by https://github.com/prebid/Prebid.js/issues/2263

add note about labelAny/labelAll being empty

---

dev-docs/bidders/invibes.md

Add bid params doc for Invibes Adapter

Invibes Adapter - documentation

---

dev-docs/bidders/contentignite.md

New bidder params documentation in preparation for pull request to Prebid.js project.
Contact me at jamie@contentignite.com

New Content Ignite docs

---

dev-docs/bidders/oneplanetonly.md

Hello! Add please doc file for Oneplanetonly Bid Adapter

Add doc for Oneplanetonly Bid Adapter

---

dev-docs/bidders/lifestreet.md

Updated doc as requested in the following pull request: https://github.com/prebid/Prebid.js/pull/2197

Lifestreet Adapter: doc update for prebid 1.0

---

dev-docs/faq.md

Adding FAQs for release schedule and priceGranularities

Adding FAQs for release schedule and priceGranularities

---

dev-docs/bidders/adtelligent.md

Add description for new adtelligentBidAdaper 
https://github.com/prebid/Prebid.js/pull/2137

Add md file for new adtelligentBidAdapter

---

dev-docs/publisher-api-reference.md

Documentation of new event `adRenderFailed` : [prebid/Prebid.js#2210](https://github.com/prebid/Prebid.js/pull/2210)

new event adRenderFailed added

---

dev-docs/bidders/archon.md

Associated Prebid PR: https://github.com/prebid/Prebid.js/pull/2293

Added doc page for the archon bid adapter alias.

---

dev-docs/bidders/beachfront.md

Adds documentation for optional video mimes param.

Add video mimes to beachfront doc

---

overview/analytics.md

Docs PR to  https://github.com/prebid/Prebid.js/pull/2331

Add: Vuble analytics adapter

---

dev-docs/modules/consentManagement.md

Added section about using gdprConsent information in UserSync registration function, as well as made minor layout changes and added table of contents for page.

GDPR - added notes to UserSync support and minor layout changes

---

_posts/2015-08-29-what-is-post-bid.md
addme.md
assets/js/pbjs_home.js
download.md
support/index.md

The addme.md file is useless I believe -- it doesn't appear to be linked anywhere, and it seems to redirect. But I changed it anyhow.

changed info@prebid.org to support@prebid.org

---

dev-docs/bidders/widespace.md

[x] Compliance with Prebis 1.x.x
[x] `bidFloor` param added
[x] Missing param `demo` data added in readme

Widespace Readme Updates

---

dev-docs/bidders/visx.md

Please see corresponding PR in Prebid.js repo for VIS.X

Adding VIS.X bidder dev docs

---

dev-docs/modules/consentManagement.md
dev-docs/modules/currency.md
dev-docs/modules/dfp_express.md
dev-docs/modules/dfp_video.md
dev-docs/modules/digitrust.md
dev-docs/modules/pubCommonId.md
dev-docs/modules/s2sTesting.md
download.md

remove digitrust from download

---

dev-docs/modules/consentManagement.md

Updates for the consentManagement module page in lieu of the upcoming changes to support the 1.1 CMP spec.

updates to consentManagement page in lieu 1.1 CMP spec

---

dev-docs/bidders/dgads.md

Please see corresponding PR in Prebid.js repo for dgads.

Adding dgads bidder dev docs

---

dev-docs/bidders/consumable.md

Please see corresponding PR in Prebid.js repo for Consumable bidder adapter.

Adding Consumable bidder dev docs

---

dev-docs/bidders/brainy.md

Pull request prebid/Prebid.js#2458

Add brainy bidder params

---

dev-docs/bidders/conversant.md

Mark Conversant adapter as gdpr enabled

Add gdpr_supported for Conversant

---

dev-docs/bidders/rhythmone.md

Added gdpr_supported flag for RhythmOne - https://github.com/prebid/Prebid.js/pull/2576

Added gdpr_supported flag for RhythmOne

---

dev-docs/bidders/aardvark.md

Along with:
https://github.com/prebid/Prebid.js/pull/2507

GDPR support for Aardvark

---

download.md

Add missing analytics adapters

---

dev-docs/bidders/adyoulike.md

Update AdyoulikeAdapter docs
https://github.com/prebid/Prebid.js/pull/2518

doc(adyoulike): add flat to gdpr support

---

dev-docs/bidders/gumgum.md

Added flag according to Adapter Integration guide.
PR for Adapter: https://github.com/prebid/Prebid.js/pull/2595

Add GDPR compliance flag

---

dev-docs/bidders/adkernel.md
dev-docs/bidders/adkernelAdn.md

Added GDPR info for both adkernel adapters

GDPR-related changes in docs for adkernel adapters

---

dev-docs/bidders/sekindo.md

changing Sekindo bidder name to SekindoUM

changing Sekindo bidder name to SekindoUM

---

dev-docs/bidders/widespace.md

GDPR Consent complaint PR: https://github.com/prebid/Prebid.js/pull/2638

Widespace GDPR support variable

---

dev-docs/bidders/kargo.md

update kargo bidder docs to clarify need for mobile device usage/emulation

---

dev-docs/bidders/adspirit.md

as requested for PR on https://github.com/prebid/Prebid.js

Docs for AdSpirit bid adapter

---

dev-docs/bidders/xaxis.md

Update as per request in https://github.com/prebid/Prebid.js/pull/2536

xaxis bidder documentation updated for 1.x/gdpr adapter update

---

dev-docs/bidders/fyber.md

New documentation for Fyber's Prebid Adapter

Fyber Prebid Adapter Documentation

---

dev-docs/bidders/visx.md

- Added GDPR consent management support
- Description updated

 Added GDPR consent management to YOC VIS.X Bid Adapter

---

index.md

This PR adds Gamoshi to the list of "Partners that work with Prebid" as the last partner in the list.

Add Gamoshi to the list of "Partners that work with Prebid"

---

.gitignore
assets/js/prebid-server-api.js
dev-docs/add-a-prebid-server-adapter.md
dev-docs/get-started-with-prebid-server.md
dev-docs/prebid-server-bidders.md

This addresses some concerns brought up in https://github.com/prebid/prebid-server/issues/574
This info didn't really fit into the current page... so I just made a new one. 
I think this is a much neater way of presenting the info... but let me know what you think. My eye for aesthetics kinda sucks.

Document Prebid Server Bidders

---

download.md

This switches the backend for the prebid.js download and changes from email delivery to straight file download.

turn back on prebid.js download

---

dev-docs/bidders/yieldlab.md

Corresponding to Pull Request: https://github.com/prebid/Prebid.js/pull/2755

Add gdpr support and key-value targeting to the Yieldlab bidder

---

dev-docs/integrate-with-the-prebid-analytics-api.md

Docs changes for PR: https://github.com/prebid/Prebid.js/pull/2779

remove references to library type as an analytics adapter

---

dev-docs/bidders/indexExchange.md

Docs changes for PR: prebid/Prebid.js#2744

Update documentation for IX Adapter

---

dev-docs/bidders/triplelift.md

Updated the markdown file to include:
prebid_1_0_supported : true
gdpr_supported: true

updated md file

---

dev-docs/bidders/uol.md

UOL  bidAdapter docs - first version.

UOL - bidAdapter release candidate docs

---

dev-docs/show-prebid-ads-on-amp-pages.md

from https://github.com/prebid/prebid.github.io/issues/886

Adding note about AMP debug parameter

---

dev-docs/bidders/aardvark.md

Reflect bid params to match current version of the adapter.

Update aardvark bidder docs

---

dev-docs/bidders/aduptech.md

Add docs for Ad Up Technology bidder adapter
Corresponding PR is [HERE](https://github.com/prebid/Prebid.js/pull/2809) .

Add docs for Ad Up Technology bidder adapter

---

dev-docs/bidders/answermedia.md

This alias was merged into Prebid in this PR: https://github.com/prebid/Prebid.js/pull/2847

Serverbid Bid Adapter alias: answermedia

---

download.md

This mostly automates updating the download page (individual bidder pages still need to be reviewed / merged to be updated here).

automate populating the prebid select picker for version

---

dev-docs/prebid-1.0-API.md

Correct, Labels may be targeted in the AdUnit structure via "labelAny" and "labelAll" not "labels"

Correct labels documentation

---

dev-docs/bidders/between.md

update for [prebid/Prebid.js#2722](https://github.com/prebid/Prebid.js/pull/2722)

add new adapter between

---

dev-docs/bidders/consumable.md

Updated docs for refactor fo Consumable adapter

docs for refactor of consumable adapter

---

overview/analytics.md

Re https://github.com/prebid/Prebid.js/pull/2939#issuecomment-412601979

Adding kargo analytics

---

dev-docs/bidders/divreach.md

Prebid.js PR [prebid/Prebid.js#2946](https://github.com/prebid/Prebid.js/pull/2946)

Add DivReach adapter docs

---

prebid-mobile/code-integration-ios.md
prebid-mobile/logging-troubleshooting-ios.md

Add PBM for iOS info about logging in test mode

---

dev-docs/modules/consentManagement.md

https://github.com/prebid/Prebid.js/pull/2636

Added docs for static consent mgmt

---

dev-docs/bidders/piximedia.md

Updated the documentation of the Piximedia Prebid adapter to Prebid 1.0.

Update Piximedia adapter documentation to 1.0

---

dev-docs/bidders/districtm.md

adding aliasCode
In support of https://github.com/prebid/prebid.github.io/issues/944

Linking districtm to appnexus

---

dev-docs/bidders/rdn.md

Add bid parameters to the RDN adapter

RDN adpter - add document

---

dev-docs/bidders/colombia.md

Add new colombia bidder

---

download.md
overview/analytics.md

Our analytics adapter was submitted and merged via this PR: https://github.com/prebid/Prebid.js/pull/3069.

New analytics adapter from Adagio

---

dev-docs/bidders/invibes.md

Invibes Bid Adapter doc update: support for GDPR
link to prebid.js pull request:
https://github.com/prebid/Prebid.js/pull/3151

InvibesBidAdapter - support GDPR

---

dev-docs/bidders/visx.md

Removed the docs on the deprecated priceType option.

Removed deprecated priceType option

---

dev-docs/publisher-api-reference.md

this question came up recently, thought it worth a note.

clarifying effect of standard targeting override

---

dev-docs/modules/dfp_express.md

added an example and making reference to the GAM name change

express -- clarifying integration

---

dev-docs/bidders/rtbhouse.md

Added supported media types definition by RTBHouseAdapter.

Add media_types declaration to rtbhouse.md

---

dev-docs/bidders/grid.md

Hello, add please doc file for TheMediaGrid Bid Adapter.

Doc file for TheMediaGrid Bid Adapter

---

dev-docs/bidders/appnexus.md

Adding custom keys documentation for appnexus.
https://github.com/prebid/Prebid.js/pull/3201

Custom keys docs for appnexus

---

dev-docs/troubleshooting-tips.md

Updated the debugging snippet to account for no bids with new API (`pbjs.getNoBids()`)

added no bids to debugging snippet

---

dev-docs/publisher-api-reference.md

Trying to shed a little light on https://github.com/prebid/Prebid.js/issues/3226

Warning for labels not being filters of sizeConfig

---

dev-docs/bidders/adformOpenRTB.md

Adding docs of adformOpenRTB adapter.

adformOpenRTB adapter info

---

dev-docs/bidders/nextMillenium.js

Documentation for new bid adapter nextMillenium

Add nextMilleniumBidAdapter doc

---

download.md
overview/analytics.md

Adapter PR: https://github.com/prebid/Prebid.js/pull/3285

add openx to analytics overview and download

---

dev-docs/bidders/otm.md

Adding docs for OTM bid adapter.

OTM bid adapter info

---

dev-docs/bidders/pubmatic.md

Added description for dctr parameter usage.

added desc for dctr

---

dev-docs/show-prebid-ads-on-amp-pages.md

Update cookie sync example to load from jsdelivr

---

dev-docs/publisher-api-reference.md

Add docs for new field in s2sConfig.
Related Prebid.js PR that introdces the changes:
https://github.com/prebid/Prebid.js/pull/3375
Please wait on merging this PR until the linked PBJS PR is merged.

add userSyncLimit field in s2sConfig

---

dev-docs/bidders/supply2.md

Hello, add please doc file for Supply2 Bid Adapter

Added doc-file for Supply2 Bid Adapter

---

dev-docs/bidders/adtelligent.md

Related pull request https://github.com/prebid/Prebid.js/pull/3359

Add gdpr support for adtelligent

---

dev-docs/modules/pubCommonId.md

Fixed a typo.  _pubcid_output should be _pubcid_optout.

Fix _pubcid_optout typo

---

dev-docs/publisher-api-reference-old.md
dev-docs/publisher-api-reference.md

corresponding code changes pull req(https://github.com/prebid/Prebid.js/pull/3415)

Add iframes at the bottom of the html tag

---

_layouts/home.html

Review code on home.html for capitalization fix:

Fixed icon issue

---

overview/intro.md

I created a separate branch for this fix because I think there might be an issue with stage.

Fixed two H1 headers on intro page.

---

dev-docs/publisher-api-reference.md

Documentation for new `setConfig({useBidCache: false})`

added new setConfig option, useBidCache

---

dev-docs/plugins/bc/about-bc-prebid-plugin.md
dev-docs/plugins/bc/bc-prebid-plugin-prebid-options.md

updates for Brightcove plugin v 0.4 docs

---

dev-docs/bidders/ozone.md

Documentation for new Ozone Project adapter.

added ozone adapter docs

---

dev-docs/faq.md
dev-docs/publisher-api-reference.md

updating FAQ and API reference with the 2.0 false-by-default feature

useBidCache false-by-default

---

_data/message.yml
_posts/2019-01-31-prebidjs-2.md

new blog entry and home page message

pbjs 2.0 announcement

---

dev-docs/bidders/medianet.md

Documentation for native support in Media.net Adapter

Media.net : Native support added

---

dev-docs/bidders/viewdeo.md
dev-docs/bidders/viewdeos.md

Added ```viewdeos``` as a new bidder code alias for gamoshi.
Thanks.

Viewdeo: new bidder code alias for gamoshi

---

dev-docs/bidders/admedia.md

AdMedia Bidder Adaptor updated docs

updated Admedia docs

---

dev-docs/bidders/richaudience.md

Documentation for Rich Audience Bidder Adapter

Rich Audience Bidder Adapter

---

dev-docs/bidders/richAudience.md
dev-docs/bidders/richaudience.md

Rename file name and bidder code because I get an error when I try to download the adapter from the website

Rename File Name

---

dev-docs/publisher-api-reference.md

added `extPrebid` argument and a video example in support of https://github.com/prebid/Prebid.js/pull/3528

s2sConfig updates

---

assets/css/style.css

made a small tweak based on feedback in https://github.com/prebid/prebid.github.io/issues/1160
I think the darker header goes part of the wayw towards improving the readability.

darkening headers

---

assets/css/style.css
dev-docs/modules/adpod.md
dev-docs/modules/freewheel.md
dev-docs/modules/iabCatagoryTranslation.md

Fixed the front matter on the 3 module files related to long-form video. Ignore the .css file, I made a quick change to font-weight

fixed front matter on module files

---

dev-docs/bidders/loopme.md

Added documentation for LoopMe adapter

New Adapter LoopMe

---

dev-docs/bidders/microad.md

added document for microad adapter

New Adapter MicroAd

---

adops/step-by-step.md

not working with safeframes and newer prebid universal creative

added note about older versions of PBJS 

---

dev-docs/modules/adpod.md

I realized that we didn't document the `setConfig` options for the `adpod` module anywhere.
I created this PR with the information on the currently available option and a description of its behavior.  Please let me know what you think.

add description for adpod setConfig option

---

dev-docs/bidder-adaptor.md

@MartianTribe @jeanstemp Technically it is correct but would definitely need your help to correct my grammar :-). 
I will assign @jsnellbaker to review technical stuff.

Added more info to help bidders add long-form support

---

dev-docs/bidders/brightcom.md

Add documentation for Brightcom adapter

Submit Brightcom Bidder Adaptor doc

---

dev-docs/bidders/mytarget.md

Added documentation for myTarget adapter

New adapter myTarget

---

dev-docs/show-native-ads.md

Adds Documentation for Prebid.js PR https://github.com/prebid/Prebid.js/pull/3387

Adding additional Native parameters Doc

---

_data/sidebar.yml
prebid-server/developers/add-new-analytics-module.md
prebid-server/developers/add-new-bidder.md
prebid-server/developers/cookie-syncs.md
prebid-server/developers/currency-converter.md
prebid-server/developers/default-request.md
prebid-server/developers/gdpr.md
prebid-server/developers/stored-requests.md
prebid-server/endpoints/bidders/params.md

Updated the stored-request file with interstitial ad sample

Prebid server docs

---

_includes/alerts/alert_important.html
_includes/alerts/alert_note.html
_includes/alerts/alert_tip.html
_includes/alerts/alert_warning.html
_includes/send-all-bids-keyword-targeting.md
adops/before-you-start.md
assets/css/style.css

Made changes per: 
https://jira.corp.appnexus.com/browse/DOC-5971?filter=-1
and some other editorial changes.

Pb adops edits

---

dev-docs/publisher-api-reference.md

This PR update the s2s config for syncUrlModifier documentation and usage

update s2s config params

---

dev-docs/bidders/mediafuseLift.md

Add dev-docs for MediaFuse Lift (Orbitsoft alias).
Main request: https://github.com/prebid/Prebid.js/pull/3682

Added MediaFuse Lift dev-docs

---

dev-docs/bidders/synacormedia.md

Synacormedia: add post & bidfloor to documentation

Synacormedia: add post & bidfloor to documentation

---

dev-docs/show-native-ads.md

Rewrote, added the `class` requirement, and placed in an alert box

Rewrite native script section

---

dev-docs/bidders/smartrtb.md

SmartRTB doc file

---

dev-docs/bidders/adspend.md

Hi. I support AdSpend bidder adapter now. Can you please accept documentation?

Add adspend adapter doc

---

dev-docs/modules/userId.md

added opt-out

---

prebid-server/developers/cookie-syncs.md

Removed the escape characters from the URL reference in the blockquote

Removed escape characters from URL reference.

---

dev-docs/bidders/nafdigital.md

Add documentation for NAF Digital adapter

Submit NAF Digital adapter doc

---

dev-docs/bidders/synacormedia.md

Synacormedia: Added video parameters to documentaion.

Synacormedia: Added video parameters to documentaion.

---

dev-docs/bidders/sonobi.md

Docs update for https://github.com/prebid/Prebid.js/pull/3743

Updated Sonobi Docs to add userId support for unifiedId/tradedesk

---

dev-docs/bidders/go2net.md

- A link to a PR on the prebid.js repo [#3763](https://github.com/prebid/Prebid.js/pull/3763)

go2net docs

---

dev-docs/bidders/cleanmedia.md
dev-docs/bidders/gambid.md
dev-docs/bidders/viewdeos.md

Fix download links of gamoshi bidder code aliases

Gamoshi: Fix aliases download link

---

dev-docs/show-native-ads.md

Add privacyIcon field for native ads

Update documentation for native ad privacy icon

---

examples/video/brid-player-demo.html
examples/video/bridplayer-pbserver-demo.html
examples/video/index.md

Just added 2 new pages which provide prebid examples using the Brid player.

Added Brid player prebid examples for video.

---

dev-docs/bidders/pubmatic.md

and explain when mutli-sized requests are sent

Update information on PubMatic adSlot parameter 

---

adops/setting-up-prebid-with-the-appnexus-ad-server.md
dev-docs/examples/use-prebid-with-appnexus-ad-server.md

This PR adds some information on how to enable SafeFrame when using the AST tag with Prebid.js.

add notes on how to enable safeframes with AST tags

---

dev-docs/bidders/hpmdnetwork.md

Add dev-docs for HPMD Network bid adapter

Add HPMD Network bid adapter dev-docs

---

dev-docs/bidders/richaudience.md

Updating files name and bidder code for avoiding future errors

RichAudience: File Names Updated

---

dev-docs/bidders/mgid.md

native support + bidfloor and currency optional parameters

native support & some optional params added

---

dev-docs/bidders/cpmstar.md

Added cpmstarBidAdapter docs

---

dev-docs/bidders/reload.md

Reload Adapter - New

---

dev-docs/bidders/districtm.md

The adapter is not S2S only, updated to reflect this.

Update documentation on districtm.md

---

adops/send-all-bids-adops.md
adops/setting-up-prebid-for-amp-in-dfp.md
adops/setting-up-prebid-with-the-appnexus-ad-server.md
adops/step-by-step.md
dev-docs/show-prebid-ads-on-amp-pages.md
prebid-mobile/adops-line-item-setup-dfp.md
prebid-mobile/adops-line-item-setup-mopub.md

Documentation changes for https://github.com/prebid/prebid-universal-creative/pull/62

added hbPb macro replacement to the example creative templates

---

dev-docs/bidders/adxcg.md
prebid/prebidjsReleases.md

Adding userId ref based on https://github.com/prebid/Prebid.js/pull/3824

Adxcg userid

---

overview/analytics.md

Adds STAQ contact information to the  overview/analytics.md page.

add STAQ to list of analytics vendors

---

prebid-mobile/pbm-api/android/code-integration-android.md

Adding in implement Maven for version 1.1

Android SDK: Modified implement maven for version 1.1

---

dev-docs/bidders/rdn.md

documentation for https://github.com/prebid/Prebid.js/pull/3902

Added documentation for configuration option rdn.endpoint

---

dev-docs/bidders/yieldmo.md

adds bidFloor param and userId to variables for yieldmo module

---

dev-docs/bidders/nextMillennium.md

update and rename NextMillennium

---

dev-docs/bidders/slimcut.md

Add documentation for SlimCut bid adapter.

Add SlimCut bid adapter

---

dev-docs/bidders/feedad.md

added parameter documentation for the new FeedAd bidder adapter

added FeedAd adapter parameters

---

download.md
overview/analytics.md

New Analytics Adapter
Sibling PR: https://github.com/prebid/Prebid.js/pull/3846

PLEASE MERGE -> Adding Scaleable Analytics to download/overview markdown files

---

download.md
overview/analytics.md

PR just to add STAQ analytics adapter to the downloads.md page.

Add staq analytics to downloads page

---

dev-docs/bidders/bidglass.md

Added dev-doc for the new bidglass adapter

(New adapter) Added bidglass dev-doc

---

prebid-mobile/pbm-api/android/code-integration-android.md
prebid-mobile/pbm-api/ios/code-integration-ios.md

This PR Updates the following:
- Modifies the target iOS platform from 11.0 to 9.0
- Adds documentation to resize ad slots using Native code

Add resize function to iOS integration

---

dev-docs/bidders/indexExchange.md

Please see related pull request https://github.com/prebid/Prebid.js/pull/3901

Updated documentation for video adapter support.

---

dev-docs/bidders/SafeReach.md

Bidder configuration documentation for Safe Reach Adapter

SafeReach Adapter

---

dev-docs/bidders/seedtag.md

Adding documentation for the seedtag bid adapter

Add seedtag bid adapter

---

dev-docs/bidders/indexExchange.md

Discussed this update in last week's Prebid Server meeting -- would like the @ix-prebid-support team to review.

ix doesn't require size param for prebid server

---

dev-docs/bidders/kargo.md

Re https://github.com/prebid/Prebid.js/pull/3981

Kargo docs adding Tradedesk to userids list

---

dev-docs/modules/userId.md
dev-docs/publisher-api-reference.md

Documentation for pbjs.getUserIds method in User Id module

Documentation for pbjs.getUserIds method in User Id module

---

dev-docs/bidders/padsquad.md

Documentation for padsquad bid adapter

Padsquad bid adapter

---

dev-docs/bidders/logicad.md

Add Logicad for Publishers bid adapter dev-docs

Logicad for Publishers bid adapter

---

dev-docs/bidders/adastaMedia.md
dev-docs/bidders/cleanmedia.md
dev-docs/bidders/gambid.md
dev-docs/bidders/viewdeos.md

Modify existing aliases docs
Maintainer contact email: dev@gamoshi.com

Gamoshi: Modify aliases description

---

_data/message.yml
_layouts/home.html

Refactored message banner code.

Pb banner edit

---

examples/video/flowplayer-demo.html
examples/video/index.md

This example demonstrates prebid.js integrated with Flowplayer

Flowplayer video example

---

dev-docs/bidders/smilewanted.md

Refers to https://github.com/prebid/Prebid.js/pull/4064#issuecomment-519545722

Adding support of video for SmileWanted Adapter

---

dev-docs/bidders/sonobi.md

Updated Sonobi bidder params required explaination. The previous expl…aination was not clear enough for people implementing the adatper.

Sonobi - Param definition update

---

dev-docs/bidders/visx.md

Added note regarding SafeFrame support

VISX update documentatino

---

dev-docs/bidders/criteo.md

We're adding the support of deal in our adapter.

Criteo Adapter - Added deal support

---

dev-docs/bidders/sublime.md

Adding documentation for the Sublime bid adapter

Add Sublime bid adapter

---

_data/sidebar.yml
prebid-server/endpoints/getuids.md

Added the missing getuids doc. Please review to make ensure it is current.

Pb server docs

---

dev-docs/bidders/9MediaOnline.md

Add 9MediaOnline new adaptor alias
- contact email of the adapter’s maintainer

Gamoshi: Add 9MediaOnline bidder adapter alias docs

---

dev-docs/bidders/beachfront.md

Adds documentation for optional video `placement` param.

Add placement param to Beachfront doc

---

dev-docs/bidders/nobidBidAdapter.md

Nobid Prebid Adapter documentation.

Nobid Prebid Adapter documentation commit

---

dev-docs/bidders/optimera.md

This relates to the new feature issue: https://github.com/prebid/Prebid.js/issues/4105
PR: https://github.com/prebid/Prebid.js/pull/4106

Optimera Bid Adapter device param update.

---

dev-docs/modules/userId.md

Documentation for https://github.com/prebid/Prebid.js/pull/4140

userIdTargeting related mention in userId module doc

---

dev-docs/bidders/buzzoola.md

Buzzoola Bid Adapter doc

---

dev-docs/bidders/lockerdome.md

This is not a breaking change.
Related: https://github.com/prebid/Prebid.js/pull/4176

Update LockerDome adUnitId bid param

---

overview/analytics.md

Added AdxPremium adapter to the list

Added adxpremium analytics adapter

---

dev-docs/bidders/openx.md

Fixes issue: https://github.com/prebid/Prebid.js/issues/4186

OpenX Adapter fix: updating outdated video examples in documentation

---

dev-docs/modules/index.md
dev-docs/modules/userId.md

updated userid module docs to add refresh in seconds option to ID5 examples, as well as adjust some of the text for ID5

ID5 refresh in seconds docs

---

dev-docs/bidders/pubmatic.md

PubMatic: updated list of User Id partners

PubMatic: updated list of User Id partners

---

dev-docs/modules/userId.md

added link to ID5 release notes and did some minor text clean up

id5 - add link to our release notes, and some minor text clean up

---

dev-docs/modules/userId.md

Added a more complete definition of the IdentityLink as it relates to prebid.

Idl addtl info

---

dev-docs/bidders/criteo.md

Updated our doc to fix some inconsistencies

Fixed some inconsistencies into criteo adapter's video documentation

---

dev-docs/publisher-api-reference.md
sandbox/apiDocs/html/userSync.html

related PR https://github.com/prebid/Prebid.js/pull/4115

add documentation for auctionDelay in userSync

---

_data/sidebar.yml
dev-docs/modules/index.md
dev-docs/modules/konduit.md

Initial documentation for Konduit Accelerate Video Module.

Konduit Module documentation.

---

dev-docs/bidders/pubmatic.md

added LiveIntent in supported sub-module list
https://github.com/prebid/Prebid.js/pull/4306

added LiveIntent in supported sub-module list

---

dev-docs/publisher-api-reference.md

@jeanstemp - I didn't find anywhere that described setConfig({cache}). This was kinda hard to write about, so could definitely use your review here. There are probably places that could link to this, like /prebid-video/video-getting-started.html, but will leave video review for a separate ticket

adding video cache to pub api doc

---

dev-docs/bidders/smartrtb.md

SmartRTB: removing alias code

---

dev-docs/bidders/gamoshi.md

- Indicate that we are supporting for userSync using ID5 and UnifiedId
- Please refer to [#4319](https://github.com/prebid/Prebid.js/pull/4319 ) PR in Prebid.js repository.

Gamoshi: Add support for userIds

---

dev-docs/bidders/pubmatic.md

PubMatic to support Parrable User Id sub-module

PubMatic to support Parrable User Id sub-module

---

dev-docs/bidders/pubmatic.md

PubMatic coppa support update

---

dev-docs/bidders/waardex

Adding a new HB bidder description - WaardeX

Create waardex alias for adkernel

---

dev-docs/bidders/7xbid.md

related to https://github.com/prebid/Prebid.js/pull/4328

add dev doc for 7xbid adapter

---

dev-docs/modules/userId.md

We updated some wording around LiveIntent User Id module.

Liveintent docs update

---

dev-docs/bidders/beachfront.md

Adds documentation for optional player `adPosterColor` param.

Update beachfront doc

---

dev-docs/bidders/mobsmart.md

Create Mobsmart adapter doc

---

dev-docs/bidders/adagio.md

Improve the doc about Adagio bidder adapter, related to prebid/Prebid.js#4217

Update adagioBidAdapter documentation

---

_includes/dev-docs/native-image-asset-sizes.md
dev-docs/adunit-reference.md

Docs update for PR: https://github.com/prebid/Prebid.js/pull/4434

add min_height field to native request example

---

dev-docs/bidders/1ad4good.md

This is open source bidder for non profit ads that I created. Could be used to fill unsold inventory for a good causes.
More info about this project can be found here: http://1ad4good.org
It is my weekend project. I hope it will be net positive for this community as:
1) open source education about tech and header bidding 
2) always filling (good for some test cases for ad ops 
3) providing some free ad placements to non profits
Thank you!

Add doc for 1ad4good.org bidder

---

dev-docs/bidders/pubmatic.md

PubMatic supporting updated Criteo User Id module
https://github.com/prebid/Prebid.js/pull/4431

PubMatic supporting updated Criteo User Id module

---

dev-docs/bidders/districtmdmx.md

Added districtmdmx schain support

---

dev-docs/bidders/conversant.md

Add pubcid_name parameter for conversant adapter.

Conversant adapter adds pubcid_name param

---

dev-docs/bidders/visx.md

Added documentation for publishers with an explanation of how to configure currency for VIS.X adapter.

VIS.X update documentation

---

dev-docs/bidders/newborntownWeb.md

Create newborntownWeb adapter doc

Create newborntownWeb adapter doc

---

dev-docs/bidders/gumgum.md

Updates documentation for schain and userid support

GumGum adapter - documentation update

---

dev-docs/bidders/appnexus.md

Adding missing docs for coppa.
https://github.com/prebid/Prebid.js/pull/4253

Appnexus adapter coppa support

---

dev-docs/bidders/appnexus.md

https://github.com/prebid/Prebid.js/pull/4531

Appnexus ccpa docs

---

dev-docs/bidders/lockerdome.md

Related: https://github.com/prebid/Prebid.js/pull/4360

Add schain_supported to LockerDome adapter doc

---

dev-docs/bidders/pubmatic.md

PubMatic to support britepoolId
Refer: https://github.com/prebid/Prebid.js/pull/4532

PubMatic to support britepoolId

---

dev-docs/bidders/indexExchange.md

Added the id parameter for Banner and Video.

ix: Added the id parameter for Banner and Video.

---

dev-docs/bidders/pubmatic.md

Refer: https://github.com/prebid/Prebid.js/pull/4533

PubMatic to support CCPA/USP

---

dev-docs/bidders/quantcast.md

Added usp_supported to bidder documentation.

Update QC bidder documentation for CCPA

---

dev-docs/bidders/deepintent.md

New Addition with examples for User Object override.

deepintent: added user param example

---

dev-docs/bidders/lockerdome.md

Related Pull Request: https://github.com/prebid/Prebid.js/pull/4575

Add CCPA / US privacy data support for LockerDome adapter

---

dev-docs/bidders/sonobi.md

Dev docs for new param to sonobi bidder adapter "keywords"

New Sonobi param - keywords

---

dev-docs/bidders/rtbsolutions.md

Adding new RTB Solutions adapter docs

RTB Solutions adapter docs

---

dev-docs/bidders/criteo.md

Related PR : https://github.com/prebid/Prebid.js/pull/4604

Add support for CCPA consent in Criteo adapter

---

dev-docs/bidders/aduptech.md

Fixed wording/description for the AdUp Technology bidding adapter.
- steffen.anders@adup-tech.com
- sebastian.briesemeister@adup-tech.com
- marten.lietz@adup-tech.com
New PR for the adapter: https://github.com/prebid/Prebid.js/pull/4603
Initial PR for the docs: https://github.com/prebid/prebid.github.io/pull/866

Fix docs for AdUp Technology bid adapter

---

_data/partners.yml

mediamath link update

---

dev-docs/bidders/fidelity.md

Fidelity Media Bbid Adapter Update.

---

dev-docs/bidders/oneVideo.md

adding CCPA support in docs , changes are already merged : https://github.com/prebid/Prebid.js/pull/4571

OneVideo Adaptor : CCPA support

---

dev-docs/plugins/cross-player-prebid-component/about-cross-player-prebid-component.md
dev-docs/plugins/cross-player-prebid-component/cross-player-api.md
dev-docs/plugins/cross-player-prebid-component/cross-player-communication.md
dev-docs/plugins/cross-player-prebid-component/cross-player-config.md
dev-docs/plugins/index.md

Docs to go with this component: https://github.com/prebid/cross-player-prebid-component

Docs for Cross Player Prebid Component

---

dev-docs/bidders/eplanning.md

Add usp_supported and gdpr_supported lines in top of EPlanning page

Add usp and gdpr support for EPlanning adapter

---

dev-docs/bidders/beachfront.md

Adds CCPA (US Privacy) support to the Beachfront doc.

Add CCPA support to Beachfront doc

---

dev-docs/modules/consentManagementUsp.md

This change documents the static API introduced in the Prebid.js repo pull request: prebid/Prebid.js#4685

Added docs and example for the static API to the consentManagementUsp module.

---

_data/sidebar.yml
dev-docs/publisher-api-reference.md
features/pbAdSlot.md

External docs for https://github.com/prebid/Prebid.js/issues/4149
Also making the event documentation more useful.

pbAdSlot and beforeRequestBids documentation

---

dev-docs/bidders/nobidBidAdapter.md

Added support for CCPA to the Nobid Adapter.

NoBid: Added support for CCPA

---

dev-docs/bidders/gamoshi.md

Add support for CCPA and SChain 
- contact email of the adapter’s maintainer

Gamoshi: Add support for ccpa and schain

---

dev-docs/bidders/revcontent.md

RevContent Bidder Documentation

RevContent Bidder Documentation

---

dev-docs/bidders/tpmn.md

Added TPMN Markdown

---

dev-docs/bidders/fluct.md

The following sample params is correct.
https://github.com/prebid/Prebid.js/blob/master/modules/fluctBidAdapter.md

Fix param examples for fluctBidAdapter

---

prebid-mobile/pbm-api/android/code-integration-android.md
prebid-mobile/pbm-api/ios/code-integration-ios.md

Fixed link to MoPub register pages.

---

dev-docs/bidders/smartadserver.md

Udpate documentation of start delay to better reflect reality

SmartAdServer: update documentation of start delay to better reflect reality

---

download.md

Resolving the issue https://github.com/prebid/prebid.github.io/issues/1778

Add LiveIntend ID sub-module to Download page

---

dev-docs/modules/userId.md
download.md

- no longer need to include the userId module in the build.
- added remaining sub-modules to download page

pbjs3.0 userid module update

---

troubleshooting/pbs-troubleshooting.md
troubleshooting/troubleshooting-guide.md
troubleshooting/troubleshooting.md

Also broke out the prebid server troubleshooting into it's own doc

adding stored response docs

---

dev-docs/bidders/byplay.md

https://github.com/prebid/Prebid.js/pull/4646

add ByPlay adapter docs

---

dev-docs/bidders/audiencerun.md

Pull request for adapter audiencerun https://github.com/prebid/Prebid.js/pull/4761

Documentation for audiencerun adapter

---

dev-docs/bidders/vuble.md

GDPR support added on the vuble bidder
https://github.com/prebid/Prebid.js/pull/4804

Add: gdpr consent for vuble bidder

---

dev-docs/bidders/adkernel.md
dev-docs/bidders/adkernelAdn.md

Declare CCPA support for adkernel and adkernelAdn adapters.

Adkernel: declare ccpa support

---

dev-docs/bidders/tribeOS.md

Initial documentation for the Prebid tribeOS bidder adapter

initial tribeOS bidder adapter doc commit

---

prebid-server/endpoints/openrtb2/video.md

the difference between the param `shal` and 
`sha1` is a big deal

Fix a few typos

---

dev-docs/examples/adunit-refresh.md
dev-docs/examples/basic-example.md
dev-docs/examples/custom-price-buckets.md
dev-docs/examples/instream-banner-mix.md
dev-docs/examples/multi-format-example.md
dev-docs/examples/native-ad-example.md
dev-docs/examples/postbid.md
dev-docs/examples/size-mapping.md
dev-docs/examples/use-prebid-with-appnexus-ad-server.md

This is a test commit to see how some updated jsfiddles appear on the dev site for prebid.org (and hopefully bypass the cookie issues seen when locally host the server).

test commit for new fiddles

---

dev-docs/bidders/triplelift.md

Pending merge of this PR: https://github.com/prebid/Prebid.js/pull/4850

TripleLift: Add COPPA support to documentation

---

dev-docs/bidders/synacormedia.md

I've updated the documentation for schain object support for synacormedia adapter.

Synacore: Updated documentation for schain support

---

dev-docs/adunit-reference.md
dev-docs/bidder-adaptor.md
dev-docs/publisher-api-reference.md

Added first party data to the API doc, the bidder adapter doc, and the AdUnit reference.
Couldn't resist refactoring the bidder adapter doc a bit.

first party data initial commit

---

dev-docs/bidders/revcontent.md

Update layout, media_type, and privacy act statuses.

Correct Revcontent parameters

---

dev-docs/bidders/appnexus.md

Update the userid reference in the appnexus bidder.
Related to https://github.com/prebid/Prebid.js/pull/4862

update criteo userid name for appnexus bidder

---

dev-docs/bidders/deepintent.md

Docs for the Ad position. Also corrected type for height and width.

DeepIntent: docs changed

---

dev-docs/bidders/eplanning.md

Add description for new paramter (ml) introduced in PR https://github.com/prebid/Prebid.js/pull/4878

Add ml parameter description for eplanning adapter

---

README.md

tried to set it up on a new laptop and found the instructions needed a tweak or two.

updating jekyll install instructions

---

dev-docs/bidders/indexExchange.md

This change has associated prebid adapter changes:
- https://github.com/prebid/Prebid.js/pull/4957

IX Adapter - Increase banner TTL to 300s

---

dev-docs/bidders/deepintent.md

Fix for mentioning CCPA support.

deepintent: ccpa support header added

---

dev-docs/bidders/unicorn.md

UNICORN bid adapter documentation

add UNICORN bid adapter docs

---

dev-docs/bidders/clicktripz.md

Submitting Clicktripz bidder dev doc for acceptance into Prebid

Adds Clicktripz bidder adapter to dev-doc notes

---

dev-docs/bidders/medianet.md

Documentation for Media.net PR :  [prebid/Prebid.js#4925  ](https://github.com/prebid/Prebid.js/pull/4925)

Media.net : add support for userId module

---

download.md
overview/analytics.md

Documentation for merged Media.net Analytics Adapter PR :  [prebid/Prebid.js#5016  ](https://github.com/prebid/Prebid.js/pull/5016)

Media.net : adds Analytics Adapter 

---

dev-docs/bidders/readpeak.md

Add a missing parameter to Readpeak bidder adapter documentation.

Update Readpeak Adapter Documentation

---

dev-docs/bidders/yieldlift.md

Documentation for YieldLift bid adapter

yieldlift adapter docs

---

dev-docs/bidders/hybrid.md

Added documentation for Hybrid.ai Adapter to dev-docs

Added documentation for Hybrid.ai Adapter

---

dev-docs/bidders/bidlab.md

- Adapter PR
https://github.com/prebid/Prebid.js/pull/5020

Bidlab adapter docs

---

dev-docs/bidders/fidelity.md

PBJS PR: https://github.com/prebid/Prebid.js/pull/4945

Add Schain support. Fidelity Media bid adapter

---

dev-docs/adunit-reference.md

Documenting the long-hidden feature of 'twin' adunit codes. See https://github.com/prebid/Prebid.js/issues/5044

twin ad unit codes

---

dev-docs/bidders/relaido.md

- Adapter PR
https://github.com/prebid/Prebid.js/pull/5101

Relaido adapter docs

---

dev-docs/bidders/wipes.md

WIPES Adapter PR: https://github.com/prebid/Prebid.js/pull/5051

WIPES adapter docs

---

dev-docs/bidders/conversant.md
dev-docs/bidders/openx.md
dev-docs/bidders/rubicon.md

missed a few userid modules that are supported

correct a few bid adapters' support of user id modules which were missed in the last round

---

dev-docs/bidders/adagio.md

This PR is about updating the scope of the params `environment` and `placement` which are now _required_.

Adagio: update scope params column

---

dev-docs/modules/userId.md

A critical piece of information is missing. You'll need to add the `userId` module as well to make the user id stuff work :smile:

Add information about userId module

---

dev-docs/modules/userId.md
dev-docs/publisher-api-reference.md

Documentation for https://github.com/prebid/Prebid.js/pull/5108

documentation for getUserIdsAsEids

---

dev-docs/bidders/pubmatic.md

adding support for tcf2 for PubMatic

adding support for tcf2 for PubMatic

---

dev-docs/bidders/deepintent.md

Doc request for 
https://github.com/prebid/Prebid.js/pull/5147

DeepIntent: Gdpr support

---

dev-docs/bidders/bluebillywig.md

Docs for the Blue Billywig bid adapter PR
Prebid.js PR: https://github.com/prebid/Prebid.js/pull/5118

New bid adapter: Blue Billywig docs

---

dev-docs/bidders/admixer.md

- A link to a PR on the Prebid.js repo [#5169](https://github.com/prebid/Prebid.js/pull/5169)

Admixer Bidder Adapter add gdpr and usp

---

dev-docs/bidders/quantumdex.md

Add Quantumdex Bid Adapter docs

Add Quantumdex Bid Adapter docs

---

dev-docs/bidders/adprime.md

Adapter: https://github.com/prebid/Prebid.js/pull/5172

New Adprime Prebid adapter

---

prebid-mobile/pbm-api/android/pbm-video-rewarded-adunit-android.md
prebid-mobile/pbm-api/android/pbm-videointerstitialadunit-android.md
prebid-mobile/pbm-api/android/pbm-videooutstreamadunit-android.md
prebid-mobile/pbm-api/ios/pbm-video-rewarded-adunit-ios.md
prebid-mobile/pbm-api/ios/pbm-videointerstitialadunit-ios.md
prebid-mobile/pbm-api/ios/pbm-videooutstreamadunit-ios.md

PBSDK 1.6: video signals

---

dev-docs/bidders/selectmedia.md

Add selectmedia to bidders list & downloads page

Add selectmedia to bidders list & downloads page

---

features/pbAdSlot.md

PR to fix issue: https://github.com/prebid/prebid.github.io/issues/1982

Fix typos in pbAdSlot exampe

---

dev-docs/bidders/unicorn.md

related to https://github.com/prebid/Prebid.js/pull/5184

update UNICORN BidAdapter docs

---

dev-docs/modules/floors.md

Added a fetchStatus field in the analytics interface.

Floors Module: new analytics fields

---

dev-docs/bidders/kubient.md

Adding Prebid Kubient Bidder Adapter. The alias to fidelity
See: https://github.com/prebid/Prebid.js/pull/5302

Add Prebid Kubient Bidder Adapter

---

dev-docs/bidder-adaptor.md

Change iabSubCatId name to primaryCatId. More info in linked Prebid.js PR.

change iabSubCatId name to primaryCatId

---

download.md
overview/analytics.md

add adWMG Analytics to the list of analytics adapters

add adWMG Analytics to the list

---

dev-docs/bidders/onomagic.md

Add documentation for Onomagic Adapter

Submit Onomagic Adapter doc

---

dev-docs/publisher-api-reference.md

Docs PR for https://github.com/prebid/Prebid.js/pull/5209

multiple PBS feature

---

dev-docs/bidders/nextroll.md

Related to https://github.com/prebid/Prebid.js/pull/5319

Update NextRoll docs for native support

---

dev-docs/bidders/glimpseProtocol.md

* Initial submission
* Author: Tim Holmes-Mitra <tim@glimpseprotocol.io>

New Adaptor: Glimpse Protocol

---

dev-docs/bidders/h12media.md

Add module H12 Media

---

_data/sidebar.yml
_includes/video/pb-is-app.html
_layouts/video_sample.html
examples/video/instream/adplayerpro/pb-ve-adplayerpro.html

Added Ad Player Pro video example

Added Ad Player Pro video example

---

dev-docs/bidders/gmossp.md

Add Documentation for GMOSSP Adapter

---

dev-docs/bidders/vidazoo.md

As part of:
https://github.com/prebid/Prebid.js/pull/5386

Vidazoo Adapter: Feature/user-id

---

dev-docs/bidders/appnexus.md

Updated video params for the appnexus bidder.  Related to https://github.com/prebid/Prebid.js/pull/5394

update appnexus video params

---

dev-docs/bidders/conversant.md

Add conversant to the list of adapters that support TCF2

declare conversant TCF 2 support

---

dev-docs/bidders/mediasquare.md

changes about what the mediasquare adapter supports

Update mediasquare adapter params

---

dev-docs/bidders/amx-rtb.md

Adding documentation for AMX RTB prebid bid adapter. See code PR here: https://github.com/prebid/Prebid.js/pull/5383

Add AMX RTB adapter documentation

---

dev-docs/bidders/sonobi.md

Related to code PR https://github.com/prebid/Prebid.js/pull/5491

Sonobi: Removing digitrust support

---

dev-docs/bidders/welect.md

Documentation PR according to the adapter submission: https://github.com/prebid/Prebid.js/pull/5457

add docs for welect-bidder-adapter

---

dev-docs/publisher-api-reference.md

documents https://github.com/prebid/Prebid.js/pull/5419

add default ttl to s2sconfig

---

dev-docs/modules/userId.md

docs for https://github.com/prebid/Prebid.js/pull/5406

update id5 userId docs with new `pd` field

---

dev-docs/bidders/performax.md

Documentation PR according to the adapter submission: prebid/Prebid.js#5480

Performax adapter

---

dev-docs/bidders/yieldlab.md

See merged and released https://github.com/prebid/Prebid.js/pull/5374
Forgot about the docs 😳

Add customParams to Yieldlab Bid Params

---

dev-docs/modules/userId.md

Documents https://github.com/prebid/Prebid.js/pull/5500

Document subdomain to domain change for 4.0

---

dev-docs/bidders/synacormedia.md

This covers updates based on https://github.com/prebid/Prebid.js/pull/5506

[synacormedia] Update Documentation for latest changes

---

dev-docs/bidders/adtelligent.md

Update info about adtelligent adapter

Update adtelligent doc

---

dev-docs/bidders/apstream.md

Related to: prebid/Prebid.js#5508

AP Stream adapter: Update docs, add 'front matter'

---

dev-docs/bidders/brightcom.md

Update Brightcom doc file to support GDPR

Brightcom support GDPR

---

dev-docs/bidders/triplelift.md

- update documentation for instream support

update triplelift docs for instream video

---

dev-docs/bidders/pubmatic.md

Fix some incorrect version numbers

PubMatic: Add Safe Frame OK

---

dev-docs/bidder-adaptor.md
dev-docs/modules/consentManagement.md

Documents https://github.com/prebid/Prebid.js/pull/5600

Update consentManagement.md to add AC string

---

dev-docs/bidders/mediago.md

Add MediaGo Prebid Bidder Adapter help docs.

mediago prebid bidder adapter docs

---

dev-docs/show-outstream-video-ads.md

Documents https://github.com/prebid/Prebid.js/pull/5638

Update show-outstream-video-ads.md for backupOnly renderers

---

dev-docs/bidders/ironsource.md

1.Change ironsource to be lower case all over
2.add pbjs: true

Adaptation of md file to latest version of bidder

---

dev-docs/bidders/eplanning.md

Added TCF v2.0 support to the documentation
tcf2_supported: true

Added TCF v2.0 support to the documentation

---

dev-docs/bidders/concert.md
dev-docs/bidders/edgequeryx.md

Add documentation for concert bid adapter

New Adapter: Concert

---

dev-docs/bidders/adocean.md

Changes:
- mark tcf2 as supported
- add contact information.

Updated information for AdOcean adapter.

---

dev-docs/show-outstream-video-ads.md

Reverts prebid/prebid.github.io#2259

Revert "Update show-outstream-video-ads.md for backupOnly renderers"

---

dev-docs/bidders/bluebillywig.md

Prebid.js PR: https://github.com/prebid/Prebid.js/pull/5584

Blue Billywig bid adapter - add video param to docs

---

dev-docs/integrate-with-the-prebid-analytics-api.md
dev-docs/publisher-api-reference.md

Documentation for https://github.com/prebid/Prebid.js/pull/5563

Document auctionDebug

---

dev-docs/bidders/indexExchange.md

* Update indexExchange.md
* minor spelling fix
* Fixed minor grammatical errors (#2)
* Changed timeout example to 50ms
Co-authored-by: rimaburder-index <55195208+rimaburder-index@users.noreply.github.com>

Update indexExchange.md to include Prebid Server details (#1)

---

dev-docs/bidders/medianet.md

Updating documentation for MediaNet SChain support.

MediaNet SChain Support

---

dev-docs/bidders/pubx.md

add Pub-X dev-docs

---

_data/sidebar.yml
dev-docs/integrate-with-the-prebid-analytics-api.md
dev-docs/modules/index.md
dev-docs/modules/instreamTracking.md
dev-docs/publisher-api-reference.md

Instream Video Ads Tracking docs for https://github.com/prebid/Prebid.js/pull/5481

Added docs for Instream Video Ads Tracking

---

dev-docs/bidders/amx-rtb.md

* TCF2 support added
* COPPA support added
* integration with userIds

Indicate new features in AMX RTB 1.1 Update

---

dev-docs/bidders/gumgum.md

Adds zone, pubId, slot, and native params to the gumgum doc
related prebid.js ticket - https://github.com/prebid/Prebid.js/pull/5728

GumGum: adds new params to gumgum doc

---

dev-docs/bidders/welect.md

Update Docs so we support tcf2 according to them

welect: update docu to tcf2.0

---

dev-docs/bidders/brightroll.md

Updating supported mediatypes to include display also for Brightroll adapter

Update Brightroll adapter details

---

dev-docs/bidders/adformPbjs.md
dev-docs/bidders/adformPbs.md

Separating descriptions about Adform Prebid.js and Adform Prebid Server adapters

Separate Adform adapters descriptions

---

dev-docs/bidders/logicad.md

Updated docs to reflect support for native.

Logicad bidder support for native dev-docs

---

dev-docs/bidders/adagio.md

Update Adagio bidder documentation with support of CCPA/COPPA related to https://github.com/prebid/Prebid.js/pull/5749

Adagio: add support for CCPA/COPPA

---

dev-docs/bidders/sublime.md

This is the follow up PR for our new adapter being released (see: https://github.com/prebid/Prebid.js/pull/5726)

Update Sublime adapter doc for v0.6

---

dev-docs/bidders/brightroll.md

Description:
Updating brightroll prebid adapter documentation

Updated Brightroll adapter documentation

---

dev-docs/bidders/smartyads.md

Here is documentation for SmartyAds adapter

init smartyads docs

---

dev-docs/modules/userId.md
download.md

accompanies https://github.com/prebid/Prebid.js/pull/5802

new userId module - neustar's fabrick

---

dev-docs/modules/userId.md

accidentally deleted my branch and closed the previous PR for this (https://github.com/prebid/prebid.github.io/pull/2348)

update id5 docs with new structure

---

dev-docs/bidders/stroeerCore.md

Prebid.js PR: https://github.com/prebid/Prebid.js/pull/5830

Add stroeerCore bidder documentation (#1)

---

download.md

Related to https://github.com/prebid/Prebid.js/pull/5861

pubprovided filename change

---

dev-docs/bidders/sovrn.md

* tcf 2.0 support noted
* gvlid added
* supported user ID's updated

Sovrn: updated docs

---

download.md
overview/analytics.md

Docs for the new ooloAnalyticsAdapter.
[#5852](https://github.com/prebid/Prebid.js/pull/5852)
Thanks

add oolo analytics adapter docs

---

dev-docs/bidders/medianet.md

Updating the video instream example.

medianet doc update

---

dev-docs/bidders/adoppler.md

Documentation for parameter added in next PR: https://github.com/prebid/prebid-server/pull/1535

Adoppler: Add client parameter documentation.

---

dev-docs/bidders/amx-rtb.md

Prebid server PR: https://github.com/prebid/prebid-server/pull/1549

AMX RTB: indicate prebid server adapter and GVL ID

---

dev-docs/bidders/apacdex.md
dev-docs/bidders/valueimpression.md

Changes:
- Add Apacdex Bid Adapter docs
- The Valueimpression adapter and the Quantumdex adapter have now become the alias of the Apacdex adapter

Add apacdex bid adapter docs & edit valueimpression, quantumdex docs

---

dev-docs/bidders/smaato.md

Doc change for Prebid.JS PR https://github.com/prebid/Prebid.js/pull/5927
Indicating support for criteo, pubCommonId, unifiedId userId and update our status as Prebid member.

Smaato BidAdapter: Add support for userIds

---

dev-docs/bidders/mediasquare.md

update the media types and add the global vendor list id

MediaSquare: updated media_types + add glv_id

---

dev-docs/bidders/indexExchange.md

IX: updated the text in line 309

---

dev-docs/bidders/adagio.md

Related to : https://github.com/prebid/Prebid.js/pull/5938

Adagio: add user id types

---

prebid-mobile/pbm-api/android/pbm-bannerinterstitialadunit-android.md
prebid-mobile/pbm-api/ios/pbm-bannerinterstitialadunit-ios.md

There were some errors and inaccuracies in the existing documentation in the documentation for interstitial ad units.

PBSDK: added clarity on insterstitial ad units

---

dev-docs/modules/userId.md

A related prebid pr https://github.com/prebid/Prebid.js/pull/5859

LiveIntent id module. Add an "emailHash" param

---

dev-docs/bidders/beachfront.md

Adds identityLink to the list of supported userIds

Add identityLink support to Beachfront doc

---

dev-docs/bidders/inmobi.md

Awkwardly updating due to some planned changes that'll have us not support this for a while on our end.

InMobi: updating usp support

---

dev-docs/bidders/MobfoxX.md

Add MobfoxX new gamoshi adapter alias
- contact email of the adapter’s maintainer
official adapter submission

Gamoshi - Add new bid adaptor alias

---

dev-docs/bidders/smartyads.md

Hello! Here is update for SmartyAds prebid.js and prebid server adapter. Currently we have different parameters for integration and we work for unification bidder parameters

update SmartyAds apater docs for prebid.js and prebid-server

---

dev-docs/bidders/criteo.md

Update criteo.md re: floors

---

dev-docs/bidders/pubmatic.md

updated list of PubMatic supported user id modules

updated list of PubMatic supported user id modules

---

dev-docs/bidders/andbeyond.md

Update aliased adaptor information on client request.

Update andbeyond adaptor documentation

---

dev-docs/bidders/mobilefuse.md

Hello,
We've added support for TCF2 and I'm updating accordingly.

Update mobilefuse tcf2 compliance

---

download.md

Adjust Formatting for Proper Row Layout and Headings

Adjust Layout

---

download.md

Improve Formatting

---

dev-docs/bidders/concert.md

Add documentation for concert bid adapter updates.

Update Concert Adapter
