prebid/prebid.github.io

dev-docs/bidders/beachfront.md
Adds documentation for optional banner tagid param.
=> Update tagid param for Beachfront doc

dev-docs/modules/userId.md
Addressing https://github.com/prebid/Prebid.js/issues/6097
=> PubProvided docs fix

dev-docs/bidders/adbite.md
We have created our own bidder file. plz let me know if we need to change anything.
=> created adbite.md

dev-docs/bidders/yieldlab.md
The 'adSize' parameter was changed from 'required' to 'optional'.
=> Yieldlab: Update size handling

dev-docs/modules/userId.md
The changes here are showing how to build the LiveIntentID module in two different ways.
=> Update docs with LiveConnectModes.

download.md
From Issue https://github.com/prebid/prebid.github.io/issues/2563
splitting out the User ID modules on the download page
=> Download page: separating out the user id modules

dev-docs/bidders/indexExchange.md
=> IX PBS: Updated the Supported Media Types table

dev-docs/bidders/temedya.md
https://github.com/prebid/Prebid.js/pull/6168
=> te medya new adaptor

dev-docs/bidders/gothamads.md
Hello! Here is Docs for GothamAds prebid adapter! Please check it!
=> GothamAdsAdapter docs

dev-docs/bidders/adtrue.md, dev-docs/show-prebid-ads-on-amp-pages.md
Add AdTrue bidder dev documentation.
=> New AdTrue bidder

dev-docs/bidders/tappx.md
We received a mail to update our Bidder with this new flag.
Actually we accept apps.
=> TAPPX - pbs_app_supported: true

dev-docs/bidders/tappx.md
Sorry for don't put with the pbs_app_supported change...
=> Tappx - check other features

dev-docs/bidders/sonobi.md
Updated the meta data for the sonobi bidder in dev docs to show that Sonobi supports usp, schain, mobile app, and banner
=> Sonobi - Update Bidder Meta Data Dev Docs

dev-docs/bidders/triplelift.md
Minor revisions to triplelift.md.
=> triplelift: updates dev-docs info

download.md
Adds tapadIdSystem to downloads
=> add tapadIdSystem to downloads

_includes/adops/adops-gam-setup.html, _includes/adops/adops-gam-video-setup.html, adops/gam-native.md, adops/send-all-bids-adops.md, adops/setting-up-prebid-for-amp-in-dfp.md, adops/setting-up-prebid-multi-format-in-dfp.md
At the request of the Tools committee. @asafsham FYI
=> added links to line item tool in GAM AdOps pages

dev-docs/modules/userId.md
a few minor changes to ID5 docs related to eids and a/b testing feature. both of these are already merged in master, this is just correcting the docs.
https://github.com/prebid/Prebid.js/pull/6193
https://github.com/prebid/Prebid.js/pull/6076
=> Id5 update eids and ab testing in docs

dev-docs/modules/userId.md
Update documentation of IDx system id
=> [IDx] update docs

dev-docs/bidders/missena.md
Adding documentation for the Missena bid adapter
=> Add Missena bid adapter

dev-docs/bidders/sharethrough.md
- Related feature PR [here](https://github.com/prebid/Prebid.js/pull/6261)
pubgrowth.engineering@sharethrough.com
=> [Sharethrough] Add support for ID5, Shared ID, and Live Intent ID

dev-docs/bidders/tappx.md
Adding Prebid.js to our dev-doc md file
=> ADD: update tappx pbjs to true

dev-docs/bidders/pangle.md
code PR: https://github.com/prebid/prebid-server/pull/1697
=> pangle bidder: add doc

dev-docs/bidders/epom.md
Epom Adapter:
https://github.com/prebid/prebid-server/pull/1680
=> Epom Adapter Doc

prebid-mobile/pbm-api/ios/code-integration-ios.md
=> upgraded deployment target

dev-docs/modules/userId.md
=> revising britepool marketing

dev-docs/analytics/yuktamedia.md
Resolves the conflict from PR #2736
=> update yuktamedia analytics

dev-docs/analytics/medianet.md, dev-docs/bidders/medianet.md
MediaNet doc update for:
1. Adding MediaNet landing page URL. 
2. Updating example of Instream Video Ad-unit
=> MediaNet analytics and adapter doc updates

dev-docs/bidders/triplelift_native.md
References #2704 
Updates triplelift native info
=> Triplelift: updates triplelift native info

dev-docs/modules/jwplayerRtdProvider.md
Updates documentation for changes introduced in https://github.com/prebid/Prebid.js/pull/6293
Must be merged with https://github.com/prebid/Prebid.js/pull/6302
=> JW Player RTD doc updates for FPD changes

dev-docs/publisher-api-reference.md
further clarification of #1539
=> Clarify when syncDelay is ignored

dev-docs/modules/userId.md
Official documentation updates from the technical writers at Verizon Media.
=> Verizon Media Connect ID documentation update

dev-docs/bidders/amx.md
Document support for schain, added in latest AMX adapter update
=> AMX adapter: adding schain support

dev-docs/show-video-with-a-dfp-video-tag.md, examples/video/instream/akamai/pb-ve-amp.html, prebid-video/video-getting-started.md
Hello, 
I am adding a fix for Akamai AMP player instream sample, along with some other feedback regarding Google's AMP and Akamai AMP product names. 
Any other feedback is welcomed.
=> fix akamai amp player sample, add missing links

dev-docs/analytics/optimon.md
=> adding optimon analytics

dev-docs/bidders/smaato.md
Add pbs_app supported flag
This relates to prebid/prebid-server#1767
=> Smaato: add pbs_app_supported flag

dev-docs/bidders/outbrain.md
Outbrain is now a community member. Changing docs to update
=> outbrain is now a prebid member

dev-docs/bidders/tappx.md
Changes on documentation related to updates on Prebid.js adapter.
Pull request: [https://github.com/prebid/Prebid.js/pull/6504](https://github.com/prebid/Prebid.js/pull/6504)
=> Tappx: update docs. userId added

dev-docs/bidders/logicad.md
Updated docs to reflect support for userids modules.
=> Adding supported userids modules to logicad bid adapter documentation

dev-docs/bidders/between.md
I have added sharedId, gvl_id and usp_supported
=> Between bidder: update dev-doc

dev-docs/bidder-adaptor.md
=> Update bidder-adaptor.md: Remove duplicate item

dev-docs/bidders/kargo.md
Documents https://github.com/prebid/Prebid.js/pull/6447/files
fyi @wedgev
=> Update kargo.md: gdpr support

dev-docs/publisher-api-reference.md
Related to https://github.com/prebid/Prebid.js/pull/6615
=> added maxNestedIframes option

dev-docs/bidders/gnet.md
This docs is reference for PR: https://github.com/prebid/Prebid.js/pull/6536
=> Docs for gnet bidder

dev-docs/bidders/sonobi.md
related js pr -> https://github.com/prebid/Prebid.js/pull/6631
=> Sonobi adapter added support for coppa

dev-docs/bidders/gothamads.md
https://github.com/prebid/Prebid.js/pull/6470
=> Gothamads bid adapter: add ccpa support true flag from pr

features/firstPartyData.md
aligning with changes in https://github.com/prebid/Prebid.js/issues/6057 : change "taxonomyname" to "segtax"
=> FPD: update segments to new segtax format

dev-docs/bidders/viewdeosDX.md
add gvlId
change ViewDeos title in docs
=> Viewdeos doc changes

dev-docs/bidders/converge_digital.md
Documentation for https://github.com/prebid/Prebid.js/pull/6714
=> Documenting converge_digital adaptor alias

dev-docs/bidders/visx.md
Updating docs to reflect latest changes with including video in-stream support.
=> VIS.X: update docs

dev-docs/bidders/adomega.md
Documenting https://github.com/prebid/Prebid.js/pull/6739
=> Documenting adomega adaptor alias

dev-docs/bidders/pangle.md
code PR: https://github.com/prebid/prebid-server/pull/1842
=> pangle bidder: update doc

dev-docs/bidders/medianet.md
Medianet floor module support doc update.
=> Medianet floor module support doc update

dev-docs/bidders/aol.md
documents https://github.com/prebid/Prebid.js/pull/6743
=> Remove AOL floor support

dev-docs/bidders/beachfront.md
Adds schain support to the Beachfront doc.
=> Add schain support to Beachfront doc

dev-docs/bidders/beachfront.md
Adds floors module support to the Beachfront doc.
=> Add floors module support to Beachfront doc

dev-docs/bidders/engageadx.md
Documenting https://github.com/prebid/Prebid.js/pull/6608
=> Documenting engageadx adaptor alias

dev-docs/bidders/pubgenius.md
Flagged in https://github.com/prebid/Prebid.js/issues/6512
Related Prebid.js PR https://github.com/prebid/Prebid.js/pull/6793
=> pubGENIUS bid adapter: update doc to reflect that video params can be read from ad unit

dev-docs/modules/jwplayerRtdProvider.md
Clarifies what JW Player means by Player ID.
=> JW Player RTD Module - Add clarification for Player ID

dev-docs/bidders/ix.md, dev-docs/bidders/roundel.md
Updated documentation for index and roundel to outline coppa support.
Connected Prebid PR: https://github.com/prebid/Prebid.js/pull/6782
=> Index Exchange + Roundel Docs Update: coppa support

dev-docs/modules/userId.md
AdmixeridSystem change syncDelay to auctionDelay
=> AdmixeridSystem change syncDelay to auctionDelay

dev-docs/bidders/yieldmo.md
=> Yieldmo Prebid adapter: read video parameters from the ad unit

dev-docs/denakop.md
Documenting https://github.com/prebid/Prebid.js/pull/6886
=> Documenting denakop alias

dev-docs/bidders/tappx.md
We have updated our dev-doc to correct data that was not correct.
=> tappx - Update adapter docs

download.md
Per https://github.com/prebid/Prebid.js/pull/6521#issuecomment-852106132 adding a checkbox to download the FLoC module. 
Tested locally and confirmed download includes floc module.
=> Add Checkbox in Download Page for FLoC ID System

dev-docs/analytics/id5.md
docs for the ID5 analytics adapter: https://github.com/prebid/Prebid.js/pull/6871
=> Id5 analytics adapter: initial release documentation

dev-docs/bidders/dspx.md
=> Update dspx.md: add list of supported userIds

dev-docs/bidders/invamia.md
Documentation for the Invamia Bidder Adapter.
PR for the adapter changes: prebid/Prebid.js#6941
=> Invamia Bid Adapter: added dev docs for invamia bid adapter

dev-docs/bidders/adkernel.md
Documenting changes from  https://github.com/prebid/Prebid.js/pull/6964
=> Adkernel: documenting userId module support

dev-docs/bidders/adrelevantis.md
Change FPD example for Prebid.js 5
=> Updated FPD example

dev-docs/bidders/amx.md, dev-docs/modules/userId.md
Documentation for a new userId submodule, amxId
- documenting ID & setup on userId.md
- adding support in amx (AMX RTB) bid adapter
- adding example in eids array
=> Adding amxIdSystem documentation (amxId)

dev-docs/bidders/vidazoo.md
We updated the `cId` param example value
=> Vidazoo: Updated `cId` param example

dev-docs/modules/userId.md
Fixes https://github.com/prebid/prebid.github.io/issues/3019 -- also added a couple of other IDs missing and a new column to store the EIDs source.
=> Update User ID table

dev-docs/bidders/growadvertising.md
=> Add GrowAdvertising Bid Adapter docs

dev-docs/bidders/videobyte.md
Video Byte adapter documentation
=> VideoByte adapter docs

features/firstPartyData.md
As driven by discussion in https://github.com/prebid/Prebid.js/issues/6057
- changing segtax 3 to 4 
- changes to description of segtax 1 and 2
=> updated segtax table

dev-docs/bidders/denakop.md
Minor content changes
Moving file to proper location
=> Updating denakop alias documentation

prebid/native-implementation.md
This should fix some broken links in the prebid native documentation.
=> fix some links in the prebid native docs

dev-docs/bidders/vlyby.md
for vlyby bid adapter https://github.com/prebid/Prebid.js/pull/6417
=> initial commit vlyby markdown

dev-docs/bidders/pixfuture.md
The new PixFuture Bidder Adapter
our email: admin@pixfuture.net
=> PixFuture bid adapter

dev-docs/bidders/yieldone.md
YieldOne Bid Adapter: add LiveRampID support.
=> YieldOne Bid Adapter: add LiveRampID support.

dev-docs/bidders/vdoai.md
https://github.com/prebid/Prebid.js/pull/7119
=> vdoai Bid Adapter - Support for Prebid 5.x

dev-docs/bidders/impactify.md
Related to pr https://github.com/prebid/Prebid.js/pull/7113#pullrequestreview-694993443
=> Update docs for Adding Impactify back into Prebid 5.0

dev-docs/bidders/vrtcal.md
Related to pr https://github.com/prebid/Prebid.js/pull/7106
=> Updating Docs for Adding Adapter Back to Prebid 5.0

dev-docs/bidders/pubx.md
Related to pr https://github.com/prebid/Prebid.js/pull/7103
=> Update Docs for Adding Adapter back to Prebid 5.0

dev-docs/publisher-api-reference/getEvents.md
related to https://github.com/prebid/Prebid.js/pull/7059
=> Add adRenderSucceeded to event list

dev-docs/bidders/kubient.md
Added Video support
New PBJS endpoint
Compliant to Prebid v5
=> Kubient adapter. Add video support

dev-docs/modules/userId.md
Incorporating the x1 API doc changes for akamaiDAPIdSystem submodule
=> Updating x1 API documentation in akamaiDAPIdSystem

dev-docs/bidders/growads.md
Add native support in media_types
=> GrowAdvertising: Add native support

dev-docs/bidders/smartico.md
Update with merge https://github.com/prebid/Prebid.js/pull/7115
=> Update Smartico for Prebid 5.0 Compliance

dev-docs/bidders/innity.md
Innity Bid adapter added to Prebid v5 -> https://github.com/prebid/Prebid.js/pull/7168
=> Innity Bid Adapter: update prebid 5.0 compliance

dev-docs/bidders/gamma.md
per pr https://github.com/prebid/Prebid.js/pull/7033
=> Gamma Bid Adapter: update prebid v5 compliance

dev-docs/bidders/microad.md
per pr https://github.com/prebid/Prebid.js/pull/7007
=> Microad Bid Adapter: update prebid 5 compliance

dev-docs/bidders/proxistore.md
per pr https://github.com/prebid/Prebid.js/pull/7136
=> Proxistore Bid Adapter: update prebid 5 compliance

dev-docs/bidders/revcontent.md
per pr https://github.com/prebid/Prebid.js/pull/7093
=> Revcontent Bid Adapter: update prebid 5 compliance

dev-docs/bidders/rise.md
per pr https://github.com/prebid/Prebid.js/pull/7143
=> Rise Bid Adapter: update prebid v5 compliance

dev-docs/bidders/sortable.md
per pr https://github.com/prebid/Prebid.js/pull/7157
=> Sortable Bid Adapter: update prebid 5 compliance

dev-docs/bidders/vidazoo.md
per pr https://github.com/prebid/Prebid.js/pull/7022
=> Vidazoo Bid Adapter: update prebid 5 compliance

dev-docs/bidders/videoreach.md
per pr https://github.com/prebid/Prebid.js/pull/7142
=> Video Reach Bid Adapter: update prebid 5 complianc

dev-docs/bidders/tappx.md
We have updated our doc for removing an obosolete note.
=> Tappx: update doc removing obsolete note

dev-docs/bidders/clickforce.md
per pr https://github.com/prebid/Prebid.js/pull/7193
=> Clickforce Bid Adapter: update prebid 5 compliance

dev-docs/bidders/adhese.md
per pr https://github.com/prebid/Prebid.js/pull/7191
=> Adhese Bid Adapter:update with prebid 5 compliance

dev-docs/bidders/aja.md
per pr https://github.com/prebid/Prebid.js/pull/7190
=> Aja Bid Adapter: update with prebid 5 compliance

dev-docs/bidders/getintent.md
Update documentation, [#7197](https://github.com/prebid/Prebid.js/pull/7197)
=> GetIntent bid adapter: update documentation

dev-docs/bidder-adaptor.md
This documents prebid https://github.com/prebid/Prebid.js/pull/7184
=> Document meta.demandSource

dev-docs/bidders/videoreach.md
Added adapter to v5 with this pr -> https://github.com/prebid/Prebid.js/pull/7142
=> Video Reach Bid Adapter: update with prebid v5 compliance

dev-docs/bidders/mantis.md
Update docs from pr https://github.com/prebid/Prebid.js/pull/7173
=> Mantis Bid Adapter: update Prebid 5 compliance

dev-docs/bidders/adblender.md, dev-docs/bidders/admixer.md, dev-docs/bidders/go2net.md
adblender/go2net is alias.
add description to zone param.
add kvTargeting param.
=> Admixer Bid Adapter add kvTargeting option

dev-docs/bidders/iqm.md
Updated IQM md file with latest video support.
=> updated iqm md file

dev-docs/bidders/limelightDigital.md
from https://docs.prebid.org/download.html page
=> Fix Limelight Digital Bidder Adapter downloading

dev-docs/bidders/beachfront.md
Adds Halo ID to the list of supported userIds
=> Add Halo ID support to Beachfront doc

dev-docs/publisher-api-reference/setConfig.md
Highlighting the issue described in https://github.com/prebid/Prebid.js/issues/7147
We don't plan to fix this 'properly' unless there's significant demand -- that would require a substantial rewrite of ad-server-targeting, which is already one of the most complicated parts of the code.
=> mediatypepricegran updates

dev-docs/bidder-adaptor.md, dev-docs/faq.md
Documentation for https://github.com/prebid/Prebid.js/issues/6440
=> adding AUCTION_PRICE notes

dev-docs/bidders/colossusssp.md
Per pr https://github.com/prebid/Prebid.js/pull/7245
=> ColossusSsp Bid Adapter: update Prebid 5 compliance

dev-docs/bidders/advangelists.md
Per pr https://github.com/prebid/Prebid.js/pull/7226
=> Advangelists: Update Prebid 5 Compliance

dev-docs/bidders/unicorn.md
Per pr https://github.com/prebid/Prebid.js/pull/7241
=> Unicorn Bid Adapter: update Prebid 5 compliance

dev-docs/bidders/tappx.md
We update with the changes of the https://github.com/prebid/prebid-server/pull/1931 pull request.
=> TAPPX - Update tappx.md

dev-docs/bidders/inmobi.md
Accompanying prebid-server PR: https://github.com/prebid/prebid-server/pull/1928
=> InMobi: Update docs for native, schain

dev-docs/bidders/vidoomy.md
Added docs as requested to create a new bidder adapter
=> added vidoomy bidder docs

dev-docs/bidders/adagio.md
See: https://github.com/prebid/prebid-server/pull/1907
=> Adagio Bid Adapter: add Prebid Server Adapter support

dev-docs/bidders/integr8.md
Adapter PR: https://github.com/prebid/Prebid.js/pull/6882
=> Added docs for integr8

dev-docs/bidders/smaato.md
Update documentation for Floor Price Module support
=> Smaato: Update documentation

download.md
=> fix download page

dev-docs/bidders/inmobi.md
Accompanying PR: https://github.com/prebid/prebid-server/pull/1956
=> InMobi: Update docs with usersync info

dev-docs/bidders/cpmstar.md
per pr _> https://github.com/prebid/Prebid.js/pull/7284
=> Cpmstar Bid Adapter: update prebid 5 compliance

dev-docs/bidders/rtbanalytica.md
Documenting https://github.com/prebid/Prebid.js/pull/7281
=> Adkernel: documenting rtbanalytica alias

dev-docs/bidders/smarthub.md
Documentation for new SmartHub adapter
PR with SmartHub adapter: prebid/prebid-server#1932
=> SmartHub docs

dev-docs/bidders/ix.md
Updating documentation from changes made in https://github.com/prebid/Prebid.js/pull/6691
=> IX Bid Adapter: Update ix docs for size validation

dev-docs/modules/bidViewable.md, dev-docs/modules/bidViewableIO.md, dev-docs/modules/index.md
Add's documentation for bidViewabilityIO module
see
https://github.com/prebid/Prebid.js/pull/7151
=> documentation for bidViewabilityIO module

dev-docs/bidders/tappx.md
We have updated the name in our information file to appear in the bidder listing https://docs.prebid.org/dev-docs/bidders.html. Related to issue #3111
=> Tappx :: update name related to issue #3111

dev-docs/bidders/algorix.md
update Algorix Dev-Doc.
prebid_member and other(USP,Schain, coppa) support
=> update algorix dev-doc for prebidmember and other support

dev-docs/bidders/adsyield.md
- alink to Prebid.js PR [#7282](https://github.com/prebid/Prebid.js/pull/7282)
=> Add AdsYield adapter doc

dev-docs/bidders/smartrtb.md
per issue -> https://github.com/prebid/Prebid.js/issues/7318
=> Smartrtb Bid Adapter: update non Prebid 5 Compliance

dev-docs/bidders/adpartner.md
Per pr -> https://github.com/prebid/Prebid.js/pull/7347
=> Ad Partner Bid Adapter: update Prebid 5 Compliance

dev-docs/bidders/iqzone.md
Add doc for new bid adapter IQZone
=> IQZone Bid Adapter Doc

README.md
CF https://github.com/prebid/prebid.github.io/issues/3204
=> [README] Update command to install packages

dev-docs/bidders/bizzclick.md
per pr -> https://github.com/prebid/Prebid.js/pull/7212
issue reference -> https://github.com/prebid/Prebid.js/issues/7388
=> Bizzclick Bid Adapter: update Prebid 5 compliance

dev-docs/bidders/unibots.md
Documenting https://github.com/prebid/Prebid.js/pull/7387
=> Adkernel: documenting unibots alias

dev-docs/bidders/fluct.md
per pr -> https://github.com/prebid/Prebid.js/pull/7353
=> Fluct Bid Adapter: update Prebid 5 compliance

dev-docs/bidders/seedingAlliance.md
per per -> https://github.com/prebid/Prebid.js/pull/7426
=> Seeding Alliance Bid Adapter: update Prebid 5 compliance

guide.md
Summarizing the job of a PR reviewer
=> Update guide for new reviewers

dev-docs/modules/gpt-pre-auction.md
From https://github.com/prebid/prebid.github.io/issues/3201
=> fixed ortb2Imp case

dev-docs/bidders/justpremium.md
per pr https://github.com/prebid/Prebid.js/pull/7506
=> Just Premium Bid Adapter: update schain support

dev-docs/bidders/mytarget.md
Per pr -> https://github.com/prebid/Prebid.js/pull/7397
=> Mytarget Bid Adapter: update Prebid 5 compliance

dev-docs/bidders/kargo.md
Added video to the list of supported mediaTypes
=> Kargo Adapter: Add video mediaType

dev-docs/bidders/impactify.md
Add the prebid server support
Related PR : https://github.com/prebid/prebid-server/pull/2004
=> Impactify - Prebid Server Support

dev-docs/modules/weboramaRtdProvider.md
I forget to update this file, sorry
=> fix weborama conf example as in Prebid.js/modules/weboramaRtdProvider.md

dev-docs/bidders/adgeneration.md
per pr -> https://github.com/prebid/Prebid.js/pull/7150
(reference pr https://github.com/prebid/Prebid.js/pull/7533 as well)
=> Ad Generation Bid Adapter: update prebid 5 compliance

dev-docs/bidders/engageya.md
Per pr -> https://github.com/prebid/Prebid.js/pull/7579
=> Engageya Bid Adapter: update Prebid 5 compliance

dev-docs/bidders/algorix.md
Add Algorix PlacementId Support
add placementId and appId
replace imp.tagid to placementId
the PBS PR is: 
* https://github.com/prebid/prebid-server/pull/2035
* https://github.com/prebid/prebid-server-java/pull/1525
=> Algorix: add placementId Support

dev-docs/modules/userId.md
updated a few notes on the ID5 ID.
some other spacing issues throughout that my IDE did
=> remove reference to release notes page and some documentation links

dev-docs/bidders/yahoossp.md
Adding a link to the JS adapter .md file to see how to setup all features.
=> Adding reference to prebid.js adapter .md file

dev-docs/bidders/saambaa.md
per pr https://github.com/prebid/Prebid.js/pull/7448
=> Saamba Bid Adapter: update Prebid 5 compliance

dev-docs/bidders/openx.md
These are going to be added in https://github.com/prebid/Prebid.js/pull/7642
=> OpenX update supported userIds

dev-docs/bidders/admixer.md, dev-docs/modules/userId.md
* add user ids: AdmixerId
* set prebid_member: true
* change params.pid to Optional
=> Admixer: bid adapter and id system docs update

dev-docs/bidders/iprom.md
per pr -> https://github.com/prebid/Prebid.js/pull/7700
*added to version note since this adapter is not in 5.x but in 6.2
=> iProm Bid Adapter: update versions included

dev-docs/bidders/beachfront.md
Adds first-party data support to the Beachfront doc.
=> Add first-party data support to Beachfront doc

dev-docs/bidders/admixer.md
- A link to a PR on the Prebid.js repo [#7717](https://github.com/prebid/Prebid.js/pull/7717)
=> AdmixerBidAdapter: add native support

dev-docs/bidders/missena.md
per pr -> https://github.com/prebid/Prebid.js/pull/7648
=> Missena Bid Adapter: update with prebid compliance

dev-docs/modules/intersectionRtdProvider.md
* A link to a PR on the Prebid.js repo [#7710](https://github.com/prebid/Prebid.js/pull/7710)
=> Add Intersection RTD Provider docs

dev-docs/bidders/luponmedia.md
per pr -> https://github.com/prebid/Prebid.js/pull/7458
=> Lupon Media Bid Adapter: update prebid 5 complianc

dev-docs/modules/userId.md
Documents https://github.com/prebid/Prebid.js/pull/6448
=> Document setting ppid from the userid module

dev-docs/add-rtd-submodule.md
Document new RTD submodule event handler: `onBidRequest`
Code changes: https://github.com/prebid/Prebid.js/pull/7729
Related issue: https://github.com/prebid/Prebid.js/issues/7078
=> RTD: Add 'onBidRequest' event handler for RTD submodules

dev-docs/bidders/sharethrough.md
Update Sharethrough documentation to include video media type, floors true, and safeframes true.
=> Update  Sharethrough documentation to include video media type, floors, and safeframes

dev-docs/bidders/ozone.md
Documenting added support for additional features (schain, coppa, floor prices, etc.).
=> ozone 2.7.0 doc updates

dev-docs/bidders/videobyte.md
Linked to https://github.com/prebid/prebid-server/pull/2058
=> VideoByte update docs

dev-docs/publisher-api-reference/setConfig.md
Documentation changes related to https://github.com/prebid/Prebid.js/pull/7690: a new config option `targetingControls.addTargetingKeys`
=> Add targetingControls.addTargetingKeys configuration option

dev-docs/bidders/coinzilla.md
=> Update Coinzilla for Prebid-Server support

dev-docs/bidders/etarget.md, prebid-mobile/pbm-api/ios/pbm-banneradunit-ios.md
As pointed out https://github.com/prebid/prebid.github.io/issues/3457, fixed the iOS SDK doc.
Also found that the etarget adapter file was busted, fixed that.
=> SDK doc fix

dev-docs/modules/userId.md
Minor, but important, fix as noted in https://github.com/prebid/prebid.github.io/issues/3321
=> sharedId doc fix

dev-docs/bidders/smaato.md
FPD section is updated for Smaato
=> PREB-31: [Docs] Update Smaato FPD section

dev-docs/bidders/adagio.md
- Remove `pbs` flag as we dropt our adapter (https://github.com/prebid/prebid-server/pull/2117)
- Change the `fpd_supported` flag to `false` (https://github.com/prebid/prebid.github.io/issues/3444).
- Update install guide url
=> Adagio updates

dev-docs/publisher-api-reference/getEvents.md
Prebid changes: https://github.com/prebid/Prebid.js/pull/7917
Also see discussion in https://github.com/prebid/Prebid.js/issues/7702#issuecomment-1006875215
=> Update docs for getEvents#adRenderSucceeded

_data/sidebar.yml, adops/before-you-start.md, dev-docs/publisher-api-reference/setConfig.md, features/adServerKvps.md
Fixed version of #3448 with the right set of files.
=> PBJS key value pairs

dev-docs/modules/gpt-pre-auction.md
Docs for code PR https://github.com/prebid/Prebid.js/pull/7784 and issue https://github.com/prebid/Prebid.js/issues/7367
=> GPT Pre-Auction updates

features/firstPartyData.md
per https://github.com/prebid/prebid.github.io/issues/3516
=> update FPD example for extended content ID

overview/prebid-universal-creative.md
As discussed in today's Prebid.js committee meeting
=> expanding PUC documentation

dev-docs/bidders/improvedigital.md
Code PR: https://github.com/prebid/Prebid.js/pull/7948
=> Improve Digital adapter COPPA support

prebid-server/developers/add-a-module-java.md
I encountered some problems when developing the first prebid-server module for our company.
I added some more documentation, which in my opinion was missing before.
=> Documentation improvements for prebid-server-java modules

dev-docs/modules/hadronRtdProvider.md, dev-docs/modules/haloRtdProvider.md
@bretg Small  update PR to add link instead of raw url to Halo rename & fix Audigent link.
=> Update Hadron links

dev-docs/bidder-adaptor.md
Updating the bid adapter developer docs based on the gap discussed in https://github.com/prebid/Prebid.js/issues/7977 
- added gvlid references
- noticed supportedMediaTypes was inconsistent, so fixed that
- other minor fixes
=> bid adapter developer updates

dev-docs/publisher-api-reference/setConfig.md
Related PBJS changes: https://github.com/prebid/Prebid.js/pull/7885
=> Document `s2sConfig.allowUnknownBidderCodes`

dev-docs/modules/weboramaRtdProvider.md
to reflect latest version
https://github.com/prebid/Prebid.js/pull/7912
=> update weborama RTD submodule doc for v 6.9.0

dev-docs/bidders/yieldone.md
fixing conflict in https://github.com/prebid/prebid.github.io/pull/3535
=> Adding ymuid to yieldone.md

dev-docs/bidders/adplus.md
Changed the contact email address for AdPlus bid adapter.
=> AdPlus contact email updated

dev-docs/bidders/kubient.md
Related PR https://github.com/prebid/Prebid.js/pull/7855
=> Kubient COPPA support

prebid-server/developers/add-new-bidder-go.md
Per https://github.com/prebid/prebid-server/issues/2157
=> Document seatbid.bid.ext.prebid.meta.demandsource

dev-docs/bidders/ttd.md
Bidder PR: https://github.com/prebid/Prebid.js/pull/8073
=> Add TTD bidder dev documentation

dev-docs/add-rtd-submodule.md
fixed old FPD references in the RTD module doc
=> RTC module: fixed fpd references

prebid-server/features/pbs-fpd.md
Adding keywords rows to PBS FPD table
=> PBS FPD - added keywords

dev-docs/integrate-with-the-prebid-analytics-api.md
Clarification related to https://github.com/prebid/prebid.github.io/issues/3587
=> analytics: added TCF note

dev-docs/bidders/gmossp.md
Related feature PR https://github.com/prebid/Prebid.js/pull/8128
=> GMOSSP Bid Adapter:Add user id module.

dev-docs/modules/userId.md
Adjust the email address for users to contact Lotame.
------
=> Lotame doc updates

prebid-video/video-overview.md
Clarifications from https://github.com/prebid/prebid.github.io/issues/3612
=> video overview: outstream and caching

dev-docs/bidders/sharethrough.md
Coming with prebid/prebid-server#2166 on Prebid Server Side, and following changes already released on the Prebid.js side, we're updating our adapter doc.
=> Sharethrough: Clean up deprecated params and refresh supported userIds

dev-docs/modules/userId.md
changing more pubcommon references to sharedid
=> user ID: changing more pubcommon references to sharedid

prebid-server/developers/add-new-bidder-java.md
=> Updated PBS config, added viewability-vendors description

dev-docs/bidders/adrelevantis.md
=> Changed first party data

dev-docs/bidders/sovrn.md
=> SOVRN: Updated some parameters to recommended

dev-docs/modules/sizeMappingV2.md
Adding a note about a scenario not supported by Prebid Server
=> AdvSizeMapping: add PBS note

dev-docs/bidders/ottadvisors.md
New alias for Aniview prebid adapter
https://github.com/prebid/Prebid.js/pull/8125
=> New alias for Aniview prebid adapter: ottadvisors

dev-docs/bidders/slimcut.md
- https://github.com/prebid/Prebid.js/pull/8186
-
=> Slimcut Bid Adapter: Add Magnite gvlid 52

prebid-server/features/pbs-storedreqs-java.md, prebid-server/features/pbs-storedreqs.md
=> Add PBS-Java stored requests documentation

dev-docs/modules/floors.md
=> floors: added pubmatic

dev-docs/modules/userId.md
=> user ID: fixing getUserIdsAsEids links

dev-docs/bidders/adgeneration.md
- https://github.com/prebid/Prebid.js/pull/8178
=> update AdGeneration Doc: add novatiq

features/firstPartyData.md
Segtax 4 is an audience tax
https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/extensions/community_extensions/segtax.md
=> Update firstPartyData.md example

dev-docs/bidders/conversant.md
Add supply chain support for the Conversant adapter.
Related prebid.js PR is here https://github.com/prebid/Prebid.js/pull/8203
- [ X] new feature
=> Conversant adapter now supports the supply chain module

dev-docs/bidders/nextMillennium.md
=> Updated list of parameters for nextMillennium

dev-docs/bidders/readpeak.md
=> Add banner support

dev-docs/bidders/open8.md
Adding back adapter to pbjs and enabling download along with updating version notes.
PBjs pr -> https://github.com/prebid/Prebid.js/pull/8127
- [X ] update bid adapter
=> Open8 Bid Adapter: update docs for added back adapter

dev-docs/modules/userId.md, download.md
=> Adding ftrack to the Prebid website

download.md
Make it available on download page for `im-uid UserId Module` that have already been released.
https://github.com/prebid/Prebid.js/blob/master/modules/imuIdSystem.js
https://github.com/prebid/Prebid.js/pull/7239
=> add imuid userId Module download

dev-docs/bidders/yahoossp.md
=> YahooSSP added video support.

dev-docs/bidders/admaru.md
=> Admaru Adapter: add dev docs for admaru adapter

dev-docs/modules/prebidServer.md
added TOC, changed heading levels
=> prebidServer module updates

dev-docs/bidders/pulsepoint.md
pulsepoint bidder update related to [Prebid.js](https://github.com/prebid/Prebid.js/pull/8215)
=> Updating pulsepoint config related to userIds support

dev-docs/bidders/audiencerun.md
AudienceRun adapter doc update.
**Related Prebid.js PR** 
- https://github.com/prebid/Prebid.js/pull/8261
=> docs: update AudienceRun adapter doc

dev-docs/bidders/nexx360.md
=> Nexx360 - Video added to nexx360 bid adapter

dev-docs/modules/userId.md
=> prebid 7: Remove useridtargeting

dev-docs/bidders/pgam.md
Doc for: 
https://github.com/prebid/prebid-server/pull/2198
=> add PGAM doc

dev-docs/modules/userId.md
Updated Yahoo Brand from VerizonMedia
Updated old brand of Verizon Media to Yahoo.  @slimkrazy please review
=> Yahoo Branding

dev-docs/bidders/smarthub.md
=> Fix SmartHub documentation

dev-docs/bidders/pubmatic.md
- [N/A] Related pull requests in prebid.js or server are linked
- [N/A] For new adapters check [submitting your adapter docs](https://docs.prebid.org/dev-docs/bidder-adaptor.html#submitting-your-adapter)
Remove outdated information that applied to Prebid.js 2.x and earlier
=> Remove outdated information for PubMatic bidder

dev-docs/bidders/outbrain.md
prebid.js: https://github.com/prebid/Prebid.js/pull/8223
=> Outbrain adapter: support floor module

dev-docs/modules/consentManagementUsp.md
Timeout and behavior seemed wrong, potentially copied from GDPR.
=> USP API Doc was wrong

dev-docs/modules/userId.md
Update https://docs.prebid.org/dev-docs/modules/userId.html#fabrick-id-by-neustar section, add new parameters. 
- [ x] text edit only (wording, typos)
=> add parameters in Fabrick ID by Neustar section.

dev-docs/bidders/glimpse.md
- Add usp support
- Remove demand and keywords bidder params
- Update example on setting up adapter with first party data
- Rename placementId to pid
- Update fpd section description
- remove user.ext.keywords from example
- update contact email address
- (reverted) https://github.com/prebid/Prebid.js/pull/8237
- new PR: https://github.com/prebid/Prebid.js/pull/8260
=> Glimpse: add usp support, update params and fpd setup

dev-docs/bidders/outbrain.md
- [ x ] text edit only (wording, typos)
=> Outbrain: Added multiformat support flag

dev-docs/analytics/ats.md, dev-docs/modules/userId.md
Add storage.refreshInSeconds to example implementations and provide more context on available params.
=> Update documentation for RampID module

prebid-server/developers/add-new-bidder-go.md
=> Remove Reference Supporting Dynamic Domains

dev-docs/bidders/janet.md
=> Fix janet server flag

prebid-server/developers/add-new-bidder-java.md
=> PBJ: Add IPF feature to bid adapter

dev-docs/bidders/cwire.md
Fix for https://github.com/prebid/prebid.github.io/issues/3673 and https://github.com/prebid/Prebid.js/issues/8331
It had an extra blank line at the start.
=> fixed cwire md file

prebid-server/features/pbs-native.md
Apparently PBS has supported this for a long time, but it was never documented.
=> PBS native - adding asset.id

dev-docs/bidders/loglylift.md
=> Loglylift Bid Adapter: add support for banners

dev-docs/analytics/ats.md
=> Show ATS Analytics on download page

dev-docs/bidders/insticator.md
Added yob, gender, instl and pos to Bid Params
=> feat: updated insticator.md

dev-docs/analytics/malltv.md
=> MallTv Analytics Adapter: fix adapter code

dev-docs/bidders/mediasniper.md
=> Mediasniper bid adapter

dev-docs/bidders/criteo.md
This relates to the change requested in https://github.com/prebid/prebid.github.io/issues/3444
=> Criteo: Updated document regarding first party data support

dev-docs/faq.md
Placeholder info about the GAM Yield Group feature until we can get a standalone page set up.
=> Initial GAM Yield Group FAQ

dev-docs/analytics/ats.md
=> Fix incorrect module code

dev-docs/faq.md
Also a couple of tweaks to the yield-group FAQ
=> added renaming FAQ entry

dev-docs/modules/airgridRtdProvider.md
=> chore: update AirGrid docs, typos and link fixes

dev-docs/bidders/ix.md
=> Updated the TTL for banner and video bids

download.md
=> Update naming of RampID user id module

dev-docs/analytics/audigent.md, dev-docs/analytics/hadron.md
=> Hadron analytics adapter

dev-docs/bidders/adf.md
=> Adf adapter: coppa signal and multiformat support

dev-docs/modules/userId.md, download.md
- new ID system submodule
[https://github.com/prebid/Prebid.js/pull/8364](https://github.com/prebid/Prebid.js/pull/8364)
=> Add CPEx ID

dev-docs/bidders/improvedigital.md
Code PR: https://github.com/prebid/Prebid.js/pull/8399
=> Improve Digital adapter: Extend mode

dev-docs/analytics/bidwatch.md
- [x ] new analytic adapter
- [ x] Related pull requests in prebid.js or server are linked
- [x ] For new adapters check [submitting your adapter docs](https://docs.prebid.org/dev-docs/bidder-adaptor.html#submitting-your-adapter)
Prebid.js pull request: https://github.com/prebid/Prebid.js/pull/8302
=> Add BidWatch Analytics Adapter

prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md
added a new deals targeting option and revised the bid caching section
=> PBS auction doc updates

dev-docs/modules/userId.md
Add comma to code examples for RampID
=> Add comma to code examples for RampID

dev-docs/bidders/automatad.md
* Modified the automatad's bidder docs to support prebid server documentation.
=> Automatad adapter documentation update

dev-docs/modules/userId.md
=> Rename id to AudienceOne ID from DAC ID

dev-docs/bidders/adyoulike.md
new feature
Add schain support on adyoulikebidder adapter
https://github.com/prebid/Prebid.js/pull/8486
=> AdYouLike BidderAdapter schain support

dev-docs/bidders/groupm.md, dev-docs/bidders/ix.md
=> Updated docs for Kobler adapter

dev-docs/modules/userId.md
This change includes the cleanup of documentation for AkamaiDAPId module. It is replaced by akamai RTD module.
prebid.js pull request: 
https://github.com/prebid/Prebid.js/pull/8480
=> Removed akamaiUserID documentation

dev-docs/modules/userId.md
Updated example for MerkleIdSystem
https://github.com/prebid/Prebid.js/pull/8499
=> Updated merkleId parameters

dev-docs/bidders/incrementx.md
As noted in https://github.com/prebid/prebid.github.io/pull/3725
=> fixing bidder code for incrementx

dev-docs/bidders/pubmatic.md
Added FPD Support details in the documentation as per [suggestion](https://github.com/prebid/prebid.github.io/issues/3444)
=> PubMatic : FPD Support documentation

dev-docs/bidders/adf.md, dev-docs/bidders/admixer.md, dev-docs/bidders/adnuntius.md, dev-docs/bidders/beachfront.md, dev-docs/bidders/beop.md, dev-docs/bidders/colossusssp.md, dev-docs/bidders/datablocks.md, dev-docs/bidders/futureads.md, dev-docs/bidders/gumgum.md, dev-docs/bidders/inmar.md, dev-docs/bidders/livewrapped.md, dev-docs/bidders/medianet.md, dev-docs/bidders/nobid.md, dev-docs/bidders/optout.md, dev-docs/bidders/ozone.md, dev-docs/bidders/pixfuture.md, dev-docs/bidders/proxistore.md, dev-docs/bidders/rise.md, dev-docs/bidders/sharethrough.md, dev-docs/bidders/sonobi.md, dev-docs/bidders/sovrn.md, dev-docs/bidders/sspBC.md, dev-docs/bidders/trustx.md, dev-docs/bidders/winr.md, dev-docs/bidders/yieldmo.md, dev-docs/bidders/zeta_global_ssp.md
Finally  enforcing issue #3444 by removing the fpd_supported flag from 26 adapter md files.
=> removing FPD support flag

dev-docs/bidders/openx.md, dev-docs/bidders/synacormedia.md, dev-docs/modules/userId.md, download.md
- https://github.com/prebid/Prebid.js/pull/8150
=> NextRoll ID: Remove NextRoll ID module docs

dev-docs/publisher-api-reference/bidderSettings.md
documents https://github.com/prebid/Prebid.js/pull/8279
=> Change storagemanager default access

dev-docs/bidders/districtm.md, dev-docs/bidders/districtmdmx.md, dev-docs/bidders/dmx.md
replaces https://github.com/prebid/prebid.github.io/pull/3776 and https://github.com/prebid/prebid.github.io/pull/3786
=> districtm version notes

dev-docs/bidders/aduptech.md
=> AdUp Technology Adapter update docs

dev-docs/bidders/ix.md
Documentation update for floating player support for IX outstream player. 
PBJS PR: https://github.com/prebid/Prebid.js/pull/8528
=> IX Bid Adapter: Outstream Floating Support

dev-docs/faq.md
Clarifying line item behavior as reported by @patmmccann
=> updating hbyg faq entry

dev-docs/bidders/kueez.md
=> add kueez adapter docs

dev-docs/bidders/yieldone.md
=> Add AudienceOne ID and modify name to YieldOne from YIELDONE in yieldone.md

dev-docs/bidders/zeta_global_ssp.md
=> ZetaSspBidAdapter docs: Add contacts

dev-docs/bidders/finative.md
=> add finative Adapter

dev-docs/bidders/gumgum.md
Updated docs for new skin product
https://github.com/prebid/Prebid.js/pull/8552
=> Update gumgum prebid docs

dev-docs/bidders/idx-bidder-code.md, dev-docs/bidders/idx.md
=> idx bidder adapter docs

dev-docs/bidders/dianomi.md
=> Dianomi bid adapter: new bid adapter

dev-docs/bidders/lasso.md
Prebid Server pull request link: https://github.com/prebid/Prebid.js/pull/8503
=> Lasso bid adapter

dev-docs/bidders/shinez.md
- [Shinez Adapter RP](https://github.com/prebid/Prebid.js/pull/8494)
=> New doc for Shinez Prebid adapter

dev-docs/bidders/openx.md
updating openx docs with information about a new adapter option and updating video support.
https://github.com/prebid/Prebid.js/pull/8409
=> OpenX Bid Adapter: update docs with video changes and adapter specifics

prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md
Added replaceimpid per issue https://github.com/prebid/prebid-server/issues/2210
=> PBS storedbidresponse update

dev-docs/bidders/ix.md
Updated user sync content to include iframe and img based syncing support
=> Updated user sync content

dev-docs/bidders/vrtcal.md
=> Updated VRTCAL support flags

dev-docs/bidders/ras.md
=> Add ras bid adapter docs

prebid-server/developers/add-new-bidder-go.md, prebid-server/developers/add-new-bidder-java.md
Related to https://github.com/prebid/prebid-server/issues/2307, adding 'tid' to the list of reserved words
=> PBS: updating list of reserved words that cannot be bidder names

dev-docs/bidders/selectmedia.md
https://github.com/prebid/Prebid.js/pull/8684
=> update SelectMedia gvlid

dev-docs/modules/1plusXRtdProvider.md
Docs for 1plusX RTD submodule
Reflects changes introduced by prebid/Prebid.js#8614
=> 1plusX RTD submodule docs

dev-docs/bidders/sonic_twist.md
=> Adkernel: updating andbeyond alias

dev-docs/analytics/audigent.md, dev-docs/modules/hadronRtdProvider.md, dev-docs/modules/userId.md
https://github.com/prebid/Prebid.js/pull/8636
=> adding partnerId and changing publisherId by partnerId

dev-docs/bidders/seedtag.md
Update Seedtag bidder doc to add USP/CCPA compliance
https://github.com/prebid/Prebid.js/pull/8602
=> Seedtag - update bidder doc for usp/ccpa compliance

dev-docs/bidders/consumable.md
=> Add User IDs and USP/CCPA Support to Consumable Bid Adapter

dev-docs/bidders/pubmatic.md
=> PubMatic: add ORTB blocking & multi-bid info

dev-docs/bidders/nextMillennium.md
missing the required/optional field. Talked to NextMillennium.
=> nextMillennium: adding scope flag

dev-docs/bidders/bucksense.md
=> Update bucksense.md added gdpr_supported: true

dev-docs/bidders/yieldone.md
=> add ID5 support

dev-docs/bidders/consumable.md
=> add schain and coppa to Consumable docs

dev-docs/bidders/prisma.md
=> Prisma Bid Adapter: add new bid adapter

dev-docs/bidders/onetag.md
=> Add support for price floors and schain in onetag.md

dev-docs/modules/1plusXRtdProvider.md
Update wording in 1plusX RTD documentation
=> Update doc for 1plusX RTD Provider

dev-docs/modules/gdprEnforcement.md
As discussed in https://github.com/prebid/prebid.github.io/issues/3860#issuecomment-1191950296
=> gdpr enforcement module: removed gvlid module list

dev-docs/bidders/videonow.md
Prebid.js PR: https://github.com/prebid/Prebid.js/pull/8669
=> videonow bidder adapter docs update

dev-docs/bidders/stroeerCore.md
=> StroeerCore Bid Adapter: add schain support

dev-docs/modules/userId.md
Adding some more information about how to customize the EID response for pbjs.getUserIdsAsEids() and mentioning its a good idea to add tests for the pbjs get id methods
=> User Id Module - EID directions

dev-docs/bidders/gumgum.md
https://github.com/prebid/Prebid.js/pull/8742
=> Gumgum Bid Adapter: Updated document to include s2s example for skins

dev-docs/bidders/unicorn.md
https://github.com/prebid/prebid-server/pull/2297
=> UNICORN: update bidder params

dev-docs/bidders/blue.md
This pull request refers to the creation of documentation for a new adapter from the Blue company. We'll launch a pull request from the adapter next.
=> Blue adapter creation

dev-docs/bidders/c1x.md
please find the PR raised in the prebid.js repo below
https://github.com/prebid/Prebid.js/pull/8706
=> updated bid adapter markdown file changes

dev-docs/bidders/oftmedia_server.md
=> OFT media Server doc

dev-docs/bidders/adrino.md
Prebid Server PR: https://github.com/prebid/prebid-server/pull/2329
=> Adrino Adapter: prebid server enabled

dev-docs/bidders/sharethrough.md
Related PR: prebid/Prebid.js#8808
=> Sharethrough: Improve Doc for First Party Data and ORTB Blocking

dev-docs/bidders/invibes.md
=> Update invibes meta data

dev-docs/bidders/smartyads.md
- https://github.com/prebid/Prebid.js/pull/7380
cc: @SmartyAdsSSP please check if this is correct. I deducted the meta data from your prebid-server-java and prebid.js implementation.
=> Update smartyads meta data

dev-docs/bidders/displayioads.md
Documenting https://github.com/prebid/Prebid.js/pull/8803
=> Adkernel: Documenting displayioads

dev-docs/bidders/ozone.md
Added video support and test params.
https://github.com/prebid/Prebid.js/pull/8755
=> Ozone MD File Updates

dev-docs/bidders/consumable.md
=> add video support to Consumable docs

dev-docs/bidders/criteo.md
- [ x] new feature
- [ x] Related pull requests in prebid.js or server are linked
- [ x] For new adapters check [submitting your adapter docs](https://docs.prebid.org/dev-docs/bidder-adaptor.html#submitting-your-adapter)
=> Criteo - Add coppa support (#8781)

dev-docs/bidders/datawrkz.md
=> New Bid Adapter Dev Docs: datawrkz

dev-docs/bidders/andBeyondMedia.md
=> AndBeyondMedia Bid Adapter: add new bid adapter

dev-docs/modules/userId.md
PR for https://github.com/prebid/Prebid.js/pull/8784, adding a new config parameter for ID5
[x] User ID module update
=> ID5 User Id Module, add new config parameter

dev-docs/bidders/mediago.md
=> mediago bid adapter doc

dev-docs/faq.md
=> Fix global link in  faq.md

dev-docs/modules/viewability.md
=> Security disclaimer on viewability.md

dev-docs/bidders/inmar.md
=> inmar: add deprecation warning

dev-docs/publisher-api-reference/bidderSettings.md
Fix #3990
In addition to this fix, would it be interesting to add a new flag `requireStorage` in [_bidAdapter_].md metadata ?
=> Update bidderSettings `storageAllowed`

dev-docs/bidders/rubicon.md
=> Rubicon: Native support

dev-docs/bidders/seedtag.md
Remove the video instream documentation from the bidder doc
https://github.com/prebid/Prebid.js/pull/8921
=> Seedtag bid Adapter - update documentation

dev-docs/bidders/xe.md
=> xeworks bid adapter docs

dev-docs/bidders/consumable.md
=> add price floor support to Consumable docs

dev-docs/bidders/adkernel.md
floors_supported - https://github.com/prebid/Prebid.js/pull/6671
fpd_supported -  https://github.com/prebid/Prebid.js/pull/7684 + https://github.com/prebid/Prebid.js/pull/8880
ortb_blocking_supported - https://github.com/prebid/Prebid.js/pull/7684
=> Adkernel: updating bidder capabilities

dev-docs/bidders/outbrain.md, dev-docs/bidders/outbrain_old.md
PR: https://github.com/prebid/Prebid.js/pull/8888
=> Outbrain adapter: add docs for wlang

dev-docs/bidders/ocm.md, dev-docs/bidders/vidcrunchllc.md
https://github.com/prebid/Prebid.js/pull/8872
=> VidCrunch LLC doc 

dev-docs/bidders/acuityads.md
=> AcuityAds Bid Adapter: new adapter

dev-docs/bidders/displayio.md
=> Custom renderer URL is added to bid parameters

dev-docs/bidders/ocm.md
Added gvlid   to bidder
https://github.com/prebid/Prebid.js/pull/8961
=> Add OCM gvlID

dev-docs/modules/userId.md
=> Update rampid text

prebid-server/developers/add-new-bidder-go.md
=> PBS-Go GZIP Documentation

dev-docs/examples/postbid.md
related to https://github.com/prebid/Prebid.js/issues/8983
=> postbid: adding note about size support

dev-docs/bidders/stroeerCore.md
=> StroeerCore Bid Adapter: add video support

dev-docs/bidders/teads.md
Update the list of user Ids supported in the Teads Adapter
- [x ] update bid adapter
PR of the update of Teads Adapter :
https://github.com/prebid/Prebid.js/pull/8951
=> Update Teads bid adapter documentation : add new userIds

dev-docs/bidders/orbidder.md
Orbidder supports floor price module, update the docs accordingly.
=> add `floors_supported: true` to orbidder doc

formats/video.md, prebid-video/video-overview.md
The CTV-OTT committee has asked that we post their white paper on the site... refactored the video resource page to include a link.
Note, I also removed the list of adapters that support video. It's so long as to be pretty useless, and the same info can be obtained from multiple other places.
=> CTV-OTT white paper

dev-docs/bidders/caroda.md
=> Caroda: Prebid initial adapter release documentation

dev-docs/bidders/nextMillennium.md
https://github.com/prebid/Prebid.js/pull/8740
=> added video as supported media type

dev-docs/bidders/yieldlab.md
=> Yieldlab remove unsupported adSize bid parameter

prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md
Related to https://github.com/prebid/Prebid.js/issues/9024
=> added adunitcode to PBS extension list

dev-docs/bidders/appnexus.md
@jsnellbaker requested to add this note to the appnexus PBJS adapter
=> appnexus version note

dev-docs/bidders/adagio.md
=> Adagio: update FPD note

dev-docs/modules/userId.md
- [x ] new feature
https://github.com/prebid/Prebid.js/pull/9011
=> Update to prebid website for the new GrowthCode UserID Module

dev-docs/modules/userId.md
=> Updated ConnectID documentation to account for the Easy Opt-out 

dev-docs/bidders/vuukle.md
=> Vuukle Bid Adapter: support gdpr/usp/coppa/schain/gvlid

dev-docs/modules/oneKeyRtdProvider.md, dev-docs/modules/userId.md
User Id sub-module: https://github.com/prebid/Prebid.js/pull/8685
RTD module: https://github.com/prebid/Prebid.js/pull/8686
=> OneKey RTD Module & OneKey Id Submodule: initial release

dev-docs/modules/userId.md, download.md
**/!\ Do not review for now as the module is not released yet**
https://github.com/prebid/Prebid.js/pull/9048
=> OMNS: Update documentation for the new Teads User Id Module

dev-docs/bidders/ogury.md
=> updating Ogury Bidder documentation

dev-docs/bidders/vrtcal.md
=> Added support for 3rd party user IDs

dev-docs/publisher-api-reference/getEvents.md
List new `bidRejected` event: https://github.com/prebid/Prebid.js/pull/9013
=> PBJS: Document new `bidRejected` event

dev-docs/modules/userId.md
Making value easier to find by adding discussion in userid md
=> Add some commentary on using value in userid markdown

dev-docs/bidders/ix.md
=> ix PBJS/PBS file split - client-side

dev-docs/modules/iasRtdProvider.md
Related pull requests in prebid.js:
- https://github.com/prebid/Prebid.js/pull/9058
- https://github.com/prebid/Prebid.js/pull/8994
- https://github.com/prebid/Prebid.js/pull/8214
=> Ias rtd module optional parameters

dev-docs/bidders/bidstack.md
Related adapter PR: https://github.com/prebid/prebid-server/pull/2416
=> Bidstack adapter documentation

dev-docs/bidders/aax.md
=> MediaNet Adapter: Changed AAX client docs flag

dev-docs/bidders/smaato.md
=> Smaato: Adding native ads to docs

dev-docs/modules/weboramaRtdProvider.md
add new option on contextual contiguration to use an asset id.
code PR https://github.com/prebid/Prebid.js/pull/9086
=> update weborama RTD module documentation with new option asset id on contextual

dev-docs/analytics/magnite.md
Prebid.js PR: https://github.com/prebid/Prebid.js/pull/9068
=> Magnite Analytics Adapter

dev-docs/bidders/teads.md, download.md
=> teads adapter: Create note to avoid 7.20.0 and 7.21.0 when downloading Prebid.js

_data/sidebar.yml, dev-docs/examples/sync-tid.md
An example on how to call another library and Prebid aiming to sync imp.ext.tid
=> New Example: Sync imp.ext.tid with 'anotherLibrary'

dev-docs/bidders/ix.md
Formatting updates, no change to content.
=> Updated the step numbers in ix.md.

dev-docs/modules/oxxionRtdProvide.md
Prebid.js pull request: https://github.com/prebid/Prebid.js/pull/9102
=> Add Oxxion Rtd Provider

dev-docs/publisher-api-reference/requestBids.md
https://github.com/prebid/Prebid.js/pull/9106 introduces a way to use `requestBids` as a promise.
=> PBJS: document new return value from `requestBids`

dev-docs/modules/consentManagementUsp.md
=> add "delete" section describing new functionality

dev-docs/bidders/visx.md
No corresponding checks are done in Prebid.js or Prebid Server because the PR is aimed to fix the documentation issue.
=> VIS.X adapter update docs

dev-docs/bidders/appush.md
=> New Adapter: Appush

prebid-mobile/modules/rendering/android-sdk-integration-admob.md, prebid-mobile/modules/rendering/android-sdk-integration.md, prebid-mobile/modules/rendering/ios-sdk-integration-admob.md, prebid-mobile/pbm-api/android/code-integration-android.md, prebid-mobile/pbm-api/ios/code-integration-ios.md
=> Prebid Mobile changes for the version `2.0.4`

dev-docs/bidders/microad.md
=> Microad Bid Adapter: Support for User Ids

prebid-server/developers/add-new-bidder-go.md
Added a section on how to create a hardcoded alias in PBS-Go
=> pbs-go dev alias instructions

dev-docs/bidders/ix.md
=> Updated Video (instream) example and formatting

dev-docs/bidders/minutemedia.md, dev-docs/bidders/rise.md
=> rise doc maintenance

dev-docs/examples/sync-tid.md
=> Update sync-tid.md: fix link

dev-docs/bidders/viqeo.md
=> add viqeo prebid adapter

dev-docs/bidders/suntContent.md
**Adapter Pull Request:**
https://github.com/prebid/prebid-server/pull/2420
=> SUNT Content Bid Adapter: New Adapter

dev-docs/modules/zeusPrimeRtdProvider.md
Adding the documentation page for the Zeus Prime RTD Module. 
Reference PR in Prebid.js: https://github.com/prebid/Prebid.js/pull/9165
=> Add zeusPrimeRtdProvider Documentation Page

dev-docs/bidders/acuityads.md, dev-docs/bidders/kueezrtb.md, download.md
addresses acuityAds and kueezRtb file naming issues
=> added filename support on download page

dev-docs/bidders/kargo.md
=> Kargo adapter edit

dev-docs/bidders/adagio.md
=> Adagio: update userIds providers support

dev-docs/modules/jwplayerVideoProvider.md, prebid-video/video-module.md
We would like to add a few more references to JW Player docs to help publishers with their integration.
=> [JW Player Video Adapter] Add additional references to JW Player docs

dev-docs/bidders/openx.md
Mark _platform_ bid param as deprecated.
Adjust examples.
Fix a link to _First Party Data_ module.
=> OpenX Bid Adapter: update dev docs

dev-docs/bidders/vidazoo.md
Added `media_types` entry to Vidazoo docs
Prebid.js PR:
https://github.com/prebid/Prebid.js/pull/9284
=> Vidazoo: added media types

dev-docs/bidders/yieldlab.md
Yieldlab Bid Adapter reflect that the floors module is supported
=> Yieldlab Bid Adapter update dev docs

dev-docs/bidders/seedtag.md
Add examples for InStream and InBanner to the seedtag adapter. 
Also add safeframe support
=> Seedtag - update doc example for inBanner and inStream examples

dev-docs/bidders/afp.md, dev-docs/bidders/astraone.md, dev-docs/bidders/hybrid.md, dev-docs/modules/dfp_express.md, examples/video/outstream/pb-ve-outstream-dfp.html, examples/video/pb-video-template.html
Update based on https://github.com/prebid/prebid.github.io/issues/2293
=> Replace old gpt domain

dev-docs/bidders/algorix.md
update algorix dev-doc, change gdpr_supported to true. support gdpr.
=> update algorix support gdpr

dev-docs/bidder-adaptor.md, dev-docs/modules/enrichmentFpdModule.md
Document how first party data is now made available to all adapters by default.
https://github.com/prebid/Prebid.js/pull/9205
=> pbjs: document default FPD enrichment

dev-docs/publisher-api-reference/setConfig.md
- [x ] Related pull requests in prebid.js or server are linked
https://github.com/prebid/Prebid.js/pull/8947
=> Added section related to  Topics IFrame configuration

dev-docs/publisher-api-reference/enableAnalytics.md, overview/analytics.md
- [x ] new feature: event filter options in `pbjs.enableAnalytics`
=> PBJS: document new `enableAnalytics` event filter parameters

_layouts/home.html, dev-docs/modules/bidViewableIO.md, formats/formats.md, prebid-mobile/modules/rendering/android-sdk-integration-gam.md, prebid-mobile/pbm-api/ios/pbm-adunit-ios.md, prebid-server/use-cases/pbs-amp.md, prebid-video/video-getting-started.md
Additional pass from the broken link checker, plus resolves https://github.com/prebid/prebid.github.io/issues/4108
=> fix a few more broken links

dev-docs/bidders/globalsun.md
prebid.js - https://github.com/prebid/Prebid.js/pull/9307
prebid server - https://github.com/prebid/prebid-server/pull/2477
=> New Adapter: Globalsun

dev-docs/bidders/ix.md
Fixed table column names for ix bidder to match column names used in the other documentation files
=> ix documentation fix

dev-docs/modules/confiantRtdProvider.md
Added documentation for Confiant's RTD Provider Module.
Relevant Prebid.js PR: https://github.com/prebid/Prebid.js/pull/9325
=> Confiant's RTD Provider documentation

debugging/debugging.md, dev-docs/add-video-submodule.md, dev-docs/bidder-adaptor.md, dev-docs/common-issues.md, dev-docs/conditional-ad-units.md, features/adServerKvps.md, formats/amp.md, prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md, prebid-server/features/pbs-feature-idx.md, support/index.md
Cleanup of grammar, formatting, etc. from general site review.
=> Site cleanup for minor issues

dev-docs/analytics/adomik.md, dev-docs/analytics/adxcg.md, dev-docs/analytics/concert.md, dev-docs/analytics/eplanning.md, dev-docs/analytics/marsmedia.md, dev-docs/analytics/roxot.md, dev-docs/analytics/sharethrough.md, dev-docs/analytics/sigmoid.md, dev-docs/analytics/sonobi.md, dev-docs/analytics/zeta_global_ssp.md
Fix for Issue 4093 https://github.com/prebid/prebid.github.io/issues/4093
=> Added missing links to analytics adapter docs

dev-docs/modules/fledgeForGpt.md
tables weren't formatted properly
=> fledge doc - fixing tables

dev-docs/bidders/nexx360.md
=> Nexx360 prebid adapter update

dev-docs/bidders/kueezrtb.md
Prebid.js PR:
https://github.com/prebid/Prebid.js/pull/9326
=> Kueez RTB: Added video media type

dev-docs/bidders/rubicon.md
Related to https://github.com/prebid/prebid-server/pull/2465
=> Rubicon: new param

prebid-server/endpoints/openrtb2/pbs-endpoint-amp.md
Was of sync for PBS-Java since https://github.com/prebid/prebid-server/issues/1817
=> AMP endpoint update

prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md
=> Fixed bidder specific FPD config format

dev-docs/bidders/holid.md
=> Add docs for Holid bid adapter

dev-docs/publisher-api-reference/setConfig.md
PBJS GitHub Issue: https://github.com/prebid/Prebid.js/pull/9268
=> Updated setConfig doc page to include details about optional category targeting

dev-docs/bidders/ix.md
Corrected step 1 for server-side on how to enable the Index adapter
=> Updated ix.md on how to enable the Index adapter

prebid-server/developers/add-a-module-go.md, prebid-server/developers/add-a-module-java.md, prebid-server/developers/add-a-module.md, prebid-server/pbs-modules/ortb2-blocking.md
Related PRs in PBS:
- https://github.com/pi-prebid/prebid-server/pull/22
- https://github.com/pi-prebid/prebid-server/pull/23
- https://github.com/pi-prebid/prebid-server/pull/24
=> Document for adding a PBS Go Module

dev-docs/bidders/eplanning.md
Required on https://github.com/prebid/prebid-server/pull/2512
=> Update eplanning adapter media_types

dev-docs/modules/gdprEnforcement.md
thanks for finding @robertrmartinez
=> Fix param typo at gdprEnforcement.md

features/firstPartyData.md
docs for https://github.com/prebid/Prebid.js/pull/9258
=> Update firstPartyData.md -- delete site when app occurs

dev-docs/modules/userId.md, dev-docs/modules/userid-submodules/adriver.md
=> Add Adriver ID User ID sub-module

dev-docs/publisher-api-reference/bidderSettings.md
Related to https://github.com/prebid/Prebid.js/pull/9441
=> Prebid.js: update docs for `bidCpmAdjustment` and `inverseCpmAdjutment`

dev-docs/bidders/onetag.md
- https://github.com/prebid/Prebid.js/pull/9487
=> Add GPP Support to Onetag Bid Adapter

dev-docs/modules/consentManagement.md
- Updated the consent management docs to include information about the new actionTimeout feature.
- Prebid.js PR: https://github.com/prebid/Prebid.js/pull/9365
- GH Issue Ticket: https://github.com/prebid/Prebid.js/issues/9176
=> Consent Management:  Updated Consent Management docs to include info about actionTimeout

dev-docs/modules/userId.md, dev-docs/modules/userid-submodules/amxrtb.md
Updating domain / name for AMX ID system, corresponding to Prebid.js PR. Correction in description of functionality (e.g. user.eids)
=> update amxid documentation

debugging/debugging.md
Replacing wording for debugging with headerbid expert and also includes debugging module overview and link to docs
=> Update Debugging Page with Professor Prebid and Debug Module

dev-docs/bidders/minutemediaplus.md
MinuteMediaPlus Prebid.js adapter Pull Request:
https://github.com/prebid/Prebid.js/pull/9430
=> docs(module): MinuteMediaPlus bid adapter dev-docs

dev-docs/bidders/adsinteractive.md
=> Documentation for Adsinteractive Adapter

dev-docs/bidders/smilewanted.md
Related to this PR on PrebidJS : https://github.com/prebid/Prebid.js/pull/9440
- https://github.com/prebid/Prebid.js/pull/9440
=> SmileWanted Adapter : Update support of eids

dev-docs/modules/fledgeForGpt.md, prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md, prebid-server/features/pbs-feature-idx.md
The feature has already been released with PBS-Go and PBS-java
=> PBS fledge

prebid-mobile/pbm-api/android/code-integration-android.md, prebid-mobile/pbm-api/android/pbm-targeting-params-android.md, prebid-mobile/pbm-api/ios/pbm-targeting-ios.md
Clarification info about the build and integration process.
=> Mobile: various clarification info

dev-docs/bidders/iionads.md, dev-docs/bidders/limelightDigital.md
Add new fields which will be used for targeting in Limelight platform
https://github.com/prebid/Prebid.js/pull/9436
=> Limelight Digital Bid Adapter: add custom targeting fields, rename iionads title to iion

dev-docs/bidders/seedtag.md
=> Seedtag bid adapter -  Add GPP consent

dev-docs/bidders/bidbuddy.md
Documenting #https://github.com/prebid/Prebid.js/pull/9375
=> Adkernel: Documenting Bidbuddy

dev-docs/bidders/scattered.md
=> Add docs for Scattered bid adapter

dev-docs/bidders/brightcomssp.md
- [x ] new bid adapter
New adapter pull request
https://github.com/prebid/Prebid.js/pull/9411
=> BrightcomSSP bid adapter: add new bidder page

dev-docs/bidders/outbrain.md
https://github.com/prebid/Prebid.js/pull/9405
https://github.com/prebid/prebid-server/pull/2488
=> Outbrain: added video support and example

dev-docs/bidders/kiviads.md
=> New Adapter: Kivi

dev-docs/bidders/definemedia.md
Prebid server: [New Adapter: Definemedia](https://github.com/prebid/prebid-server/pull/2506)
=> New Adapter: Definemedia 

dev-docs/bidders/taboola.md
https://github.com/prebid/prebid-server/pull/2550
=> Taboola Bid Adapter : support native in prebid server

dev-docs/modules/sirdataRtdProvider.md
=> Page header fix

dev-docs/bidders/livewrapped.md
We just added support for the Price Floors Module (https://github.com/prebid/Prebid.js/pull/9540). We also became Prebid members.
=> Updated Livewrapped Bid Adapter documentation

dev-docs/bidders/algorix.md
update Algorix bidder support EU endpoint(use EUC region bidder param)
Prebid-Server link: https://github.com/prebid/prebid-server/pull/2602
Prebid-Server-Java link:  https://github.com/prebid/prebid-server-java/pull/2184
=> add EUC endpoint for Algorix

dev-docs/bidders/optidigital.md
=> New Adapter: Optidigital

dev-docs/modules/neuwoRtdProvider.md
Improved overview text, added apiUrl config parameter description
=> NeuwoRTDProvider: docs: Overview, apiUrl

dev-docs/bidders/adagio.md
=> Adagio: add user-sync config recommends

dev-docs/bidders/smaato.md
=> Update smaato.md to indicate gpp support

dev-docs/bidders/adagio.md
Related to https://github.com/prebid/Prebid.js/pull/9542.
=> Adagio: update doc video params

dev-docs/bidders/admedia.md
=> Admedia Adapter Doc

dev-docs/modules/topicsFpdModule.md
https://github.com/prebid/Prebid.js/pull/8947
=> Topics FPD module documentation and link added

dev-docs/module-rules.md, prebid-server/developers/add-new-bidder-go.md, prebid-server/developers/add-new-bidder-java.md
Related to https://github.com/prebid/prebid-server/issues/2437
=> PBS rules update

dev-docs/bidders/amx.md
- https://github.com/prebid/Prebid.js/pull/9556
=> Amx Bid Adapter : add gpp support

dev-docs/bidders/improvedigital.md
Improve Digital adapter: minor doc updates
=> Improve Digital adapter doc updates

dev-docs/bidders/gumgum.md
- https://github.com/prebid/Prebid.js/pull/9572
=> GumGum Bid Adapter : add gpp support

dev-docs/bidders/viously.md
Add the banner media type to the Viously Bid Adapter
=> Viously banner requests

dev-docs/analytics/oxxion.md
- [x ] new analytic adapter
- [ x] Related pull requests in prebid.js or server are linked
-  https://github.com/prebid/Prebid.js/pull/9449
- [x ] For new adapters check [submitting your adapter docs](https://docs.prebid.org/dev-docs/bidder-adaptor.html#submitting-your-adapter)
Prebid.js pull request: https://github.com/prebid/Prebid.js/pull/9449
=> oxxion Analytics Adapter

dev-docs/modules/floors.md
There has been confusion about floors skipRate -- this is an attempt to clarify
=> floors skipRate

dev-docs/bidders/criteo.md
=> Criteo: Update documentation to reflect real pbs capabilities

dev-docs/bidders/adnuntius.md
updated version of https://github.com/prebid/prebid.github.io/pull/4303
=> removing native support for adnuntius

dev-docs/bidders/stv.md
=> added stv adapter documentation

dev-docs/bidders/nexx360.md
=> Nexx360 Bid Adapter: native added and params added

dev-docs/bidders/grid.md
Support gpp consent in TheMediaGrid Bid Adapter.
=> TheMediaGrid: update doc

prebid-server/developers/add-new-bidder-java.md
=> Add docs for seatnonbid integrations for pbs java bid adapters

dev-docs/bidders/brightcomssp.md
This PR related to this issue https://github.com/prebid/prebid.github.io/issues/4432
=> BrightcomSSP: add missing aliasCode

dev-docs/faq.md
Noticed that "Amazon" is one of the search terms people are looking for on docs.prebid.org that has no search results.
=> adding TAM faq

dev-docs/bidders/adquery.md
=> Adquery - documentation edit

dev-docs/bidders/ttd.md
update ttd documentation with optional bidfloor parameter
https://github.com/prebid/Prebid.js/pull/9607
=> TTD Bid Adapter : bidfloor support

dev-docs/modules/userid-submodules/novatiq.md
=> Novatiq UserID Module: update docs to make it easier for clients

dev-docs/bidders/vidoomy.md
&nbsp;
Update doc for Vidoomy Adapter - added Schain module.
- https://github.com/prebid/Prebid.js/pull/9759
=> Updated doc for Vidoomy Schain module 

dev-docs/analytics/greenbids.md
Greenbids new analytics module.
=> add greenbids analytics documentation

dev-docs/bidders/criteo.md
Add support of GPP on documentation
=> Criteo: update doc

dev-docs/modules/userid-submodules/yahoo.md
This PR  is tied to the changes in [this PR](https://github.com/prebid/Prebid.js/pull/9716).
=> Updated documentation for Yahoo ConnectID UserID module

dev-docs/bidders/concert.md
Indicates that the Concert Bid Adapter now supports GPP consent.
=> Concert Bid Adapter: Indicate GPP support

dev-docs/publisher-api-reference/setConfig.md
- Added documentation in the PBJS docs for the batched video cache request feature.
=> Documentation for Batch Video Cache Requests

dev-docs/bidders/kueez.md, dev-docs/bidders/kueezrtb.md
=> Update KueezRTB and Kueez docs

dev-docs/bidders/yieldlab.md
=> Update Yieldab docs

dev-docs/bidders/yandex.md
=> Yandex adapter: add pbs support and add native media_type

dev-docs/modules/userid-submodules/liveintent.md
=> Add information about EIDS support for attributes resolved by LI's user id module

dev-docs/analytics/intentiq.md, dev-docs/modules/userid-submodules/intentiq.md
=> IntentIQ: add analytics and update id submodule docs

dev-docs/modules/enrichmentFpdModule.md
- text edit only (wording, typos)
- Change in default value
- Link to prebid.js PR : https://github.com/prebid/Prebid.js/pull/9711
=> FPD Enrichment: use low entropy method by default to fetch user agent data 

dev-docs/bidders/intertech.md
=> Intertech: creating doc for new server adapter

dev-docs/bidders/ivs.md
=> IVS Bid Adapter: New Adapter

dev-docs/bidders/9dotsmedia.md
=> 9Dots Media adapter

dev-docs/modules/permutiveRtdProvider.md
PR link: https://github.com/prebid/Prebid.js/pull/9697
=> Update Permutive documentation

dev-docs/bidders/pwbid.md
https://github.com/prebid/prebid-server/pull/2657
=> PubWise Support PBS

dev-docs/bidders/evolutionTechnologies.md, dev-docs/bidders/evtech.md, dev-docs/bidders/iionads.md, dev-docs/bidders/limelightDigital.md
=> New Adapter: Evolution Technologies

dev-docs/bidders/dspx.md
This PR is to update the documentation for the DSPx bidder adapter.
* schain support
* userIds support
* multiformat support
* bid params description
=> DSPx docs update
