- dev-docs/bidders/visx.md
Update the VIS.X documentation under the latest adapter changes.
> VIS.X: update docs

- dev-docs/bidders/futureads.md
add alias futureads
A link to a PR on the docs repo at Prebid.js [#7753](https://github.com/prebid/Prebid.js/pull/7753)
> Admixer Bid Adapter: add alias futureads

- prebid-mobile/modules/rendering/ios-sdk-Integration.md
Use the actual pod names instead of old ones in the docs
> Mobile: fix the pod's names

- dev-docs/bidders/improvedigital.md
Improve Digital adapter: Remove deprecated/not-to-be-used params
> Improve Digital adapter: Remove deprecated/not-to-be-used params

- dev-docs/bidders/apacdex.md
- dev-docs/bidders/quantumdex.md
- dev-docs/bidders/valueimpression.md
As mentioned in PR https://github.com/prebid/prebid-server/pull/2097, we currently support bidding via PBS.
This PR updates documentation regarding the Apacdex adapter and its alias (Quantumdex, Valueimpression) to update this to the documentation page.
> Update Apacdex, Quantumdex, Valueimpression docs

- dev-docs/bidders/algorix.md
Add Server Region Support:
* add region in ext.bidder: APAC for request to SG EP, USE for request to US EP, other for request to Global EP
PBS-Go: https://github.com/prebid/prebid-server/pull/2096
PBS-Java: https://github.com/prebid/prebid-server-java/pull/1598
> Algorix: add Server Region Support

- prebid-mobile/modules/rendering/ios-sdk-Integration.md
- prebid-mobile/modules/rendering/ios-sdk-integration-gam.md
The additional integration step is introduced.
> Prebid Mobile: Add warning for GAM integration on iOS.

- dev-docs/bidders/loglylift.md
Add Loglylift bid adapter dev-docs
Adapter PR: https://github.com/prebid/Prebid.js/pull/7761
> Loglylift adapter

- dev-docs/publisher-api-reference/setConfig.md
List `syncTimeout` as s2sConfig option
﻿Code changes: https://github.com/prebid/Prebid.js/pull/7744
Related: https://github.com/prebid/Prebid.js/issues/6354
> Add 's2sConfig.syncTimeout' option

- dev-docs/modules/weboramaRtdProvider.md
we add support to new features, should be reflected in the documentation
feature: https://github.com/prebid/Prebid.js/pull/7728
> update weborama RTD submodule doc to reflect latest feature update

- _layouts/bidder.html
adds a note when enable_download is false "This adapter is not available in current versions of Prebid.js."
> updated bidder layout

- dev-docs/bidders/medianet.md
Adding MediaNet into the Prebid server bidder list.
[PR Link](https://github.com/prebid/prebid-server-java/pull/1378)
> MediaNet adapter: Adding MediaNet into Prebid server bidder list

- dev-docs/bidders/conversant.md
Update the conversant bid params since site_id is no longer required
> SiteId is no longer required for the conversant adapter

- dev-docs/modules/jwplayerRtdProvider.md
Updates documentation for https://github.com/prebid/Prebid.js/pull/7886
> [AD-1505] [RTD - JW Player] Write to oRTB content segments

- dev-docs/bidders/conversant.md
Update to add support for first party data and examples.  
The PR for the adapter update is https://github.com/prebid/Prebid.js/pull/7966
> Conversant adapter now supports FPD options through ortb2 and ortb2Imp

- dev-docs/bidders/tappx.md
This changes is in response to the pull request: https://github.com/prebid/prebid-server/pull/2130
> Tappx :: avoid host

- dev-docs/bidders/adnuntius.md
- dev-docs/modules/adnuntiusRtdProvider.md
Adding information on how to set Adnuntius Bidder to not use cookies
> Use cookie information.

- dev-docs/bidders/deepintent.md
> DeepIntent: video docs added

- dev-docs/bidders/mediakeys.md
- Add FDP documentation #3444
- Add required modules documentation
> Mediakeys documentation improvements

- dev-docs/bidders/somoaudience.md
As noted in https://github.com/prebid/prebid-server/issues/2152, somoaudience no longer supports their server-side adapter
> deprecating somoaudience

- dev-docs/modules/dchain.md
This is a bit late (apologies), but this PR represents the docs tied around the new dchain module available for Prebid.js
The module code was already merged via https://github.com/prebid/Prebid.js/pull/7473
I would appreciate any feedback/word-smithing on this PR by interested parties, as describing  the business justifications and need for publishers is not exactly my forte.  
If there's any other information needed or other back-end pages that need to be updated to properly reflect this page as a module in the new style of prebid.org, please let me know.  I tried to look around to current examples and past PRs, and I didn't believe anything else should be needed than cleanly defining the headers.
> dchain module docs

- dev-docs/modules/debugging.md
- troubleshooting/troubleshooting-guide.md
See PBJS PR: https://github.com/prebid/Prebid.js/pull/7801
> Document new debugging module

- adops/setting-up-prebid-for-amp-in-dfp.md
- [ n/a ] Related pull requests in prebid.js or server are linked
- [ n/a ] For new adapters check [submitting your adapter docs](https://docs.prebid.org/dev-docs/bidder-adaptor.html#submitting-your-adapter)
> AdOps AMP - code type note

- dev-docs/adunit-reference.md
Added note recommending that AdUnit sizes cover the same list as AdX and OB
> adunit ref: added note about sizes

- dev-docs/publisher-api-reference/mergeBidderConfig.md
- dev-docs/publisher-api-reference/mergeConfig.md
- dev-docs/publisher-api-reference/setBidderConfig.md
- dev-docs/publisher-api-reference/setConfig.md
New mergeConfig feature updates `setBidderConfig` now to include a second argument that defaults to false and sets bidder config normally. If the argument is set to true the config is added. Supporting pr for new feature here. -> https://github.com/prebid/Prebid.js/pull/7396
> Prebid Publisher API: update setBidderConfig, mergeConfig, mergeBidderConfig

- dev-docs/bidders/adrino.md
This is a new adapter for Adrino unique demand.
> Adrino: new native adapter

- prebid-server/developers/add-new-bidder-java.md
> Update PBS-Java bidder creation documentation

- dev-docs/adunit-reference.md
- dev-docs/show-outstream-video-ads.md
- dev-docs/show-video-with-a-dfp-video-tag.md
- prebid-video/video-getting-started.md
Add recommendation to set API for Open Measurement if available
Clean-up formatting issues in video ad unit reference
Add links to the video ad unit reference
Update outstream doc to place all video parameters on the ad unit
- [ N/A] Related pull requests in prebid.js or server are linked
- [ N/A] For new adapters check [submitting your adapter docs](https://docs.prebid.org/dev-docs/bidder-adaptor.html#submitting-your-adapter)
> Add recommendation to set API for Open Measurement if available + Cleanup

- dev-docs/examples/adunit-refresh.md
- dev-docs/examples/basic-example.md
- dev-docs/examples/custom-price-buckets.md
- dev-docs/examples/instream-banner-mix.md
- dev-docs/examples/meta-bid-filtering.md
- dev-docs/examples/multi-format-example.md
- dev-docs/examples/native-ad-example.md
- dev-docs/examples/postbid.md
- dev-docs/examples/size-mapping.md
- dev-docs/examples/use-prebid-with-appnexus-ad-server.md
- dev-docs/getting-started.md
This updates jsFiddle links to all point to the "base" version of the fiddle. Separately, the base versions have all been updated to use the new jsDelivr Prebid URL (instead of appnexus').
> Update jsFiddle links to versions that use new CDN URL for Prebid

- dev-docs/modules/userId.md
https://github.com/prebid/Prebid.js/issues/8151 identified the ppid was not working in video.
> Clarify GAM PPID only works with GPT api, not IMA api

- dev-docs/modules/userId.md
> Add dacid user id module

- dev-docs/modules/idWardRtdProvider.md
Added the readme file for the idWardRtdProvider RTD module according to the requirement https://docs.prebid.org/dev-docs/add-rtd-submodule.html#step-5-website-pull-request
> readme file for idWardRtdProvider

- dev-docs/bidders/improvedigital.md
Related code PR: https://github.com/prebid/Prebid.js/pull/7975
> Improve Digital adapter: added renderer config

- dev-docs/bidders/distroscale.md
This change includes documentation of the new DistroScale Bid Adapter and the sample parameters for testing purpose, as required by PrebidJS submission process.  The code PR link is https://github.com/prebid/Prebid.js/pull/8221
> Add DistroScale Bid Adapter

- README.md
- _layouts/bidder.html
- dev-docs/bidder-adaptor.md
- dev-docs/bidders/rubicon.md
- dev-docs/pbs-bidders.md
- prebid-server/developers/add-new-bidder-go.md
- prebid-server/developers/add-new-bidder-java.md
Adds a new field `multiformat_supported` to the bidder table, which indicates the behaviour of a bid adapter when more than one media type (`banner`, `native`, `video`) is being requested.
Possible values are
* `will-bid-on-any` - bidder will bid on any media type
* `will-bid-on-one` - bidder will prioritize one media type and ignores the others
* `will-not-bid` - bidder will not bid at all
> Fix #3327 add multiformat_supported field

- dev-docs/bidders/adot.md
This pull request fixes a typo in the publisherPath parameter for prebid server
> Adot: fix parameter publisherPath typo

- dev-docs/modules/userId.md
module name is: pubProvidedIdSystem, instead of pubProvidedId
> Build package info for pubProvidedIdSystem fix

- Gemfile
Jekyll doesn't start with ruby3 . This PR adds the dependency. 
https://github.com/jekyll/jekyll/issues/8523
- [X ] bugfix (code examples)
> fix for jekyll not starting with ruby 3

- dev-docs/bidders/triplelift.md
Revamping Triplelift's bidder parameters page to be more verbose.
> Triplelift: update bidder params page

- dev-docs/bidders/amx.md
Updating AMX bid adapter documentation to indicate support for native format. See https://github.com/prebid/prebid-server/pull/2220 for relevant code change.
> update docs to indicate native support

- dev-docs/modules/userId.md
- download.md
Add documentation for a new user id sub-module: 33acrossId
> Add 33Across user id sub-module

- dev-docs/publisher-api-reference/bidderSettings.md
Added description of change for `allowAlternateBidderCode` & `allowedAlternateBidderCode` property in `bidderSettings`
> Added documentation for allowAlternateBidderCodes property

- dev-docs/analytics/ats.md
The `modulecode` for the ATS analytics adapter is incorrect, which causes errors when trying to download it from Prebid.org (https://github.com/prebid/Prebid.js/issues/8376)
> Fix `modulecode` for the ATS analytics adapter

- dev-docs/modules/userId.md
- download.md
Fix formatting of 33Across configuration params + Add missing ID suffix
> Fix wrong formatting of 33Across configuration params

- dev-docs/bidders/aax.md
This change includes documentation of the new Aax Bid Adapter. The code [PR link](https://github.com/prebid/prebid-server-java/pull/1811)
> Adding Aax bidder adapter doc

- dev-docs/faq.md
Documentation of https://github.com/prebid/Prebid.js/pull/8171
> Change macro resolution langauge

- dev-docs/bidders/ix.md
This change updates the documentation of the outstream implementation for IX
Key refactors include:
Related to PR: https://github.com/prebid/Prebid.js/pull/8412
> IX Adapter:  Outstream Docs Update

- dev-docs/bidders/oftmedia.md
oftmedia doesn't yet have a server-side adapter
> oftmedia doesn't support PBS

- dev-docs/modules/userId.md
- download.md
Adding Gravito User module into prebid.
Add Gravito Id
> Add Gravito Id 

- dev-docs/modules/userId.md
Removing the documentation nothing support of a custom ClientID to prevent any new implementations from using it.
- [ X ] text edit only (wording, typos)
> Remove notice of support of custom clientID

- dev-docs/bidders/slimcut.md
- dev-docs/bidders/spotx.md
- dev-docs/bidders/telaria.md
Docs for https://github.com/prebid/Prebid.js/pull/8501
At this point, the various Magnite exchanges are not in fact able to use the same GVL ID.
> Magnite adapter GVL ID update

- dev-docs/bidders/appnexus.md
Related to #3444
Adds a clarifying note to the appnexus bidder file that clarifies when First Party Data is supported by the bidder.
> appnexus First Party Data updates

- dev-docs/bidders/mediakeys.md
> Require supply chain module in mediakeys adapter

- dev-docs/faq.md
Got additional info about the ad manager HB yield group feature
> update to HB yield group FAQ

- dev-docs/bidders/criteo.md
Add documentation for missing "publisherSubId" bid param
Address https://github.com/prebid/prebid.github.io/issues/3766
> [Criteo] Add missing documentation on "publisherSubId" bid param

- dev-docs/modules/consentManagement.md
With prebid 7, the consentManagement module will no longer support TCFv1 CMPs.
PBJS PR: https://github.com/prebid/Prebid.js/pull/8356
> Prebid 7: consent management - remove references to TCFv1 and update examples to use TCFv2

- dev-docs/add-rtd-submodule.md
- dev-docs/bidder-adaptor.md
- dev-docs/modules/enrichmentFpdModule.md
- dev-docs/modules/validationFpdModule.md
- dev-docs/publisher-api-reference/requestBids.md
- dev-docs/publisher-api-reference/setConfig.md
- features/firstPartyData.md
Related PBJS changes:
- https://github.com/prebid/Prebid.js/issues/7651 - auction-specific first party data
- https://github.com/prebid/Prebid.js/issues/8283 - removal of legacy FPD support (I could not find references to this in the doc; did I miss some?)
> Prebid 7: update docs related to first-party data

- dev-docs/bidders/trafficgate.md
- [+] new bid adapter
- [+] Related pull requests in prebid.js or server are linked
- [+] For new adapters check [submitting your adapter docs](https://docs.prebid.org/dev-docs/bidder-adaptor.html#submitting-your-adapter)
Prebid Server pull request link: https://github.com/prebid/prebid-server/pull/2226
> Add new Adapter: TrafficGate

- dev-docs/bidders/criteo.md
This is to make more clear that our bidder is actually including our id module features.
cc @patmmccann
> Criteo - State more explicitly that our bidder automatically includes our id module features

- dev-docs/bidders/ix.md
Updating documentation for IX to outline our support for Native mediaTypes.
PBJS PR: https://github.com/prebid/Prebid.js/pull/8533
> IX Bid Adapter: Documentation for Native Support

- dev-docs/bidder-adaptor.md
Update the bid adapter guide to mention the new FEATURES.NATIVE flag
PBJS PR: https://github.com/prebid/Prebid.js/pull/8219
> PBJS: document the NATIVE feature flag for bid adapters

- _includes/video/pb-is-fp.html
- examples/video/instream/flowplayer/pb-ve-flowplayer.html
This PR will uprade Flowplayer example to use the latest version of Flowplayer.
> chore: upgrade flowplayer to v3

- dev-docs/bidders/adot.md
schain & userIds: pubProvidedId are now supported.
Related PrebidJs PR: https://github.com/prebid/Prebid.js/pull/8670
> [DSP-3690] feature: Add schain & pubProvidedId (#5)

- dev-docs/modules/userId.md
The `setTimeout` method takes _milliseconds_ as a parameter, not seconds. So the docs are not correct:
https://github.com/prebid/Prebid.js/blob/ea29fa16cbea64e85cbbc4c6dab85cea2afb6e0c/modules/userId/index.js#L720-L732
> registerDelay of ESP is actually milliseconds

- dev-docs/modules/userId.md
- [ x ] text edit only (wording, typos)
> Update descriptions for notUse3P param

- prebid-server/pbs-modules/ortb2-blocking.md
> pbs ortb-block fix formatting

- dev-docs/modules/imRtdProvider.md
Doc change for
- https://github.com/prebid/Prebid.js/pull/7359
- https://github.com/prebid/Prebid.js/pull/8657
> add doc: imRtdModule

- dev-docs/modules/gdprEnforcement.md
Document new `consentManagement.strictStorageEnforcement` config: https://github.com/prebid/Prebid.js/pull/8661
> GDPR enforcement module: document new `strictStorageEnforcement` config

- dev-docs/bidders/mobilefuse.md
> Updated missing params for mobilefuse

- dev-docs/bidder-adaptor.md
Documentation and resources around simple requests and CORS preflight request triggers. 
Reference to issue (https://github.com/prebid/Prebid.js/issues/8500)
> Simple Requests in HTTP, Headers, and CORS Preflight triggers

- prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md
Primarily updating the "Prebid Server ORTB2 Extension Summary" section for improved readability and with updated content. I've improved readability by separating request and response fields to their own separate tables (the Adapter Sees? column does not apply to the response, use `<wbr>` to provide breakpoint hints instead of spaces which can lead to rendering artifacts, and folded the Example column into the description. At large desktop size, the entire table now fits within the article area.
Updated misc things along the way, as commented to explain why.
> Update PBS Auction Endpoint Doc

- dev-docs/bidders/triplelift.md
Fixing incorrect version for supporting outstream
> Triplelift: Typo, updates version for outstream

- dev-docs/modules/userId.md
- dev-docs/publisher-api-reference/registerSignalSources.md
https://github.com/prebid/Prebid.js/pull/8117
> Fix #3830 and add ESP registerSignalSources docs

- dev-docs/bidders/criteo.md
bid.adId will no longer be set by Criteo so this pull-request aims at removing the disclosure on Criteo's documentation page.
See [#8783](https://github.com/prebid/Prebid.js/pull/8783) for the change in Prebid.js
> Criteo: remove disclosure on adId

- dev-docs/bidders/ttd.md
Remove siteId
Update language for publisherId, placementId
https://github.com/prebid/Prebid.js/pull/8679
> TTD Adapter updates

- dev-docs/integrate-with-the-prebid-analytics-api.md
With https://github.com/prebid/Prebid.js/pull/8599, analytics adapters need to import the base adapter from a different place - this updates the guide to reflect that.
> PBJS: update analytics adapter guide with new file paths

- dev-docs/analytics/kargo.md
A fenced code block missing its closing backticks was breaking the layout of https://docs.prebid.org/overview/analytics.html.
> Closed fenced code block

- dev-docs/bidders/between.md
> BetweenBidAdapter: default cur is USD

- dev-docs/adunit-reference.md
to cover [Prebid.js/pull/8833](https://github.com/prebid/Prebid.js/pull/8833)
This adds a description as well as an example for mediaType.video.useCacheKey
> update adunit reference

- dev-docs/bidders/adagio.md
Add a section in Adagio related to the need to explicitly set `bidderSettings.storageAllowed: true`.
> Adagio: add `BidderSettings.storageAllowed` note

- dev-docs/bidders/improvedigital.md
Improve Digital adapter has supported the floors module for quite a while but it seems the adapter doc says otherwise. Fixing it now.
> Improve Digital adapter: Floors module support

- features/firstPartyData.md
When reviewing the documentation for the First Party Data feature, in the **Supplying OpenRTB Content Data** example I noticed that the `keywords` value had an array of strings, which was different to the other keyword fields in other parts of the ortb2 examples.
I checked the ORTB2.5 [spec](https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf) and confirmed that the keywords field in this area should be a comma separated string.  I made this PR to fix the type in the example.
> fix FPD content keywords example

- dev-docs/bidders/ix.md
Deprecates the usage of detectMissingSize config.
prebid.js MR: https://github.com/prebid/Prebid.js/pull/8906
> IX Bid Adapter: deprecate detectMissingSiez config

- dev-docs/analytics/liveintent.md
> LiveIntent Analytics Adapter

- _layouts/home.html
apparently prebids twitter username changed, but the site was never update to reflect the change.
> Update Twitter username

- dev-docs/bidders/e_volution.md
- dev-docs/bidders/ias.md
- dev-docs/bidders/iprom.md
- dev-docs/bidders/luponmedia.md
- dev-docs/bidders/missena.md
- dev-docs/bidders/open8.md
- dev-docs/bidders/optimera.md
- dev-docs/bidders/outbrain.md
- dev-docs/bidders/smartx.md
- dev-docs/bidders/talkads.md
- dev-docs/bidders/turktelekom.md
- dev-docs/bidders/vibrantmedia.md
Clean up the download page with notes that are outdated or no longer reference a current maintained version
> Remove notes for adapters referring to versions prior to 6.x

- dev-docs/modules/userId.md
Related pr: https://github.com/prebid/Prebid.js/pull/9053
> LiveIntent UserId Module: Allow resolving uid2

- features/firstPartyData.md
Add an example of setting `ortb2Imp.ext.tid`, followup to https://github.com/prebid/Prebid.js/issues/8807
> PBJS: add example on setting custom transactionId

- dev-docs/publisher-api-reference/setConfig.md
This change documents use of setting a custom cpm rounding function in the config.
- [ x ] new feature
[Change pull request](https://github.com/prebid/Prebid.js/pull/9018)
@robertrmartinez
> Prebid Core: Document setting custom cpm rounding config

- dev-docs/modules/enrichmentFpdModule.md
Document support for user agent client hints in the fpdEnrichment module.
https://github.com/prebid/Prebid.js/pull/8826
> PBJS: document fpdEnrichment ua client hints support

- dev-docs/adunit-reference.md
- dev-docs/show-outstream-video-ads.md
Old versions of prebid had an undocumented feature - bid-level custom renderers. https://github.com/prebid/Prebid.js/pull/9128 restores the feature, and this is an attempt to document it.
> PBJS: document `adUnit.bids[].renderer`

- dev-docs/bidders/improvedigital.md
Improve Digital adapter: adding publisherId param. The param is marked as "required" which would be a breaking change for our customers and so for an interim period our adapter won't enforce it. Making it mandatory is our longer term plan.
> Improve Digital adapter: adding publisherId param

- dev-docs/modules/userId.md
The ConnectID User Identity module has been extended to support an optional additional input parameter.
> ConnectID User ID module: Document extended configuration options

- dev-docs/bidder-adaptor.md
Document new PBJS-ORTB conversion library - https://github.com/prebid/Prebid.js/pull/8738, or rather, point to its documentation in source.
Note that the link won't be valid until that PR is merged into master; currently the source docs can be found at  https://github.com/dgirardi/Prebid.js/blob/pbjs-ortb-squash/libraries/ortbConverter/README.md
> PBJS: document ORTB conversion library

- dev-docs/publisher-api-reference/getEvents.md
- dev-docs/publisher-api-reference/onEvent.md
PR to Prebid.js: https://github.com/prebid/Prebid.js/pull/9195
> Updated Info for adRenderSucceeded Event

- dev-docs/bidders/ix.md
Updating documentation for mediaType specific stieId overrides. This docs update relates to the following PR: https://github.com/prebid/Prebid.js/pull/9173
- [ x] new feature
> IX Bid Adapter: docs update for siteId overrides

- dev-docs/bidders/ix.md
The table for our multi-format siteId override section wasn't rendering correctly. This MR addresses that issue. 
Related to: https://github.com/prebid/Prebid.js/pull/9173 (already merged)
> IX Bid Adapter: Multi-format SiteId Table Fix

- dev-docs/bidders/aax.md
> AAX Adapter: Added medianet alias code

- dev-docs/modules/userId.md
> Remove the example of the minimal version of Live Connect

- dev-docs/modules/userId.md
Currently the command is shown outside of the alert-info section:
> Fix the command in userId to be in alert-info section 

- dev-docs/modules/userId.md
> Update dacid userid module documents

- dev-docs/bidders/kueezrtb.md
KueezRTB Prebid.js adapter Pull Request:
https://github.com/prebid/Prebid.js/pull/9065
> docs(module): kueezrtb adapter dev-docs

- dev-docs/bidders/freewheel-ssp.md
- dev-docs/bidders/freewheelssp.md
> freewheel ssp add prebid go adapter - update freewheel dev doc

- dev-docs/modules/fledgeForGpt.md
Add documentation for the experimental FLEDGE support module. This is linked with:
https://github.com/prebid/Prebid.js/pull/9127
> fledgeForGpt Module Docs

- dev-docs/publisher-api-reference/renderAd.md
Relates to: https://github.com/prebid/Prebid.js/issues/9060
> pbjs.renderAd Doc: Updated to include details about the ${CLICKTHROUGH} macro feature

- dev-docs/modules/captifyRtdProvider.md
Adding the documentation page for the Captify RTD submodule.
Related prebid.js PR: https://github.com/prebid/Prebid.js/pull/9180
> Add captifyRtdProvider Documentation Page

- dev-docs/faq.md
As discussed in the Identity and Privacy committee, here's a cut at a FAQ entry
It really ought to be a page of its own, but let's start with a FAQ and then figure out where to move it.
> adding privacy regulation FAQ

- dev-docs/bidder-adaptor.md
This adds an alert and makes more prominent the ORTB library when creating a new bid adapter.
> Alert on ortb convesion and move up wording

- dev-docs/module-rules.md
The doc says "Even grandfathered modules must adhere to all required rules by Prebid.js 5.0." I'm aware of enforcements in a couple areas, but would like help reviewing the other rules for whether all bidders conform.
> reviewing module rules

- dev-docs/analytics/growthcode.md
https://github.com/prebid/Prebid.js/pull/9021
> Update to prebid website for the new GrowthCode Analysis Module

- prebid-video/video-module.md
Adds a new event, AUCTION_AD_LOAD_QUEUED and fixes a typo in the event names:
Event names are in the format `'videoXyz'`, not `'video_xyz'`
https://github.com/prebid/Prebid.js/pull/9226
> Video Module: Ad Queue

- guide.md
Updated the guide to include instructions for opening the left nav to a certain location when a page not included in the sidebar.yml file is selected.
> Update guide with instructions for files not in sidebar

- dev-docs/bidder-adapter-1.md
- dev-docs/bidder-adapter.md
In the file structure for how to create a new bid adapter there are 2 extra files. 1 has the same name as the file we use and only redirects to that file. The other is how to create a PBjs 1.0 adapter. Deleted both these as cleanup
> How to add a bid adapter old doc cleanup

- dev-docs/modules/zeusPrimeRtdProvider.md
Removing the documentation page for the Zeus Prime RTD Module as we have deprecated the business.
Prebid.js PR: prebid/Prebid.js#9358
> Remove zeusPrimeRtdProvider documentation page

- dev-docs/bidders/viously.md
PR in Prebid.js : https://github.com/prebid/Prebid.js/pull/9076
> Viously Bid Adapter : New Adapter

- dev-docs/bidders/visx.md
- Updated type documentation of `uid` that supports both `integer` and `string`, with `integer` being preferred.
- Synced to the latest upstream master
- prebid-server: https://github.com/prebid/prebid-server/pull/2501
- prebid-server-java: https://github.com/prebid/prebid-server-java/pull/2096
> VISX: Update type support for uid

- dev-docs/bidders/adagio.md
Remove description of no more used bid params.
Related PR: https://github.com/prebid/Prebid.js/pull/9398
> Adagio: update bidAdapter params description

- dev-docs/publisher-api-reference/installedModules.md
Per discussion on Slack, this removes the outdated documentation that if all modules are included, an empty array is returned. In modern Prebid.js, all modules will be returned from the API.
> remove reference to installedmodules returning an empty array

- dev-docs/bidders/ix.md
Adds GPP support to IX bidder doc.
PBJS: https://github.com/prebid/Prebid.js/blob/master/modules/ixBidAdapter.js#L722
Prebid Server: adapter passes regs to exchange.
For more information contact shahin.rahbariasl@indexexchange.com.
> IX Bid Adapter: add gpp support flag to ix bidder doc

- dev-docs/bidders/mobilefuse.md
Added "native" under media_types to reflect the support of native that was added to the MobileFuse Adapter, 
pull request: (https://github.com/prebid/prebid-server/pull/2517)
> MobileFuse Adapter: native support added to docs

- dev-docs/bidders/triplelift.md
Added GPP support to Triplelift bidder page.
> TL-34447 Add GPP Support to Prebid.org

- dev-docs/bidders/adbite.md
- dev-docs/bidders/adkernel.md
- dev-docs/bidders/adsolut.md
- dev-docs/bidders/audiencemedia.md
- dev-docs/bidders/bcm.md
- dev-docs/bidders/headbidding.md
- dev-docs/bidders/houseofpubs.md
- dev-docs/bidders/rtbdemand_com.md
- dev-docs/bidders/sonic_twist.md
- dev-docs/bidders/waardex_ak.md
> Adkernel: consistent zoneId parameter type across aliases

- dev-docs/publisher-api-reference/aliasRegistry.md
- dev-docs/publisher-api-reference/setConfig.md
Added doc page for pbjs.aliasRegistry
> Publisher API Reference: Added doc page for pbjs.aliasRegistry

- dev-docs/bidders/vidazoo.md
This PR updates the docs params list with optional flag for the `bidFloor` param.
> Vidazoo Bid Adapter - bidFloor changed from required to optional param

- dev-docs/integrate-with-the-prebid-analytics-api.md
There's an issue in `integrate-with-the-prebid-analytics-api.md` that causes the list of benefits of integrating with the Prebid Analytics API to not be rendered in the HTML, probably because of the instruction used to generate the table of contents. This is how the page looks on all the browsers on which I tested:
The proposed fix is to separate the list and the TOC by introducing some text that will not be rendered in the HTML. This is how the page looks with the proposed fix:
- text edit only (wording, typos)
> Fix for TOC issue

- _includes/footer.html
I created a Google Analytics v4 property, which is linked to the old universal property. 
It seems to work without any code changes. However I would merge this once we see that the data matches.
And then ultimately remove the `UA-130832561-2` universal analytics property.
> Add new google analytics v4 tag

- dev-docs/bidders/cwire.md
New CWire prebid server adapter supporting ORTB2 protocol.
- new bid adapter
> CWire: Introduce prebid server adapter

- dev-docs/bidders/nextroll.md
- dev-docs/bidders/onetag.md
- dev-docs/bidders/sonobi.md
Those bidders have floor module support, but was not properly documented
> Document floor support for adapters that have it

- prebid-mobile/pbm-api/android/code-integration-android.md
- prebid-mobile/pbm-api/ios/code-integration-ios.md
Tables with test PBS configs that are used in the Demo Apps and which publishers can use to verify their integration. 
Closes https://github.com/prebid/prebid-mobile-ios/issues/783
> Mobile add test ad unit configs

- dev-docs/adunit-reference.md
- dev-docs/modules/prebidServer.md
https://github.com/prebid/Prebid.js/pull/9470
> PBJS: Document `adUnit.bids[].ortb2Imp` and `module`

- prebid-server/endpoints/pbs-endpoint-cookieSync.md
- prebid-server/hosting/bidder-specific-guidelines.md
- prebid-server/hosting/pbs-hosting.md
Added a page where bidders can place instructions to PBS host companies
This is a draft - need @SyntaxNode to comment on how host companies could disable bidders if they wish.
> PBS bidder specific guidelines

- dev-docs/bidders/pwbid.md
Bid adapter update at: https://github.com/prebid/Prebid.js/pull/9576
> Update PubWise Bidder Docs

- dev-docs/bidders/lemmadigital.md
> New Adapter: Lemmadigital

- dev-docs/bidders/amx-server.md
…rt on prebid-server
Fixes https://github.com/prebid/prebid.github.io/issues/4415 -- separate docs for AMX prebid.js and prebid-server adpaters, -- amx prebid.js adapter doesn't support native mediaType.
> AMX RTB: Separate documentation for amx/amx-server

- dev-docs/bidders/pwbid.md
In the previous update we modified instructions for integration but missed the needed update to the "media_types" line. This update corrects that.
> PubWise PWBID Video Update Correction

- dev-docs/bidders/underdogmedia.md
- Added support for user ids: 33acrossId, pubCommonId, unifiedId
- Added optional param: productId
> Underdog Media Bid Adapter: Add support for user ids and product id

- dev-docs/bidders/adagio.md
> Adagio: Add documentation for splitKeyword and dataLayer params

- dev-docs/bidders/smaato.md
As described in prebid/Prebid.js#9676 adapters should also accept geolocation from ortb2
> Smaato: accept geolocation data also from ortb2

- dev-docs/publisher-api-reference/bidderSettings.md
Document new options for the `bidderSettings.*.storageAllowed` setting - see https://github.com/prebid/Prebid.js/pull/9660
> PBJS: document new `storageAllowed` options

- dev-docs/add-rtd-submodule.md
Document new `gvlid` option for RTD module specs: https://github.com/prebid/Prebid.js/pull/9736
> PBJS: document new  option for RTD submodules

- dev-docs/bidders/mgid.md
https://github.com/prebid/Prebid.js/pull/9751
> Mgid Adapter: update mgid adapter adding support of user sync & ortb2

- dev-docs/bidders/appnexus.md
Related to #4415
Changing flag for fpd to avoid confusion
> appnexus - change fpd flag

- dev-docs/bidders/cleanmedianet.md
Per issue https://github.com/prebid/prebid.github.io/issues/4448
This was removed a couple of years ago as part of an alias cleanup, and is still needed.
@cleanmedianet - please review. Prebid publishers want more information about the capabilities of bidders. Please supply as many of the following fields as you can as described in https://docs.prebid.org/dev-docs/bidder-adaptor.html#submitting-your-adapter
gdpr_supported:
usp_supported:
coppa_supported:
schain_supported:
floors_supported:
userIds:
prebid_member:
safeframes_ok:
deals_supported:
pbs_app_supported:
fpd_supported:
ortb_blocking_supported:
gvl_id:
multiformat_supported:
> re-adding cleanmedianet

- _includes/footer.html
- _includes/head--common.html
Use google analytics with consent
This PR adds consent support for google analytics. I wasn't able to test this locally as the callback never fired. I will test this with the preview build
- https://support.google.com/analytics/answer/10022331?hl=de
- https://community.cookiepro.com/s/article/UUID-d8291f61-aa31-813a-ef16-3f6dec73d643?language=en_US
> Support consent mode for google analytics

- prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md
Document behavior for OpenRTB 2.6-202303 fields. Did not explicitly mention `imp[].qty.ext` since the behavior is the same as/subset of `imp[].qty` which is already included in the docs.
> Add PBS OpenRTB 2.6-202303 Fields

- dev-docs/adunit-reference.md
> Adunit reference: remove duplicate listing of the `video.placement` option

- prebid-mobile/modules/rendering/android-sdk-customization-controls.md
- prebid-mobile/modules/rendering/android-sdk-integration-admob.md
- prebid-mobile/modules/rendering/android-sdk-integration-gam.md
- prebid-mobile/modules/rendering/android-sdk-integration-max.md
- prebid-mobile/modules/rendering/android-sdk-integration-pb.md
- prebid-mobile/modules/rendering/ios-sdk-integration-admob.md
- prebid-mobile/modules/rendering/ios-sdk-integration-gam.md
- prebid-mobile/modules/rendering/ios-sdk-integration-max.md
- prebid-mobile/modules/rendering/ios-sdk-integration-pb.md
- prebid-mobile/pbm-api/android/android-sdk-integration-gam-original-api.md
- prebid-mobile/pbm-api/ios/ios-sdk-integration-gam-original-api.md
Updated Prebid Mobile documentation for the multiformat feature. Added sultiformat examples.
> Mobile SDK multiformat feature

- dev-docs/bidders/vidoomy.md
> Updated docs for Vidoomy blocking supported

- dev-docs/modules/greenbidsRtdProvider.md
> greenbids RTD provider

- prebid-server/features/pbs-privacy.md
The bit count removed for ipv6 was incorrect for COPPA
> update ipv6 anon

- dev-docs/bidders/eskimi.md
> Add Eskimi bidder documentation

- dev-docs/adunit-reference.md
- dev-docs/bidders/adhash.md
> AdHash bid adapter changes

- dev-docs/bidders/criteo.md
- https://github.com/prebid/Prebid.js/commit/eeab092d7642cde5bf70f5620155452631ffa56f
- https://github.com/prebid/Prebid.js/commit/73a1a723a5f0314cc4bbbac96a32fa2e63d642b4
PRs
- https://github.com/prebid/Prebid.js/pull/10013
- https://github.com/prebid/Prebid.js/pull/9975
> Criteo Bid Adapter : Update documentation according to latest features added about video & rwdd support

- dev-docs/modules/userid-submodules/yahoo.md
- [ x] update bid adapter
- [ x] new examples
- [ x] https://github.com/prebid/Prebid.js/pull/9965
> Yahoo ID: ConnectId auto generated puid and storage updates.

- dev-docs/modules/idLibrary.md
- download.md
This adds some JavaScript code to the download page which automatically selects the modules based on the URL parameter, to allow sharing or storing a link with a custom list of preselected modules.
If I want to add or remove a module from prebid, I can skip the step of selecting all current modules, which can be quite tedious with many modules.
Additionally, the download page URL is being changed to the selected modules.
Example link: https://docs.prebid.org/download.html?modules=appnexusBidAdapter%2CconnectadBidAdapter%2CconsentManagement%2Ccurrency%2Cid5IdSystem%2CixBidAdapter%2CmedianetBidAdapter%2CpriceFloors%2CrubiconBidAdapter%2CsharedIdSystem%2CstroeerCoreBidAdapter%2CteadsBidAdapter%2CtripleliftBidAdapter%2CuserId&version=7.34.0
> Auto select modules with URL param

- prebid-server/pbs-modules/ortb2-blocking.md
In the code for the oRTB Blocking Module configuration, there is [a condition](https://github.com/prebid/prebid-server-java/blob/d1459aa1888f02fbb92d767e78ebb0ad9fe23192/extra/modules/ortb2-blocking/src/main/java/org/prebid/server/hooks/modules/ortb2/blocking/spring/config/Ortb2BlockingModuleConfiguration.java#L10) for the `hooks.ortb2-blocking.enabled` to be set to `true` in order for the module to be loaded. 
This appears to not be mentioned in the existing documentation for the module.
> Added config property instructions to enable Blocking Module in PBS Java

- dev-docs/activity-controls.md
- dev-docs/faq.md
- dev-docs/publisher-api-reference/setConfig.md
Documentation for the new activity control system - https://github.com/prebid/Prebid.js/pull/9802
> Prebid.js: activity controls

- dev-docs/bidders/conceptx.md
(https://github.com/prebid/Prebid.js/pull/9835)
> New Adapter: Conceptx

- dev-docs/modules/mass.md
in response to issue #4535, adding a note that the mass module is not in PBJS 8.0 or later.
> marking mass as deprecated

- dev-docs/bidders/qortex.md
Company name change from 'CatapultX' to 'Qortex' - Updating the bid adapter alias names and host parameters
https://github.com/prebid/Prebid.js/pull/10056
> Add Qortex.AI bidders dev-docs

- dev-docs/modules/userId.md
- dev-docs/modules/userid-submodules/cpexid.md
Docs changes for this PR: https://github.com/prebid/Prebid.js/pull/9433
updated user id submodule
> Renamed cpexId to czechAdId

- .markdownlintignore
- dev-docs/adunit-reference.md
- dev-docs/analytics-ga.md
- dev-docs/bidder-adaptor.md
- dev-docs/bidders.md
Further markdown lint fixes.
Relates to
- https://github.com/prebid/prebid.github.io/pull/4646
- https://github.com/prebid/prebid.github.io/pull/4620
> Fix top level linting errors in dev-docs

- dev-docs/activity-controls.md
changed deviceAccess to accessDevice
> PBJS activity-controls: fixed typo

- dev-docs/modules/weboramaRtdProvider.md
> update weborama rtd submodule docs

- .markdownlint.json
Found a reference that explained to set    "MD022": false, // Headers should be surrounded by blank lines disabled so that {: .no_toc } is next to its heading
> updating linter rules

- dev-docs/bidders/apester.md
- dev-docs/bidders/evtech.md
- dev-docs/bidders/iionads.md
- dev-docs/bidders/limelightDigital.md
https://github.com/prebid/Prebid.js/pull/10057
> Add Apester prebid js adapter doc

- dev-docs/bidders/pubmatic.md
PR https://github.com/prebid/Prebid.js/pull/6773 is merged.
> pubmatic.md update for dctr parameter

- dev-docs/bidders/ix.md
Add 33Across to IX's list of supported userIds, fix lint issues.
> IX Bid Adapter: Add 33Across to IX's list of userIds

- dev-docs/bidders/trafficgate.md
> Trafficgate Bid Adapter: move to OpenRTB Converter

- dev-docs/bidders/medianet.md
- added support for gpp (supported since: https://github.com/prebid/Prebid.js/pull/8607)
- added support for coppa (supported since: https://github.com/prebid/Prebid.js/pull/5195)
> GPP and COPPA support for Medianet Bidder Adapter

- prebid-server/developers/pbs-cookie-sync.md
added note that bidder sync should create an ID if they don't have one
> PBS cookie sync reference update

- dev-docs/bidders/pulsepoint.md
Disclosure on the documentation was removed, not applicable after the [#Prebid](https://github.com/prebid/Prebid.js/pull/10177) Adapter changes. Due apologies for not noticing it and replying earlier.
> PulsePoint Bid Adapter: Doc update based on adapter updates

- prebid/prebidjsReleases.md
The prebid 8 release notes were missing from the release history page
> Add prebid 8 release notes

- dev-docs/bidders/yahooAdvertising.md
Rebrand to Yahoo Advertising (`yahooAds` bidder code), whilst still maintaining support for the legacy `yahoossp` alias.
Associated PRs
- https://github.com/prebid/Prebid.js/pull/10125
- https://github.com/prebid/prebid-server/pull/2826
- https://github.com/prebid/prebid-server-java/pull/2412
> Yahoo bid adapter rebrand documentation

- dev-docs/bidders/vox.md
> vox adapter add support schain, userid, floors module

- dev-docs/bidder-adaptor.md
Update the guide for new adapters to reflect TID changes in v8 
See: [v8 release notes](https://docs.prebid.org/dev-docs/pb8-notes.html#transaction-identifiers-are-now-reliable-and-opt-in), and https://github.com/prebid/Prebid.js/issues/10260
> PBJS: update new adapter guide with v8 changes regarding TIDs

- dev-docs/bidders/imds.md
We received a bug report from a publisher attempting to use the VAST redirect in GAM.
We've updated the documentation here to fix the issue.
> imds: Update VAST url macros based upon publisher bug report

- dev-docs/activity-controls.md
There was an invalid backtick and `find` returns the actual element and not a `boolean`, which vanilla javascript is okay with, but not typescript if properly typed.
> Improve activity control examples

- dev-docs/bidders/beachfront.md
Adds GPP support to the Beachfront Bid Adapter
> Add GPP support to Beachfront doc

- dev-docs/bidders/adocean.md
AdOcean:
- add gvl_id and set tcfeu_supported to true
- add Prebid Server parameters to reflect changes in: https://github.com/prebid/prebid-server/pull/2910
> AdOcean: add gvl_id and Prebid Server parameters

- dev-docs/bidders/pubmatic.md
Issue - https://github.com/prebid/Prebid.js/issues/9676 
PR - https://github.com/prebid/Prebid.js/pull/10371
> PubMaticBidAdapter - Updated bidder parameters document for lat & lon

- dev-docs/bidders/preciso.md
>  New Bidder Doc: Preciso bidder doc added

- dev-docs/bidders/huaweiads.md
The old support address (hwads@huawei.com) has been changed. The new address is prebid@huawei.com.
> Huawei Ads: Update huaweiads.md

- _data/sidebar.yml
- prebid-server/developers/add-a-privacy-module-java.md
- prebid-server/developers/add-a-privacy-module.md
- prebid-server/features/pbs-activitycontrols.md
> Add `Adding a Java Privacy Module` section.

- dev-docs/modules/userid-submodules/euid.md
- dev-docs/modules/userid-submodules/unified2.md
Added docs for the new EUID ID module, and made a tweak to the UID2 docs to match a new config option.
Prebid.js PR: https://github.com/prebid/Prebid.js/pull/9968 (I've marked this as a draft until the Prebid.js PR is merged).
> Draft: Add docs for EUID module.

- adops/gam-creative-banner-sbs.md
I believe this is still needed for the mobile PUC scenario. It was there for the Send-All-Bidders example, but missing for Sent-Top-Bid.
> adding mobileResize explanation

- dev-docs/bidders/pangle.md
> feat: update pangle md

- dev-docs/modules/userid-submodules/liveintent.md
This PR documents the newly introduced collector Ajax timeout.
> LiveIntent UserId module: Adjust ajax timeout doc

- dev-docs/bidders/adquery.md
Added `pbs:true`
https://github.com/prebid/prebid-server/pull/3020
> Adquery: added info about supporting pbs

- dev-docs/analytics/adagio.md
> AdagioAnalyticsAdapter: update doc

- prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md
PBS-GO has made a change in how tmax is utilized in auction endpoints. PR adds instructions to assist PBS-GO hosts in configuring their PBS settings to align with this updated usage of tmax.
> Update instruction for usage of tmax in PBS-GO

- dev-docs/bidders/integr8.md
Added an optional `deliveryUrl` parameter to the Integr8 Bid Adapter documentation, allowing users to specify a custom endpoint URL for bid requests.
This enhancement provides greater adaptability and paves the way for future customization, such as supporting different endpoints for various regions or environments. It maintains backward compatibility while offering users more control over their bidding strategies.
> Integr8 Bid Adapter: added optional parameter

- dev-docs/bidder-adaptor.md
> Replace remaining gpp_supported doc in bidder adaptor

- _includes/dev-docs/loads-external-javascript.md
- dev-docs/modules/a1MediaRtdProvider.md
- dev-docs/modules/aaxBlockmeterRtdProvider.md
- dev-docs/modules/arcspanRtdProvider.md
- dev-docs/modules/geoedgeRtdProvider.md
- dev-docs/modules/medianetRtdProvider.md
This adds a new include for modules that load external javascript.
Usage:
```liquid
{% include dev-docs/loads-external-javascript.md %}
```
> Replace load external js with include

- prebid-server/developers/add-new-bidder-go.md
This PR updates to reflect new way of aliasing a bid adapter in prebid server (go) along with an example.
> update docs to create an alias using new pattern

- dev-docs/bidders/adagio.md
https://github.com/prebid/Prebid.js/pull/10633
> Adagio: Add documentation for video player implementation

- .github/workflows/ci.yml
- guide.md
Getting started on how to contribute to the docs via codespaces. Fixes #4914
I have also these images. Should we add those as well?
> Add codespaces documentation

- dev-docs/publisher-api-reference/setConfig.md
Version 8 introduced a new `enableTIDs` config, which was mentioned in the release notes but never documented in proper place.
> pbjs: document `enableTIDs` config

- dev-docs/analytics/agma.md
Adds docs for the new [agma](https://www.agma-mmc.de/) adapter
> Added agma analytics adapter

- dev-docs/bidders/sparteo.md
The parameters of the bidder ere not up to date in the documentation.
The necessary changes have been done.
> Sparteo bid adapter: modify required fields and bidder parameters

- dev-docs/bidders/indiecue.md
> add indicue doc

- dev-docs/analytics/asteriobid.md
new bid adapter
https://github.com/prebid/Prebid.js/pull/10652
> AsterioBid Analytics adapter

- dev-docs/bidders/nextMillennium.md
> OpenRTB 2.5 supported parameters

- identity/sharedid.md
I stumbled upon an issue integrating the SharedID module. For some reason the first party endpoint was not extending cookies that had been set previously. I dug through the source to discover that, while `extend` defaults to `true` in the CDN script, it defaults to `false` in the module.
This PR adds a configuration table with possible options and defaults for the module.
> Updated sharedID: include module configuration

- dev-docs/publisher-api-reference/getEvents.md
- Add a new event in the listing of all events
- fix issue with the table
> add event bidAccepted in event slisting

- dev-docs/bidders/indiecue.md
Indicue is in process of obtaining their own vendor id, 410 would not be a correct one here, since all ad serving and cookies are with Indicue infrastructure.
They want to have this field empty, until the submission of the proper GVL ID.
But it see that all aliases now contain some kind of "inherited" id in docs, started from here
#4725 
@bretg is it possible to merge?
> rm gvl id text

- dev-docs/modules/userid-submodules/pair.md
Remove the `_custom` string in pair examples, as according to LiveRamp's feedback, it's confusing to some users.
> Update pair.md to remove `_custom` string in examples

- _layouts/bidder.html
- dev-docs/bidder-adaptor.md
- dev-docs/pbs-bidders.md
- prebid-server/developers/add-new-bidder-go.md
- prebid-server/developers/add-new-bidder-java.md
Bidders now can define if they support privacy sandbox features
> Fix #4987 - adds new privacy_sandbox meta field

- _data/sidebar.yml
- formats/video.md
The video format page didn't link out to the new video and the navbar highlight wasn't working because it linked out to PBJS-video.
> improve video links

- dev-docs/modules/fledgeForGpt.md
No linked PRs
With https://github.com/prebid/Prebid.js/pull/9794 PR, OpenX has moved their implementation to ORTB hence the existing link needs to be updated.
Also, RTBHouse link is updated to the master branch.
Considering the frequent updates made to bidder code, purposefully not referring to the code line numbers in the reference links.
> Update bidder implementation links in fledgeForGpt.md

- dev-docs/bidders/admixerwl.md
> Admixer Bid Adaper: add admixerwl alias

- dev-docs/bidders/relevantdigital.md
Update documentation for `relevantdigital` bid adapter to reflect that it now supports s2s and app.
https://github.com/prebid/prebid-server/pull/3216
https://github.com/prebid/Prebid.js/pull/10610
> relevantDigital: Add pbs documentation

- dev-docs/bidders/openwebxchange.md
- dev-docs/bidders/risexchange.md
- [x ] new bid adapter
- [ x] Related pull request: https://github.com/prebid/Prebid.js/pull/10956
> Rise Bid Adapter: add alias docs

- .github/workflows/ci.yml
- _includes/dev-docs/pbjs-adapter-required-for-pbs.md
- dev-docs/bidders/adtelligent.md
- dev-docs/bidders/adxcg.md
- dev-docs/bidders/connectad.md
- dev-docs/bidders/ix-server.md
- dev-docs/bidders/mediafuse.md
- dev-docs/bidders/openweb.md
- dev-docs/bidders/openx.md
- dev-docs/bidders/pubmatic.md
- dev-docs/bidders/pulsepoint.md
- dev-docs/bidders/trafficgate.md
Adds a disclaimer for bidders that require the client adapter in order to work server-side due to the `transformBidParams` function.
> Fix #5032 by adding a disclaimer to bidders

- dev-docs/modules/userid-submodules/criteo.md
Replaces https://github.com/prebid/prebid.github.io/pull/5097
> [Criteo] Remove deprecated instruction related to Criteo ID module

- dev-docs/modules/userid-submodules/growthcode.md
> GrowthCode User ID Module: Updated documentation to reflect changes to the user id module

- dev-docs/modules/consentManagementGpp.md
Adds bidders with `gpp_sids` to the https://docs.prebid.org/dev-docs/modules/consentManagementGpp.html list
> List bidders with gpp_sids support

- faq/prebid-mobile-faq.md
The FAQ entry that describes what a publisher can add to the application's Apple Privacy manifests to cover SDK behavior.
The related ticket: https://github.com/prebid/prebid-mobile-ios/issues/858
> Mobile: FAQ item for Apple Privacy maifest

- _data/sidebar.yml
- _includes/legal-warning.html
- dev-docs/activity-controls.md
- dev-docs/cmp-best-practices.md
- dev-docs/modules/consentManagement.md
- dev-docs/modules/consentManagementGpp.md
- dev-docs/modules/consentManagementUsp.md
- dev-docs/modules/gdprEnforcement.md
- dev-docs/modules/gppControl_usnat.md
- dev-docs/modules/gppControl_usstates.md
- features/ac-quebec.md
- features/mspa-usnat.md
- prebid-mobile/prebid-mobile-privacy-regulation.md
- prebid-server/endpoints/openrtb2/pbs-endpoint-video.md
- prebid-server/features/pbs-activitycontrols.md
- prebid-server/features/pbs-privacy.md
- prebid-server/features/pbs-uscustomlogic.md
- prebid-server/features/pbs-usgen.md
- support/index.md
- support/privacy-resources.md
Documentation for Privacy Sandbox per https://github.com/prebid/Prebid.js/issues/10932 and refactored several other privacy-related pages. Made the legal warning an include and shifted the location of privacy docs in the left nav.
> privacy resources page

- dev-docs/bidders/lucead.md
This PR adds the documentation of the Lucead Bid Adapter.
New Bid Adapter
> Add Lucead Adapter

- dev-docs/bidders/ix-server.md
- dev-docs/bidders/rixengine.md
> Add RixEngine bid adapter documentation

- dev-docs/modules/userid-submodules/33across.md
Add new configuration flag for first-party ID addressability.
> 33Across ID System: 1PID storage config flag

- prebid-server/developers/add-new-bidder-java.md
> Update add-new-bidder-java doc

- dev-docs/bidders/blockthrough.md
> Blockthrough Bid Adapter: initial release

- dev-docs/bidders/cwire.md
Updated `tcfeu_supported: true` in CWire's adapter docs.
> Cwire adapter: Update tcfeu_supported field (c-wire/support#117)

- features/firstPartyData.md
Document which first party data fields are automatically filled in by Prebid, with an example on how to turn them off.
Related: https://github.com/prebid/Prebid.js/issues/11184
> JS: document automatically collected first party data

- features/ac-quebec.md
as requested in https://github.com/prebid/prebid.github.io/issues/5170
> update quebec guidance

- dev-docs/bidders/adliveplus.md
- dev-docs/bidders/lucead.md
This PR adds the documentation of the Adlive Plus Bid Adapter.
This is an alias of the Lucead Bid Adapter.
New Bid Adapter
> New Bidder Adapter: Adlive Plus

- dev-docs/bidders/oms.md
Changed flag for support: TCF-EU, USP/CCPA, COPPA, GPP
> OMS Adapter: update documentation

- dev-docs/bidders/smrtconnect.md
- feat: add doc for smrtconnect md
> Smrtconnect Bid Adapter: initial release doc

- adops/creative-considerations.md
- adops/js-dynamic-creative.md
- dev-docs/modules/nativeRendering.md
- overview/prebid-universal-creative.md
Document new option to set up creatives with Prebid.js - https://github.com/prebid/Prebid.js/pull/10819
There are many references to PUC in native documentation that shoud, but did not, get updated:
https://docs.prebid.org/prebid/native-implementation.html
I am not sure on how to approach it because:
- the doc seem to assume that the only way to do native is to use Prebid.js. If that's true (I don't think it's supposed to be), the new approach is just better than PUC. I can't find an example on how to set up native creatives when using AMP/mobile SDKs.
- there's a lot of emphasis put on the `sendTargetingKeys` and `requestAllAssets` options. Those are irrelevant for the new approach. The first _may_ be relevant for AMP/mobile - again, I don't know if those work at all. The second is, to …
> Document JS dynamic creatives

- dev-docs/bidders/opsco.md
> Opsco Bid Adapter Documentation

- dev-docs/modules/jwplayerRtdProvider.md
This PR updates the JW Player RTD Module docs to include:
- new content fields populated in the ORTB request
- replaces the deprecate `playerID` param with `playerDivId`
https://github.com/prebid/Prebid.js/pull/11179
https://github.com/prebid/Prebid.js/pull/11178
> [JW Player RTD Module] Updates docs for new content fields and deprecated config param

- dev-docs/bidders/loyal.md
> Loyal Bid Adapter: initial release

- dev-docs/modules/fledgeForGpt.md
- dev-docs/modules/paapi.md
- dev-docs/publisher-api-reference/getPAAPIConfig.md
- dev-docs/publisher-api-reference/setPAAPIConfigForGPT.md
Prebid.js `paapi` and `fledgeForGpt` module doc updates - https://github.com/prebid/Prebid.js/pull/10930
> Prebid.js: new PAAPI module documentation

- adops/step-by-step.md
While running through the step by step creation of a vanilla Prebid set up, I found a potentially setup-breaking instruction (as it did indeed break my test up).
The instruction states to only change **Rotate creatives** to **Evenly** on line items, then the default settings are okay to use.
The default setting in the **Adjust delivery** for **Display creatives** is **All**, which broke my setup; by having 2 creatives attached to the line item with only one ad slot to serve into.  As per the **All** rule, the line item can only be selected if all creatives have an open ad slot to serve into.  
I believe the **All** setting would break most Prebid set ups, so I am just proposing adding **One or more** as a default step in these instructions to avoid that mistake.
- [X ] text edit only …
> Add additional instructions to line item creation steps in step-by-step section

- dev-docs/bidders/rubicon.md
the code for this was released a while back
> rubicon adapter: downgrade video.api to optional

- dev-docs/bidders/jwplayer.md
Adapter PR https://github.com/prebid/Prebid.js/pull/11344
> [New Bid Adapter] JW Player Bid Adapter

- dev-docs/bidders/criteo.md
The Criteo Prebid adapter supports the pubid field.
This field is required, so we need to add it to our documentation.
> [Criteo] Documentation pubid on Criteo Prebid Docs

- dev-docs/bidders/playdigo.md
> Playdigo: new adapter

- dev-docs/modules/idWardRtdProvider.md
Corrected link address in the idWardRtdProvider.md(deprecated module) to the anonymisedRtdProvider.md (updated module, that replaces the old one)
> Corrected link address in the idWardRtdProvider.md

- dev-docs/modules/adagioRtdProvider.md
related to https://github.com/prebid/Prebid.js/pull/11509
> Adagio Rtd Provider: add doc

- Gemfile
We started getting build errors for this repo yesterday when ffi released 1.17.0. It requires Ruby 3.0.
Tried this tying of the Gemfile to the previous version 1.16.3 in https://github.com/prebid/prebid.github.io/pull/5381 and it seemed to work.
> Update Gemfile for FFI version

- dev-docs/activity-controls.md
- dev-docs/add-rtd-submodule.md
- dev-docs/analytics/sharethrough.md
- dev-docs/bidder-adaptor.md
- dev-docs/bidders/aidem.md
- dev-docs/bidders/mediakeys.md
- dev-docs/cmp-best-practices.md
- dev-docs/faq.md
- dev-docs/integrate-with-the-prebid-analytics-api.md
- dev-docs/modules/azerionedgeRtdProvider.md
- dev-docs/modules/consentManagementGpp.md
- dev-docs/modules/consentManagementTcf.md
- dev-docs/modules/consentManagementUsp.md
- dev-docs/modules/gdprEnforcement.md
- dev-docs/modules/genericAnalyticsAdapter.md
- dev-docs/modules/permutiveRtdProvider.md
- dev-docs/modules/tcfControl.md
- dev-docs/modules/userId.md
- dev-docs/publisher-api-reference/aliasBidder.md
- dev-docs/publisher-api-reference/setConfig.md
- features/firstPartyData.md
- identity/sharedid.md
- prebid/prebidjs.md
- prebid/prebidjsReleases.md
- support/privacy-resources.md
https://github.com/prebid/Prebid.js/issues/10251:
- rename consentManagement to consentManagementTcf
- rename gdprEnforcement to TCF control
> Prebid 9: rename TCF modules

- dev-docs/modules/prebidServer.md
Update default s2SConfig.timeout for Prebid 9 - https://github.com/prebid/Prebid.js/issues/10989
> Prebid 9: PBS adapter: update docs timeout

- dev-docs/bidders/ringieraxelspringer.md
New version of https://github.com/prebid/prebid.github.io/pull/5383
Related to 9.0 PR https://github.com/prebid/Prebid.js/pull/11657
Note to @wsusrasp - there are many metadata fields missing from this file. Please see the documentation at https://docs.prebid.org/dev-docs/bidder-adaptor.html#submitting-your-adapter - the full list would look something like
```
tcfeu_supported: true/false
dsa_supported: true/false
gvl_id: none
usp_supported: true/false
coppa_supported: true/false
gpp_sids: tcfeu, tcfca, usnat, usstate_all, usp
schain_supported: true/false
dchain_supported: true/false
userId: (list of supported vendors)
media_types: banner, video, native
safeframes_ok: true/false
deals_supported: true/false
floors_supported: true/false
fpd_supported: true/false
pbjs: true/false
pbs: …
```
> ras rename

- dev-docs/bidders/improvedigital.md
- https://github.com/prebid/Prebid.js/pull/11067
**This should be merged into PB9 only**
Updated documentation for ImproveDigital bid adapter.
> Updated ImproveDigital bidder docs for PB9

- dev-docs/modules/dfpAdpod.md
- dev-docs/show-long-form-video-with-gam.md
https://github.com/prebid/Prebid.js/issues/10552
In prebid 9, the adpod portion of `dfpAdServerVideo` is being split out to a separate module, `dfpAdpod`.
I am not sure how adpod works or how to flesh this out more - there's only one reference to it that I can't get to work.
> Prebid 9: split dfpAdpod from dfpAdserverVideo

- dev-docs/modules/anPspParamsConverter.md
> Text Edit: Fixed the docs page where dataProviders in realTimeData was shown as an object but should be an array

- dev-docs/modules/userId.md
Id modules should always respect publisher configuration on storage type
> Update userId.md 

- dev-docs/modules/consentManagementGpp.md
There was still some outdated docs on `gpp_supported`, which is deprecated in favour of `gpp_sids`
> Update gpp documentation with new meta data field

- dev-docs/bidders/vox.md
Good day,
This PR updates docs for Vox adapter.
- add `pbs: true` flag
- add `displaySizes` parameter
Some time ago we added a Vox adapter for PrebidServer. ([Link](https://github.com/prebid/prebid-server/pull/2928)), but, i suppose, we forgot to update documentation on this particular repository.
Moreover, we are listed in **Prebid.js** bidders list([Link](https://docs.prebid.org/dev-docs/bidders/vox.html)), but we are not listed in **PrebidServer** bidders([Link](https://docs.prebid.org/dev-docs/pbs-bidders.html)), despite the fact that we added PrebidServer adapter about a year ago. 
As far, as i understand, this happened because we forgot to add `pbs:true` flag to this repository.
Pull Request in PrebidServer repository for Vox adapter: …
> Update docs for Vox adapter

- dev-docs/bidders/smaato.md
[Prebid.js](https://github.com/prebid/Prebid.js/pull/11789)
[Prebid-server](https://github.com/prebid/prebid-server/pull/3749)
> Update smaato.md to indicate DSA support

- dev-docs/modules/consentManagementTcf.md
Add `dsaPlaform` config flat to `consentManagementTcf` - https://github.com/prebid/Prebid.js/pull/11824
> consentManagementTcf: add DSA platform config

- dev-docs/modules/prebidServer.md
> Adding docs for customHeader suppor for XHR call to Preid Server

- dev-docs/bidmatic.md
> Bidmatic Bid Adapter: initial release

- dev-docs/bidders/adnuntius.md
Adds documentation for the new `advertiserTransparency` feature.
> Adnuntius Bid Adaptor: add new advertiserTransparency feature

- dev-docs/bidders/vidazoo.md
Added `pbs: true` to bidder functionality and updated the `pId` parameter description in the Vidazoo bidder documentation, specifying its use for pbjs only.
> Update Vidazoo bidder documentation

- dev-docs/conditional-ad-units.md
In Prebid 8 we moved "global sizeConfig" logic to a separate `sizeMapping` module.
Related: 
https://github.com/prebid/Prebid.js/issues/11911
> Update conditional ad unit - replace references to "global sizeConfig" with "size mapping"

- dev-docs/publisher-api-reference/setConfig.md
- features/timeouts.md
Remove references to the  `timeoutBuffer` config option, which was never respected and now completely unused.
https://github.com/prebid/Prebid.js/issues/11959
> JS: remove references to defunct timeoutBuffer config

- dev-docs/publisher-api-reference/setConfig.md
Discussed in prebid.js , the auctionDelay is optional. It's already documented in the table as optional, but not in the code example.
> auctionDelay is optional

- dev-docs/bidders/dailymotion.md
This PR keeps the Dailymotion bid adapter doc in sync with https://github.com/prebid/Prebid.js/pull/12068
> Dailymotion bid adapter: Add player name

- dev-docs/modules/tcfControl.md
- prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md
- prebid-server/features/pbs-privacy.md
- prebid/prebidjsReleases.md
wordsmithing to complete the relabeling of "GDPR Enforcement" to  "TCF Control" and generally soften "enforce" with "restrict". We haven't changed the actual config attributes, so that can't go all the way.
https://deploy-preview-5529--prebid-docs-preview.netlify.app/dev-docs/modules/tcfcontrol
> re-labeling tcf control module

- dev-docs/bidders/1accord.md
> 1accord bid adapter - 1accord to 1Accord

- dev-docs/analytics/intentiq.md
Currently, when the Intent IQ Analytics Adapter is selected on Prebid Download page, the build gives an error. The reason is that the module code in the documentation (intentiq) does not match the file name for the adapter in Prebid.js main repo (intent**I**qAnalyticsAdapter.js)
> Intent IQ Analytics Adapter: Update Module Code

- dev-docs/bidders/mediaConsortium.md
https://github.com/prebid/Prebid.js/pull/11892
> New bidder Adapter - MediaConsortium

- prebid-server/pbs-modules/greenbids-analytics-reporter.md
We want to add the description of the new PBS Greenbids Analytics Reporter
- https://github.com/prebid/prebid-server-java/pull/3096
> Add description of PBS Greenbids Analytics Reporter

- _data/sidebar.yml
The link is better, but the destination isn't all that useful at this point.
> Fixed native example in sidebar

- dev-docs/bidders/appnexus.md
This PR updates some available values in the AppNexus bidders param page, as well as add a section about the interaction between `bid.params.video` and `mediaTypes.video` objects.
> AppNexus bidders page - update and clarify video params

- dev-docs/bidders/criteo.md
> [Criteo] Deprecation of the nativeCallback parameter

- dev-docs/bidders/escalax.md
> New Adapter: Escalax

- dev-docs/modules/targetVideo_video.md
> Target video module download docs

- dev-docs/modules/userid-submodules/utiq.md
This is directly from the [utiq docs on programmatic integeration](docs.utiq.com/docs/programmatic-integration), which has a bug - `utiq` is used as a vendor exception, but it should have been `utiqId`.
> Add tcf configuration information to utiq

- dev-docs/modules/symitriDapRtdProvider.md
https://github.com/prebid/Prebid.js/pull/12214
> symitriDapRtdProvider: describe changes required to support different types of user identifiers and trigger pixel on winning bid.

- .devcontainer/devcontainer.json
- guide.md
This adds a `.devcontainer.json`, which will setup a fully functional devcontainer if you use VSCode or Github Codespaces.
- Image being used https://hub.docker.com/r/microsoft/devcontainers-jekyll ([source code](https://github.com/devcontainers/images/tree/main/src/jekyll/.devcontainer))
- vscode customization docs: https://containers.dev/supporting#visual-studio-code
- how to setup a devcontainer: https://code.visualstudio.com/docs/devcontainers/create-dev-container
- custom dev container config: https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers#creating-a-custom-dev-container-configuration
> Add-devcontainer

- prebid/prebidjs-flow-video.md
added a link to professor prebid where it is mentioned
> Prebidjs Basic Impression Flow : add link for prof prebid

- prebid-mobile/pbm-api/android/pbm-targeting-params-android.md
- prebid-mobile/pbm-api/ios/pbm-targeting-ios.md
Resolves https://github.com/prebid/prebid.github.io/issues/5547
> Update PBSDK to add UID2 reference

- dev-docs/bidders/sparteo.md
Hi!
This doc update fixes the docs of the Sparteo Bid Adapter & add existing parameters which are already available.
This is the PR in Prebid.js: https://github.com/prebid/Prebid.js/pull/12321
This is the bid adapter if needed: https://github.com/prebid/Prebid.js/blob/master/modules/sparteoBidAdapter.js
Thank you :-)
> Sparteo Bid Adapter: Update Docs

- dev-docs/bidders/ads_interactive.md
> New adapter: Ads Interactive

- dev-docs/bidders/stroeerCore.md
> StroeerCore Bid Adapter: add optional 'sfp' param

- dev-docs/publisher-api-reference/aliasBidder.md
[https://github.com/prebid/Prebid.js/pull/12247](https://github.com/prebid/Prebid.js/pull/12247)
> useBaseGvlid added to aliasBidder

- dev-docs/bidders/adhese.md
> [Adhese] Document pbs ext parameters

- prebid-video/video-module/integration-examples/adplayerpro.html
> AdPlayer.Pro video module: fix integration example

- dev-docs/modules/wurflRtdProvider.md
This commit adds the integration notes section and also includes some wording edits in the documentation.
> WURFL Rtd Provider: add integration notes

- dev-docs/bidders/showheroes-bs.md
> update showheroes docs

- dev-docs/bidders/contxtful.md
This PR describes the new Contxtful Bid Adapter.
Related Bid Adapter PR: https://github.com/prebid/Prebid.js/pull/12256
> Contxtful Bidder adapter: New Documentation

- prebid-server/developers/add-a-module-go.md
- prebid-server/developers/add-new-bidder-go.md
- prebid-server/endpoints/info/pbs-endpoint-info.md
Documentation updates to reflect changes in PBS-Go v3.0.0. Also adds a missing reference to DOOH.
> PBS-Go V3 Updates

- dev-docs/modules/airgridRtdProvider.md
Update RTDModule_AirGrid documentation :params.apiKey should be a String and not a Boolean
@ydennisy as an FYI
> Change params.apiKey to set it as string instead of boolean

- dev-docs/bidders/gothamads.md
Bidders cannot claim tcfeu support without a GVLID
Can't find a reference to a GVLID for them in the adapters.
> gothamads doc to turn off tcfeu_supported flag

- prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md
Docs PR for https://github.com/prebid/prebid-server/issues/2085
> PBS flexible bidadjustments

- dev-docs/modules/paapi.md
Documentation for https://github.com/prebid/Prebid.js/pull/12205
> paapi: support for parallel PAAPI and contextual auctions

- dev-docs/publisher-api-reference/markWinningBidAsUsed.md
- dev-docs/show-outstream-video-ads.md
Update documentation for two related features:
- publisher-defined renderers can now omit `url` - https://github.com/prebid/Prebid.js/pull/12426
- `markWinningBidAsUsed` can now trigger `bidWon` - https://github.com/prebid/Prebid.js/pull/12437
> JS: update documentation for markWinningBidAsUsed/renderer

- dev-docs/modules/userId.md
- dev-docs/modules/userid-submodules/rewardedInterest.md
> New User ID submodule: Rewarded Interest

- dev-docs/bidders/bidtheatre.md
> Bidtheatre Bidder Adapter: initial release, docs

- dev-docs/modules/index.md
> Fix userId module link

- dev-docs/bidders/ttd.md
Going forward ttd wants publishers to send video.plcmt instead of video.placement.
We still except video.placement, but want to only mention video.plcmt in our docs
> update placement to plcmt

- dev-docs/bidders/kuantyx.md
Documenting https://github.com/prebid/Prebid.js/pull/12523
> Aso Bid Adapter: documenting kuantyx alias

- prebid-server/pbs-modules/index.md
> Module Execution Config

- dev-docs/bidders/beop.md
Explain why BeOp Bid Adapter now request access to publisher Storage
> BeOp Adapter doc: Access storage explained

- prebid-server/developers/add-a-module-java.md
- prebid-server/pbs-modules/greenbids-real-time-data.md
- prebid-server/pbs-modules/index.md
> Module Configuration Documentation

- dev-docs/bidders/freedomadnetwork.md
Since the filename differs, needed to be updated here following the new feature added on [this PR](https://github.com/prebid/prebid.github.io/pull/4186)
> Added filename for freedomadnetwork.md

- _includes/mobile/adunit-config-android.md
- _includes/mobile/adunit-config-ios.md
- _includes/mobile/rendering-adunit-config-android.md
- _includes/mobile/rendering-adunit-config-ios.md
- prebid-mobile/modules/rendering/android-sdk-integration-admob.md
- prebid-mobile/modules/rendering/android-sdk-integration-gam.md
- prebid-mobile/modules/rendering/android-sdk-integration-max.md
- prebid-mobile/modules/rendering/android-sdk-integration-pb.md
- prebid-mobile/modules/rendering/ios-sdk-integration-admob.md
- prebid-mobile/modules/rendering/ios-sdk-integration-gam.md
- prebid-mobile/modules/rendering/ios-sdk-integration-max.md
- prebid-mobile/modules/rendering/ios-sdk-integration-pb.md
The issue in the mobile repo: https://github.com/prebid/prebid-mobile-ios/issues/1065
> Mobile: Add section about ad position configuration

- _includes/mobile/adunit-config-android.md
- _includes/mobile/adunit-config-ios.md
- prebid-mobile/pbm-api/android/pbm-targeting-android.md
- prebid-mobile/pbm-api/ios/pbm-targeting-ios.md
> Mobile: update docs for setORTB functions

- _includes/mobile/adunit-config-android.md
- _includes/mobile/adunit-config-ios.md
- prebid-mobile/pbm-api/android/pbm-targeting-android.md
- prebid-mobile/pbm-api/ios/pbm-targeting-ios.md
> Mobile: fix the release version of the setOrtb feature

- dev-docs/bidders/urekamedia.md
> Adkernel: documenting UrekaMedia alias

- dev-docs/bidders/smartadserver.md
Indicate how we are handling multi format. Related to 
- https://github.com/prebid/prebid-server/pull/4045
> Equativ: multiformat_supported, will-bid-on-any

- dev-docs/bidders/greenbids.md
> Doc for greebids adapter

- dev-docs/modules/userid-submodules/33across.md
> 33Across ID System: Add hem optional parameter

- dev-docs/bidders/escalax.md
> Escalax: add prebid.js bid parameters

- dev-docs/modules/floors.md
Fixed the code example for configuring impression-level floor min in the floors documentation.
> Bug: Update the code for ortb2Imp for setting floorMin

- dev-docs/bidders/openx.md
After adding native support to all of the OpenX bidder adapter, we want to update the docs with native support.
Prebid.js - https://github.com/prebid/Prebid.js/pull/12625
prebid-server-java - https://github.com/prebid/prebid-server-java/pull/3649
prebid-server - https://github.com/prebid/prebid-server/pull/4144
> OpenX Bid Adapter: Native support

- prebid-server/features/pbs-floors.md
Added doc reference to max-schema-dims and highlighted the distinction between Java and Go config values.
> PBS Floors updates

- features/pbAdSlot.md
This alters the indenting on the pbAdSlot examples to match the actual nesting of the structure.
> Fix indenting on pbAdSlot examples

- dev-docs/bidders/connektai.md
PBS PR: https://github.com/prebid/prebid-server/pull/4149
> New adapter docs: Connektai

- dev-docs/bidders/kobler.md
> Extend Kobler adapter with prebid-server

- dev-docs/modules/permutiveRtdProvider.md
- dev-docs/modules/tcfControl.md
- dev-docs/modules/userid-submodules/utiq.md
We had a publisher who wanted to make a vendorException for Utiq with the rationale that "Prebid says it's ok because it's in the docs". That's incorrect. Vendors can ask for exceptions, but it has to be completely clear that Prebid is not condoning their exception.
> added vendor exception disclaimer

- dev-docs/bidders/caroda.md
- dev-docs/bidders/freedomadnetwork.md
> Remove invalid multiformat support declaration

- prebid-server/pbs-modules/greenbids-analytics-reporter.md
- prebid-server/pbs-modules/greenbids-real-time-data.md
We add extraction of modules params from account level config for both RTD module and analytics reporter. At the same time if the params are defined in BidRequestExt it should take precedent before account level config.
> Greenbids RTD: Account config docs

- dev-docs/modules/userid-submodules/intentiq.md
> IntentIq ID & Analytics Modules: GAM reporting documentation

- dev-docs/bidders/michao.md
https://github.com/prebid/Prebid.js/pull/12507
> New Bidder: Michao

- dev-docs/bidders/addigi.md
Prebid.js PR: https://github.com/prebid/Prebid.js/pull/12697
Prebid server PR: https://github.com/prebid/prebid-server/pull/4176
> Attekmi: add Addigi adapter

- prebid-mobile/pbm-api/ios/pbm-plugin-renderer.md
> Mobile: Update plugin renderer section

- dev-docs/bidders/bms.md
> feat: Add BMS documentation

- dev-docs/bidders/vdoai.md
> updated vdo.ai bidder adapter documentation according to the new server

- dev-docs/modules/userid-submodules/permutiveIdentityManagerIdSystem.md
[Prebid.js PR](https://github.com/prebid/Prebid.js/pull/12337)
This PR adds documentation for a new userId submodule, `permutiveIdentityManagerIdSystem`, which supports Permutive customers in using Permutive's Identity Manager product.
> add permutiveIdentityManagerIdSystem docs

- prebid-server/features/pbs-usgen.md
Adding allowPersonalDataConsent2 option
> PBS USGen doc update

- dev-docs/adunit-reference.md
- dev-docs/modules/floors.md
- prebid-server/features/pbs-floors.md
We've been getting support issues where people are using `floorsMin` as a way to set static floors. This doesn't work.
> documenting static floors

- dev-docs/modules/anonymisedRtdProvider.md
> anonymisedRtdProvider: can load Anonymised Marketing Tag external script

- _includes/dev-docs/vendor-exception.md
- dev-docs/modules/permutiveRtdProvider.md
- dev-docs/modules/tcfControl.md
- dev-docs/modules/userid-submodules/utiq.md
- guide.md
This creates a separate include for the vendor exception warning added in #5862 by @bretg
> Add vendor-exceptions include

- dev-docs/modules/previousAuctionInfo.md
- dev-docs/publisher-api-reference/setConfig.md
- Documentation for the new Previous Auction Info module
Relative links
- PR: https://github.com/prebid/Prebid.js/pull/11086
- GH Issue: https://github.com/prebid/Prebid.js/issues/10788
> added docs for the prev auction info module

- prebid-server/pbs-modules/index.md
> PBS module page update

- dev-docs/publisher-api-reference/setConfig.md
- [https://github.com/prebid/Prebid.js/pull/12598](https://github.com/prebid/Prebid.js/pull/12598)
> Add local way of caching VAST XML

- dev-docs/analytics/uniquest.md
- dev-docs/bidders/uniquest.md
> UNIQUEST Bid Adapter: initial release

- dev-docs/modules/userid-submodules/open-pair.md
PreBid PR: https://github.com/prebid/Prebid.js/pull/12599
> PAIR: adds TechLab version documentation

- dev-docs/publisher-api-reference/setConfig.md
> Local cache version fix

- overview/analytics.md
Redesign the analytics homepage using the bidder homepage as a reference :
- Introduce a search bar for analytics modules.
- Organize analytics modules in alphabetical order.
- Dedicated page for each module with redirection functionality.
Related to issue : https://github.com/prebid/prebid.github.io/issues/5359
- [X ] text edit only (wording, typos)
> Update Analytic Page based on bidder page

- dev-docs/modules/optableRtdProvider.md
Optable RTD submodule enriches the OpenRTB request by populating user.ext.eids and user.ext.data using an identity graph and audience segmentation service hosted by Optable on behalf of the publisher. This RTD submodule primarily relies on the Optable bundle loaded on the page, which leverages the Optable-specific Visitor ID and other PPIDs to interact with the identity graph, enriching the bid request with additional user IDs and audience data.
> New RTD submodule: optableRtdProvider

- dev-docs/bidders/adgrid.md
> Adgrid new param placement

- _includes/mobile/adunit-config-ios.md
References in PrebidMobile iOS repo:
- https://github.com/prebid/prebid-mobile-ios/issues/1085
- https://github.com/prebid/prebid-mobile-ios/issues/1104
> Mobile: Support SKAdNetwork and SKOverlay in Bidding-only scenario

- dev-docs/renderer.md
Problem: useless table because of unescaped `|` in text.
> Fix typo in renderer.md

- dev-docs/modules/previousAuctionInfo.md
- added information to the previous auction info module about the new highestBidCurrency field that is now being collected in previous auction info payloads
> updated prev auct info docs to include the new highestBidCurrency field

- dev-docs/bidders/adipolo.md
> add adipolo Adapter

- dev-docs/publisher-api-reference/setConfig.md
> Add documentation for targetingControl.allBidsCustomTargeting

- dev-docs/bidders/mobkoi.md
PBS PR here: https://github.com/prebid/prebid-server/pull/4240
> mobkoi: add pbs support

- dev-docs/bidders/epomDspBidAdapter.md
> Added documentation for epomDspBidAdapter

- dev-docs/pbs-bidders.md
Solves issue https://github.com/prebid/prebid.github.io/issues/4352
The overly-long PBS bidders page may be a cause for why the Algolia crawler results aren't working properly anymore.
> One PBS bidder to a page

- dev-docs/bidder-adaptor.md
- dev-docs/bidders/pubmatic.md
- dev-docs/publisher-api-reference/bidderSettings.md
Adds documentation for the PBJS endpointCompression bidderSettings feature.  This feature allows Publishers to optionally enables bid requests to be Gzip compressed before being sent out to bid adapter endpoints.
GH Issue: https://github.com/prebid/Prebid.js/issues/12973
PR: https://github.com/prebid/Prebid.js/pull/13033
> docs for gzip support for bid requests

- dev-docs/bidder-adaptor.md
- minor text updates to the gzip compression documentation
GH Issue: https://github.com/prebid/Prebid.js/issues/12973
PR: https://github.com/prebid/Prebid.js/pull/13033
> updated gzip doc text

- dev-docs/bidder-adaptor.md
- added a few more minor text updates to the gzip compression documentation
GH Issue: https://github.com/prebid/Prebid.js/issues/12973
PR: https://github.com/prebid/Prebid.js/pull/13033
> updated gzip docs to add a few more details

- dev-docs/analytics/adnuntius.md
Related pull request: https://github.com/prebid/Prebid.js/pull/12496
> Adnuntius Analytics Adapter: Adds documentation for the new Adnuntius Analytics Adapter

- dev-docs/modules/prebidServer.md
documents https://github.com/prebid/Prebid.js/pull/13061
> Update prebidServer.md: routing to multiple pbs instances

- dev-docs/modules/floors.md
> docs: clarify imp-level floorMin location

- prebid-mobile/modules/rendering/android-sdk-integration-gam-native.md
- prebid-mobile/modules/rendering/ios-sdk-integration-gam-native.md
- prebid-mobile/modules/rendering/rendering-deeplinkplus.md
- prebid-mobile/pbm-api/android/pbm-util-android.md
- prebid-mobile/pbm-api/ios/code-integration-ios.md
- prebid-mobile/pbm-api/ios/pbm-util-ios.md
- prebid-mobile/prebid-mobile-privacy-regulation.md
> docs(prebid-mobile): fix markdownlint issues

- prebid/native-implementation-legacy.md
- prebid/prebidjsReleases.md
> Fix markdown lint issues

- dev-docs/bidders/33across.md
- dev-docs/bidders/mediago.md
codex found additional undocumented param
https://github.com/prebid/Prebid.js/blob/da76d8f9cf2defa1517f9be2883395325e8bc5ca/modules/mediagoBidAdapter.js#L179C30-L179C46
https://github.com/prebid/Prebid.js/blob/da76d8f9cf2defa1517f9be2883395325e8bc5ca/modules/33acrossBidAdapter.js#L251
> docs: document additional bidder params

- dev-docs/modules/arcspanRtdProvider.md
- dev-docs/modules/categoryTranslation.md
- dev-docs/modules/confiantRtdProvider.md
- dev-docs/modules/dsaControl.md
- dev-docs/modules/freewheel.md
- dev-docs/modules/mediafilterRtdProvider.md
this one is not as interesting, as it just made tables for already documented params in the examples
> docs: add parameter tables for several modules

- dev-docs/modules/intersectionRtdProvider.md
- dev-docs/modules/userid-submodules/unified.md
- dev-docs/modules/userid-submodules/yandex.md
- identity/sharedid.md
> Misc modules: Document additional module parameters

- dev-docs/bidders/startio.md
https://github.com/prebid/prebid-server/pull/4324
https://github.com/prebid/prebid-server-java/pull/3941
https://github.com/prebid/Prebid.js/pull/13048
> New Adapter: Start.io

- dev-docs/modules/userid-submodules/liveintent.md
Remove documentation asking clients not to cache things in storage
> LiveIntent UserId module: Remove outdated line

- dev-docs/bidders/condorx.md
Added support for bid floor + support openRTB requests and responses
> add support to bidfloor + open RTB

- dev-docs/bidders/eclick.md
- dev-docs/bidders/eclickads.md
-> https://github.com/prebid/Prebid.js/pull/12145
This commit does nothing but change the bidder name from `EClickAds` to `eClick` (also `bidderCode` from  `eclickads` to `eclick`)
> EClickAds: rename bidder from EClickAds to eClick

- dev-docs/pb10-notes.md
- dev-docs/release-notes.md
documents https://github.com/prebid/Prebid.js/pull/13253
> Prebid 10 release notes

- dev-docs/modules/userid-submodules/utiqMtp.md
> add text on UtiqMtp ID configuration, add row on table for bidders

- dev-docs/modules/storageControl.md
First draft of docs for new storageControl module - https://github.com/prebid/Prebid.js/pull/13419
> PBJS: new storageControl module docs

- dev-docs/bidders/nextMillennium.md
Only ONE of `placement_id` or `group_id` is required.
Changed `placement_id` to state "optional" so it is less confusing (there is already a note after the table stating that one of them is required)
> Update nextMillennium.md: placement_id to optional

- dev-docs/modules/cleanioRtdProvider.md
- dev-docs/modules/humansecurityMalvDefenseRtdProvider.md
Submitting update HUMAN Security Malv Defense RTD Submodule documentation alongside the submodule.
In 2022, HUMAN Security acquired the Clean.io project ([link](https://www.humansecurity.com/newsroom/human-acquires-anti-malvertising-leader-cleanio-to-enhance-protection-across-the-media-ecosystem/)). This PR introduces the `humansecurityMalvDefenseRtdModule` as a replacement for `cleanioRtdModule`, with minimal changes aside from naming and CDN links.
`cleanioRtdModule` module is maintained for backward compatibility until the next major Prebid release.
> humansecurityMalvDefense Rtd Provider: replacement for cleanioRtdProvider

- dev-docs/bidders/tadvertising.md
> T Advertising Solutions Bid Adapter: initial release

- dev-docs/bidders/onetag.md
Updated Multi Format Support field to "will-bid-on-any" value, in order to reflect backend bidding type.
> Updated Multi Format Support field

- dev-docs/bidders/ttd.md
https://github.com/prebid/Prebid.js/pull/13612
> TTD Bid Adapter: add documentation about custom bidder endpoint

- _includes/video/pb-is-jw01.html
- _includes/video/pb-is-jw02.html
- _includes/video/pb-is-vjs.html
- _includes/video/pb-lf-fw.html
- adops/setting-up-prebid-video-in-freewheel.md
- assets/js/video/pb-ve-jwplayer-platform-h.js
- dev-docs/bidders/adklip.md
- dev-docs/bidders/aso.md
- dev-docs/bidders/bcmint.md
- dev-docs/bidders/bidgency.md
- dev-docs/bidders/consumable-server.md
- dev-docs/bidders/consumable.md
- dev-docs/bidders/cordless.md
- dev-docs/bidders/epsilon.md
- dev-docs/bidders/kuantyx.md
- dev-docs/bidders/pubmatic.md
- dev-docs/bidders/showheroes-bs.md
- dev-docs/bidders/visx.md
- dev-docs/plugins/bc/bc-prebid-plugin-api.md
- dev-docs/plugins/bc/bc-prebid-plugin-integration-studio.md
- dev-docs/plugins/bc/bc-prebid-plugin-multiad-options.md
- dev-docs/plugins/bc/bc-prebid-plugin-sample-studio-integration-general-method.md
- examples/video/instream/jwplayer/pb-ve-jwplayer-hosted.html
- examples/video/instream/jwplayer/pb-ve-jwplayer-platform.html
- examples/video/instream/videoModule/videojs/video-module-videojs.html
- examples/video/instream/videojs/pb-ve-videojs.html
- examples/video/long-form/long-form-video-with-freewheel.html
Replacing remaining documentation references to Appnexus-hosted Prebid Cache with generic examples.
> Appnexus cache-reference-cleanup

- dev-docs/bidders/adklip.md
This change documents a new, optional bid parameter in the Sharethrough bid adapter.
> Sharethrough Bid Adapter: add new optional bid param to documentation

- dev-docs/publisher-api-reference/setConfig.md
Documentation for https://github.com/prebid/Prebid.js/pull/13722
> Document targetingControls.lock

- dev-docs/bidders/oprx.md
> adunit format added

- dev-docs/bidder-adaptor.md
- dev-docs/publisher-api-reference/setConfig.md
- features/firstPartyData.md
https://github.com/prebid/Prebid.js/pull/13800
> Update TIDs for pr that made them bidder specific
