dev-docs/bidders/bedigitech.md

BEdigitech Bid Adapter: New Adapter 

---

prebid-server/features/pbs-storedreqs-java.md
prebid-server/hosting/pbs-database.md

Updated PBS-database AMP, stored requests query

---

dev-docs/analytics/pubmatic.md

- Adding the PubMatic Analytics module to the PBJS download page

Adding the PubMatic Analytics module to the PBJS download page

---

prebid-mobile/pbm-api/android/code-integration-android.md
prebid-mobile/pbm-api/ios/code-integration-ios.md

mobile: updates for sdk configuration flow

---

dev-docs/bidders/ix-server.md

Updated bid request limit note
- [ x] text edit only (wording, typos)

Updated Index's PBS docs

---

dev-docs/bidders/ix.md

Updated bid request limit, added AdUnit-specific data to the FPD module and rearranged the section.
- [yes ] text edit only (wording, typos)
- [yes ] new examples

updated Index's Prebid.js docs

---

_includes/footer.html

Reverts prebid/prebid.github.io#4441
This only works for users that previously gave consent.

Revert "Support consent mode for google analytics"

---

_includes/footer.html
_includes/head--common.html

Loading google analytics only if consent is given

Respect consent for google analytics

---

dev-docs/bidders/ix.md

Updated the version number for ad-unit FPD

IX adapter: Updated the version number for ad-unit FPD

---

dev-docs/bidders/rhythmone.md

deprecating rhythmone

---

dev-docs/bidders/adrino.md

Adrino Bid Adapter: banner support added

---

dev-docs/bidders/trustxstandalone.md

Added explanation for legacy doc

TrustX: update legacy doc

---

features/pbAdSlot.md

Per https://github.com/prebid/prebid.github.io/issues/4511

GPID: clarifying when gpt-pre-auction can be used

---

prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md

native is supported per https://github.com/prebid/prebid-server/issues/857

PBS auction endpoint price granularity

---

dev-docs/modules/userid-submodules/pair.md

Provide documentation for PAIR ID userId submodule, the corresponding PR: https://github.com/prebid/Prebid.js/pull/9662

add documentation for PAIR ID userid submodule

---

_layouts/home.html
dev-docs/adunit-reference.md
overview/all-videos.md
overview/intro-to-header-bidding-video.md
overview/intro-to-header-bidding.md
overview/intro-video.md
overview/intro.md
prebid-mobile/prebid-mobile-video.md
prebid-mobile/prebid-mobile.md
prebid-server/overview/prebid-server-overview-video.md
prebid-server/overview/prebid-server-overview.md
prebid/prebidjs-video.md
prebid/prebidjs.md

integrated training videos 1.1 through 1.5.
Previews available at:
- [/overview/intro-to-header-bidding.html](https://deploy-preview-4516--prebid-docs-preview.netlify.app/overview/intro-to-header-bidding.html)
- [/overview/intro.html](https://deploy-preview-4516--prebid-docs-preview.netlify.app/overview/intro.html)
- [/prebid/prebidjs.html](https://deploy-preview-4516--prebid-docs-preview.netlify.app/prebid/prebidjs.html)
- [/prebid-mobile/prebid-mobile.html](https://deploy-preview-4516--prebid-docs-preview.netlify.app/prebid-mobile/prebid-mobile.html)
- [prebid-server/overview/prebid-server-overview.html](https://deploy-preview-4516--prebid-docs-preview.netlify.app/prebid-server/overview/prebid-server-overview.html)

first batch of intro videos

---

dev-docs/bidders/relevantdigital.md

New Adapter: Relevant Digital

---

dev-docs/bidders/freewheelssp.md

FreeWheel SSP Adapter: add gpp_supported

---

dev-docs/bidders/emx_digital.md

driven by emx's PBS usersync URL creating 404 in browsers

Flagging emx_digital as deprecated

---

dev-docs/bidders/axonix.md

Another problem with this adapter doc is that the `type` field is missing.

axonix param table formatting

---

dev-docs/publisher-api-reference/bidderSettings.md

Added docs for the adjustAlternateBids bidderSettings functionality.
Related PR: https://github.com/prebid/Prebid.js/pull/9609

Documentation for the adjustAlternateBids bidderSettings Functionality

---

dev-docs/bidders/frvradn.md

FRVR Ad Network Adapter
Related pull requests in prebid.js or server are linked
- https://github.com/prebid/prebid.github.io/pull/4515

New Adapter: FRVR Ad Network

---

dev-docs/bidders/deepintent.md

Deep Intent : update dev docs to include tagId in video example

---

dev-docs/adunit-reference.md
dev-docs/bidder-adaptor.md
dev-docs/publisher-api-reference/triggerBilling.md
features/InterstitialAds.md

This PR provides documentation for the new optional billing deferral functionality as outlined here: https://github.com/prebid/Prebid.js/issues/4494#issuecomment-1412487621
Related PR: https://github.com/prebid/Prebid.js/pull/9640

Documentation for Billing Deferral

---

dev-docs/bidders/adtrgtme.md

Added siteID bid parameter.
- https://github.com/prebid/prebid-server/pull/2637#event-8861607049

adtrgtme: update adapter params

---

dev-docs/bidder-adaptor.md
dev-docs/publisher-api-reference/triggerBilling.md
features/InterstitialAds.md

This PR relates to https://github.com/prebid/prebid.github.io/pull/4546 and provides a correction around the new documentation for Billing Deferral

Fix for defer billing docs

---

dev-docs/modules/userid-submodules/unified2.md

-[x] text edit only (wording, typos). Minor mods to wording and formatting + one link update.
No related PR just this one. Mods have been pre-reviewed.

Edits to the Unified ID 2.0 page

---

dev-docs/bidders/adsyield.md

New adapter: Adsyield

---

dev-docs/bidders/silverpush.md

added silverpush adapter docs

---

dev-docs/modules/userid-submodules/liveintent.md

Add documentation for distributorId configuration

---

dev-docs/bidders/projectagora.md

New adapter: Project Agora

---

dev-docs/modules/userid-submodules/intentiq.md

IntentIQ: added enableCookieStorage optional parameter docs

---

dev-docs/bidders/smaato.md

Update bid adapter
Related pull requests in prebid-server -> [PR](https://github.com/prebid/prebid-server/pull/2770)

Smaato: Add skadn note for AdPods

---

dev-docs/modules/userid-submodules/pair.md

Fix a typo in pair.md

---

dev-docs/bidders/rtbhouse.md

Please reach us at [inventory_support@rtbhouse.com](mailto:inventory_support@rtbhouse.com) with [piotr.jaworski@rtbhouse.com](mailto:piotr.jaworski@rtbhouse.com) and cc [leandro.otani@rtbhouse.com](mailto:leandro.otani@rtbhouse.com).

RTB House: add fledge docs; reorganization

---

dev-docs/modules/dataControllerModule.md

Data controller Module Code renamed with actual file name

---

dev-docs/bidders/sharethrough.md

Sharethrough - Support native

---

dev-docs/bidders/uol.md

New adapter: Uol as an AppNexus alias

---

dev-docs/bidders/copper6.md

SSP Copper6 doc

---

prebid-mobile/modules/rendering/android-sdk-integration-gam.md
prebid-mobile/modules/rendering/android-sdk-integration-pb.md
prebid-mobile/pbm-api/android/code-integration-android.md
prebid-mobile/prebid-mobile-getting-started.md

Prebid Mobile
- https://github.com/prebid/prebid-mobile-ios/issues/839
- https://github.com/prebid/prebid-mobile-android/issues/623

Mobile - additional info

---

dev-docs/bidders/eskimi.md

Add Eskimi adapter video support documentation

---

dev-docs/bidders/viously.md

Add: Viouly GVL ID

---

dev-docs/bidders/viously.md

Remove duplicate meta tags for viously

---

dev-docs/bidders/minutemediaplus.md

minutemediaplus: added gpp_supported

---

dev-docs/bidders/vidazoo.md

- [X ] new feature
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203849715302559

vidazooBidAdapter: gpp_supported

---

dev-docs/bidders/stroeerCore.md

StroeerCore Bid Adapter: add price floor support

---

dev-docs/analytics/epsilon.md

Adding in alias for epsilon in conversant adapter.  Related change:
- https://github.com/prebid/Prebid.js/pull/9961
- https://github.com/prebid/prebid-server/pull/2781
- [x ] new examples
- [x ] Related pull requests in prebid.js or server are linked -> Paste link in this list or reference it on the PR itself

epsilon branding for conversant

---

dev-docs/bidders/motorik.md

init motorik adapter doc

---

dev-docs/modules/growthCodeRtdProvider.md

New Growthcode RTD module for delivering real-time contextual and audience segmentation capabilities.

growthCodeRtdProvider Docs

---

dev-docs/bidders/bidgency.md

Documenting https://github.com/prebid/Prebid.js/pull/10077

Aso Bid Adapter: documenting bidgency alias

---

dev-docs/bidders/rise.md

Rise - add PBS support documentation

---

dev-docs/bidders/cadent_aperture_mx.md

Cadent Aperture MX: rename emx to Cadent Aperture MX

---

dev-docs/bidders/pubtech.md

This PR is relative to the work done in https://github.com/prebid/Prebid.js/pull/10042

Add Pubtech Bidder docs

---

dev-docs/activity-controls.md
dev-docs/modules/allowActivities.md
dev-docs/publisher-api-reference/setConfig.md

Update activity control docs:
- add a module page so that it appears in the download page
- add `transmitTid` activity (https://github.com/prebid/Prebid.js/pull/10034)

JS: update docs on activity controls

---

dev-docs/modules/userid-submodules/trustpid.md

This was renamed in #4528 but we need the old name around for a transition period in case publishers have started using it.

trustpid legacy doc

---

Gemfile
_config.yml

Fix warning from the github pages deployment

Set site.title and update github-pages

---

dev-docs/activity-controls.md
dev-docs/faq.md

Following https://github.com/prebid/Prebid.js/issues/10097#issuecomment-1591198687 example, this adds uspapi enforcement as an example in documentation.

Document ccpa enforcement

---

dev-docs/bidders/projectagora.md

Update Project Agora bid adapter

---

dev-docs/bidders/rubicon.md

- [ x ] update bid adapter
- [x ] Related pull requests in prebid.js or server are linked -> Paste link in this list or reference it on the PR itself
https://github.com/prebid/Prebid.js/pull/10132

Rubicon Bid Adapter: gpp_supported = true

---

dev-docs/bidders/rtbhouse.md

Please reach us at [inventory_support@rtbhouse.com](mailto:inventory_support@rtbhouse.com) with [piotr.jaworski@rtbhouse.com](mailto:piotr.jaworski@rtbhouse.com) and cc [leandro.otani@rtbhouse.com](mailto:leandro.otani@rtbhouse.com).

RTB House: adding custom PA API/FLEDGE seller options

---

dev-docs/bidders/ix-server.md

Added plcmt field to video params

Added plcmt to video params in ix-server.md

---

dev-docs/bidders/openx.md

Remove duplicate fpd_support for openx

---

dev-docs/bidders/brave.md

remove duplicate meta tag for brave

---

dev-docs/bidders/freepass.md

Add FreePass BidAdapter docs

---

dev-docs/bidder-adaptor.md

cleans up bidder advice on gvlid

Update bidder-adaptor.md to mention Canada

---

dev-docs/bidders/gothamads.md

Update: gothamads doc

---

dev-docs/bidders/cadent_aperture_mx.md
dev-docs/pb8-notes.md

Cadent Aperture MX Bid Adapter: update email address (#4)

---

dev-docs/modules/userId.md

New gam feature pulls some userid modules ids
https://support.google.com/admanager/answer/10488752?hl=en

Document signal pull

---

dev-docs/bidders/qortex.md
dev-docs/faq.md

'host' parameter domain change
- [ x ] text edit only (wording, typos)

Update Qortex.md Bidder

---

dev-docs/bidders/ogury.md

ogury: removing useless skipSizeCheck parameter

---

dev-docs/bidders/consumable.md

add gpp support to Consumable docs

---

dev-docs/bidders/9dotsmedia.md
dev-docs/bidders/adtelligent.md
dev-docs/bidders/bidsxchange.md
dev-docs/bidders/copper6.md
dev-docs/bidders/janet.md
dev-docs/bidders/ocm.md
dev-docs/bidders/selectmedia.md
dev-docs/bidders/streamkey.md
dev-docs/bidders/vidcrunchllc.md

Adtelligent: add gpp flags to docs

---

dev-docs/modules/permutiveRtdProvider.md

Fix TOC for permutive

---

dev-docs/bidders/imds.md

Related pull requests:
- https://github.com/prebid/prebid-server/pull/2867
- https://github.com/prebid/Prebid.js/pull/10150
- https://github.com/prebid/prebid-server-java/pull/2371

imds: Add gpp_support for adapter

---

dev-docs/bidders/kargo.md

Asked to update Kargo's notes with new legacy js release

Add note on legacy for kargo

---

features/mspa-usnat.md

After discussion with @patmmccann

USNat: revise normalization

---

features/mspa-usnat.md

Improves internal consistency by making transmitGeo not dependent on other sensitive consent fields

Update mspa-usnat.md - transmitGeo shouldnt check other sensitive fields

---

dev-docs/bidders/adbite.md
dev-docs/bidders/adkernel.md
dev-docs/bidders/adliveconnect.md
dev-docs/bidders/adomega.md
dev-docs/bidders/adsolut.md
dev-docs/bidders/audiencemedia.md
dev-docs/bidders/bcm.md
dev-docs/bidders/bidbuddy.md
dev-docs/bidders/converge.md
dev-docs/bidders/denakop.md
dev-docs/bidders/didnadisplay.md
dev-docs/bidders/displayioads.md
dev-docs/bidders/engageadx.md
dev-docs/bidders/ergadx.md
dev-docs/bidders/felixads.md
dev-docs/bidders/headbidding.md
dev-docs/bidders/houseofpubs.md
dev-docs/bidders/motionspots.md
dev-docs/bidders/qortex.md
dev-docs/bidders/rtbanalytica.md
dev-docs/bidders/rtbdemand_com.md
dev-docs/bidders/sonic_twist.md
dev-docs/bidders/turktelekom.md
dev-docs/bidders/unibots.md
dev-docs/bidders/waardex_ak.md

Adkernel: documenting gpp support

---

dev-docs/bidders/adpluto.md

Adkernel: documenting adpluto alias

---

dev-docs/bidders/adpluto_dsp

Adkernel: documenting adpluto_dsp alias

---

dev-docs/adunit-reference.md
dev-docs/analytics-ga.md

Fix HTML errors

---

dev-docs/bidders/vrtcal.md

Added Native Support and Updated Outdated Support Flags

---

dev-docs/modules/a1MediaRtdProvider.md

New RTD Provider : A1Media

---

dev-docs/bidders/33across.md

Indicate there's GPP & COPPA support in the 33Across Bid Adapter

GPP & COPPA support for 33across bidder adapter

---

dev-docs/bidders/gothamads.md

gothamads: add pbs support

---

dev-docs/modules/userid-submodules/liveintent.md

LiveIntent UserId module: magnite id documentation

---

dev-docs/bidders/hypelab.md

New Adapter: HypeLab

---

dev-docs/bidders/brightcomssp.md

Feature was already implemented, but never documented

Add floor support to brightcomssp

---

dev-docs/bidders/gothamads.md
dev-docs/bidders/rubicon.md
dev-docs/bidders/selectmedia.md
dev-docs/bidders/streamkey.md

Remove duplicated meta data

---

dev-docs/bidder-adaptor.md

This fixes https://github.com/prebid/Prebid.js/issues/10060 and removed file with the same name as main bid adapter file

Change bidResponse meta fields to strings that are numerical

---

dev-docs/bidders/pubcircle.md

- [ x ] new bid adapter
- [ x ] Related pull requests in prebid.js or server are linked -> https://github.com/prebid/Prebid.js/pull/10192
- [ x ] For new adapters check [submitting your adapter docs](https://docs.prebid.org/dev-docs/bidder-adaptor.html#submitting-your-adapter)

New Bid Adapter Docs: PubCircle

---

dev-docs/bidders/freepass.md

FreepasBidAdaptor: add publiser{url,id} to bid param

---

dev-docs/bidders/eplanning.md

Minor changes on eplanning adapter example parameters

---

dev-docs/bidders/xtrmqb.md

New adapter: XTRM QB

---

dev-docs/bidders/screencore.md

screencore: new adapter

---

dev-docs/bidders/adagio.md

Indicate that GPP is supported in the Adagio adapter

---

dev-docs/analytics/automatad.md

Initial commit for docs of autoamatad analytics adapter

---

dev-docs/modules/fledgeForGpt.md

PR https://github.com/prebid/Prebid.js/pull/10360
Discussion: https://github.com/prebid/Prebid.js/issues/10105

fledgeForGpt: consolidate publisher configuration - doc update

---

features/ac-quebec.md

Just a small typo fix in features/ac-quebec.md

Fix scetion typo in ac-quebec.md

---

dev-docs/bidders/cadent_aperture_mx.md

- https://github.com/prebid/Prebid.js/pull/10342

Update bidder page to indicate GPP support for Cadent Aperture MX Adapter

---

dev-docs/bidders/lm_kiviads.md

LM KiviAds prebid server adapter docs

---

dev-docs/bidders/liftoff.md

Add new adapter doc for liftoff

---

dev-docs/bidders/amx-server.md
dev-docs/bidders/amx.md

Indicating support for ortb blocking, floors module, and adding a section about bidder settings -- storageAllowed.

AMX RTB: indicate ortb blocking support, add bidder settings section

---

dev-docs/bidders/sonobi.md

Resolves https://github.com/prebid/prebid-server/issues/1063

added a prebid server params section to the Sonobi bidder docs

---

prebid-mobile/pbm-api/android/code-integration-android.md
prebid-mobile/pbm-api/ios/code-integration-ios.md

- Prebid SDK iOS:  https://github.com/prebid/prebid-mobile-ios/pull/903
- Prebid SDK Android: https://github.com/prebid/prebid-mobile-android/pull/664

Prebid SDK - description of properties for creative factory timeout configuration

---

dev-docs/modules/fledgeForGpt.md

Update variable names in example to work with updated fledge module

Update example in fledgeForGpt.md

---

dev-docs/bidders/33across.md

Update features table, replace some "check with bidder" values

33Across: Update bidder documentation

---

prebid-server/developers/add-new-bidder-go.md

Update documentation for https://github.com/prebid/prebid-server/issues/2908 in PBS-Go.
- https://github.com/prebid/prebid-server/pull/2972

Sdk renderer

---

dev-docs/bidders/cadent_aperture_mx.md

Cadent Aperture MX: add filename attribute to fix build

---

_layouts/bidder.html

Move send all bids section to bottom of page

---

prebid-server/hosting/pbs-hosting.md

resolves https://github.com/prebid/prebid.github.io/issues/4820

Update PBS-Java metric systems

---

dev-docs/bidders/yieldlove
dev-docs/bidders/yieldlove.md

YieldloveBidAdapter: Release

---

dev-docs/modules/optimeraRtdProvider.md

OptimeraRTD: Adding apiVersion parameter description.

---

dev-docs/bidders/mabidder.md

- https://github.com/prebid/prebid-server/pull/3080

update mabidder.md documetation support pbs

---

dev-docs/modules/experianRtdProvider.md
dev-docs/modules/tapadRtdProvider.md

- new RTD module
https://github.com/prebid/Prebid.js/pull/10331 prebid.js PR here

Experian rtd documentation

---

dev-docs/bidders/pgamssp.md

Bid adapter PGAMSSP: new adapter

---

dev-docs/bidders/bidgency.md

Bidgency Adapter: Added aso alias code

---

dev-docs/bidders/bcmint.md

Bcmint Adapter: Added aso alias code

---

dev-docs/bidders/appstock.md

New adapter: Appstock

---

dev-docs/bidders/bematterfull

- Prebid Server PR: https://github.com/prebid/prebid-server/pull/3036

Bematterfull bid adapter: init dev-docs

---

dev-docs/bidders/optidigital.md

OptidigitalBidAdapter: Adding userId module, updating User Sync information

---

dev-docs/bidders/greedygame.md

New adapter: GreedyGame

---

dev-docs/adunit-reference.md
prebid-video/video-integrating-solo.md

Trying to further adoption of the new `plcmt` field.

Update docs regarding plcmt

---

README.md
_layouts/bidder.html
dev-docs/bidder-adaptor.md
prebid-server/developers/add-new-bidder-go.md
prebid-server/developers/add-new-bidder-java.md

Fixes #4776 - migrate `gpp_supported` to `gpp_sids`

Migrate from gpp_supported to gpp_sids

---

dev-docs/bidders/pgamssp.md

pgamssp - disable PBJS download

---

features/mspa-usnat.md

USnat update regarding issue #4805

Updated usNat Table with GPP 1.1 Support

---

dev-docs/bidders/pgam.md
dev-docs/bidders/pgamssp.md

per https://github.com/prebid/prebid.github.io/issues/4800

pgam updates

---

dev-docs/bidders/beop.md

We missed the update of that documentation since a long time. Making a clean on what we actually do now.

Update BeOp Doc

---

dev-docs/adfusion.md

New Bid Adapter : AdFusion

---

dev-docs/modules/gdprEnforcement.md

Documentation for gdprEnforcement changes; https://github.com/prebid/Prebid.js/pull/10435

JS gdprEnforcement: document new transmitPreciseGeo, eidsRequireP4consent config

---

dev-docs/bidders/viant.md

update contact information in md file

Update viant.md - update contact information in md file

---

dev-docs/modules/gdprEnforcement.md

Minor followup to https://github.com/prebid/prebid.github.io/pull/4876 , which was basically fine, but added a few flourishes.
Heads up @dgirardi .

wordsmithing gdprEnforcement

---

dev-docs/publisher-api-reference/setConfig.md

Documentation for https://github.com/prebid/Prebid.js/pull/10308
Also see https://github.com/prebid/Prebid.js/issues/10524

JS: document new `eventHistoryTTL` and `minBidCacheTTL` settings

---

dev-docs/bidders/viant.md

Update viant.md - update schain support parameter

Update viant.md - update schain support parameter

---

prebid-server/developers/add-a-module-java.md

Implements https://github.com/prebid/prebid-server/issues/3115

PBS-Java module: Added get CPU function

---

prebid-mobile/modules/rendering/android-sdk-integration-pb.md
prebid-mobile/modules/rendering/ios-sdk-integration-pb.md
prebid-mobile/pbm-api/android/android-sdk-integration-gam-original-api.md
prebid-mobile/pbm-api/ios/ios-sdk-integration-gam-original-api.md

Prebid SDK - multiformat ad unit for original api

---

dev-docs/bidders/incrementx.md

Fix for issue https://github.com/prebid/Prebid.js/issues/10520

Update incrementx filename for download page

---

prebid-mobile/modules/rendering/android-sdk-integration-pb.md
prebid-mobile/modules/rendering/ios-sdk-integration-pb.md
prebid-mobile/pbm-api/android/android-sdk-integration-gam-original-api.md
prebid-mobile/pbm-api/ios/ios-sdk-integration-gam-original-api.md

- Related tickets:
- iOS: https://github.com/prebid/prebid-mobile-ios/issues/925
- iOS: https://github.com/prebid/prebid-mobile-ios/issues/926
- Android: https://github.com/prebid/prebid-mobile-android/issues/698
- Android: https://github.com/prebid/prebid-mobile-android/issues/699

Mobile extend api for gpid and events

---

prebid-mobile/modules/rendering/android-sdk-integration-pb.md
prebid-mobile/modules/rendering/ios-sdk-integration-pb.md
prebid-mobile/pbm-api/android/android-sdk-integration-gam-original-api.md
prebid-mobile/pbm-api/ios/ios-sdk-integration-gam-original-api.md

Reverts prebid/prebid.github.io#4927

Revert "Mobile extend api for gpid and events"

---

dev-docs/bidders/lunamedia.md

Greetings,
We have noticed that the PBS adapter "lunamedia" is currently not listed on the dev-docs/pbs-bidders.html page. Could you kindly consider adding it to the documentation? Your assistance in this matter would be greatly appreciated.
Last PR: https://github.com/prebid/prebid-server/pull/3137
Thank you in advance!

Lunamedia PBS adapter docs

---

overview/intro.md

Change title to match the refeerencees.

Change Intro -> Introduction in Intro to Prebid Header

---

dev-docs/bidders/sovrn.md

Sovrn: make minduration recommended

---

dev-docs/bidders/smartx.md

update smartx documentation for support pbs

---

_data/sidebar.yml
prebid-mobile/pbm-api/android/pbm-plugin-renderer.md

Fix issues with links on plugin renderer docs

---

dev-docs/bidders/lemmadigital.md

LemmaDigital Adapter: pbs support

---

dev-docs/bidders/kobler.md

Fixed docs for Kobler adapter.

---

dev-docs/bidders/sparteo.md

PR in Prebid.js : https://github.com/prebid/Prebid.js/pull/10582

Sparteo Bid Adapter: Add Sparteo documentation

---

prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md

Updates for https://github.com/prebid/prebid-server/issues/2727

PBS auction endpoint TID changes

---

dev-docs/bidders/bluesea.md

New Adapter: bluesea.md

---

dev-docs/bidders/admatic.md
dev-docs/bidders/pixad.md

AdMatic Bid Adapter: added simple params AdMatic PR & Pixad PR

---

dev-docs/bidders/smartx.md

Split prebid server adapter options and Prebid.JS options

Smartx: documentation update

---

dev-docs/bidders/teads.md

Update teads documentation

---

_sass/vendor/_awesomplete.scss
_sass/vendor/_bourbon.scss
_sass/vendor/_include-media.scss

Fix #4979 imports for node_modules sass

---

dev-docs/bidders/impactify.md

Impactify : Add informations on storage in documentations

---

dev-docs/modules/goldfishAdsRtdProvider.md

GoldfishAdsRtdProvider: New Module

---

prebid-server/developers/add-new-bidder-java.md

- https://github.com/prebid/prebid-server-java/pull/2707

Add SDK Renderer Info

---

adops/price-granularity.md

as reported by community member Lukas. thanks.

fixing price-granularity line item counts

---

dev-docs/bidders/adstir.md

add adstir Bid Adapter

---

_data/sidebar.yml
prebid-mobile/dr-prebid.md

we've removed this app from both Apple and Android app stores

deprecating dr prebid

---

dev-docs/bidder-adaptor.md
dev-docs/faq.md
dev-docs/modules/consentManagement.md
prebid-server/developers/add-new-bidder-go.md
prebid-server/developers/add-new-bidder-java.md
prebid-server/features/pbs-privacy.md

addressing recent TCF 2.2 questions and some dead links

TCF 2.2 clarifications

---

adops/creative-considerations.md
adops/gam-creative-banner-sbs.md
overview/prebid-universal-creative.md

Followup to https://github.com/prebid/Prebid.js/issues/10741

Document additional PUC alternates

---

_data/sidebar.yml
overview/glossary.md

As discussed in the docs committee meeting

initial glossary

---

dev-docs/bidders/oms.md

New Adapter: oms

---

dev-docs/bidders/sharethrough.md

- [ x] text edit only (wording, typos)

Update mediaTypes to include native

---

_sass/node_modules/awesomplete/awesomplete.base.scss
_sass/node_modules/awesomplete/awesomplete.scss
_sass/node_modules/awesomplete/awesomplete.theme.scss
_sass/node_modules/awesomplete/prism/prism.scss
_sass/node_modules/awesomplete/style.scss
_sass/vendor/_awesomplete.scss
npm-postinstall.sh
package.json

Fix 404 for the awesomplete css

Integrate awesomplete css

---

dev-docs/bidders/indiecue.md
dev-docs/bidders/medianet.md
dev-docs/bidders/pgam.md
dev-docs/bidders/preciso.md
dev-docs/bidders/tpmn.md

Bidders have duplicated meta fields

Remove duplicate meta data fields

---

_includes/code/mobile-sdk.html
docs-examples/tab-example.md

Add a jekyll include to provide code examples for kotlin and swift. Fixes #5003

LiveIntent UserId module: Clean up the sub-module documentation (#5011)

---

dev-docs/bidders/vox.md

Add gvl_id to vox adapter

---

dev-docs/bidders/minutemedia.md

MinuteMedia Bid Adapter - Support Currency

---

dev-docs/bidders/rise.md

Rise Bid Adapter - Supporting currency bidder param

---

dev-docs/bidders/embimedia.md

https://github.com/prebid/prebid-server/pull/3325

Embi media bidder adapter

---

dev-docs/bidders/dxkulture.md

Updating support E-Mail, fixed typos and added pbs support definition

DXKulture - Updating docs details

---

dev-docs/bidders/openx.md
dev-docs/show-video-with-a-dfp-video-tag.md

- [ x] text edit only (wording, typos)
Removing dead video links from dead link checker report:
https://www.deadlinkchecker.com/reports/docs-prebid-org-20231123195232.html

Remove dead video links

---

faq/prebid-mobile-faq.md

Thanks to @simhomer for drafting the contents.

Mobile FAQ OM SDK entry

---

prebid-server/developers/pbs-cookie-sync.md
prebid-server/endpoints/pbs-endpoint-cookieSync.md

Update cookie sync doc

---

formats/multiformat.md

@pm-harshad-mane pointed out that this page was many years outdated. Put some lipstick on it...

modernizing the multiformat page

---

prebid-server/pbs-modules/confiant-ad-quality.md

feature: Add ExcludeBidders from scan config and Analytic tags for Confiant Ad Quality module docs

---

.markdownlint.json
overview/all-videos.md
prebid-server/developers/add-new-bidder-go.md
prebid-server/developers/add-new-bidder-java.md
prebid-server/hosting/bidder-specific-guidelines.md
prebid-video/video-overview-video.md
prebid-video/video-overview.md

First of the next batch of video explainers.

Adding video format video overview

---

dev-docs/bidders/rubicon.md

Making use of the the metadata field added in https://github.com/prebid/prebid.github.io/pull/5038

Rubicon adapter privacy sandbox support

---

dev-docs/modules/userid-submodules/mygaru.md

MyGaru Id System: initial release

---

dev-docs/bidders/ampliffy.md

Ampliffy Bid Adapter Documentation

---

dev-docs/analytics/greenbids.md
dev-docs/modules/greenbidsRtdProvider.md

This updates the documentation for greenbids Analytics and RTD modules, to match new functionnality.

update greenbids modules documentation

---

dev-docs/bidders/r2b2.md

- [ x] new bid adapter
- [ x] Related pull requests in prebid.js or server are linked -> (https://github.com/prebid/Prebid.js/pull/10702)

New adapter: r2b2

---

dev-docs/bidders/ad2iction.md

Ad2iction Bid Adapter: initial release

---

dev-docs/bidders/ix.md

Added Protected Audience support, updated siteID examples, updated example for outstream video

Updated ix.md

---

dev-docs/modules/floors.md

As described in https://github.com/prebid/Prebid.js/issues/10410

Floors module supports noFloorSignalBidders option

---

prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md

PBA auction endpoint update

---

dev-docs/bidders/datablocks.md

Fix wrong param names

---

dev-docs/bidders/bizzclick.md

Bizzclick: update doc

---

adops/adops-overview-video.md
adops/adops-planning-guide.md
adops/overview
overview/all-videos.md

Add adops video overview

---

dev-docs/bidder-adaptor.md

Per https://github.com/prebid/Prebid.js/pull/10971

PBJ adapter: DSA meta field

---

dev-docs/bidders/minutemedia.md

MinuteMedia prebid-server adapter was merged: https://github.com/prebid/prebid-server/pull/3399
After the next release of prebid-server, the documentation should be updated to reflect this change.

MinuteMedia: Set pbs to true

---

dev-docs/bidders/dsp_geniee.md

https://github.com/prebid/Prebid.js/pull/10834

dsp_geniee Bid Adapter : add dsp_geniee.md

---

adops/gam-native.md
prebid-mobile/pbm-api/android/android-sdk-integration-gam-original-api.md
prebid-mobile/pbm-api/ios/ios-sdk-integration-gam-original-api.md

The issue in the mobile repo: https://github.com/prebid/prebid-mobile-ios/issues/878

Mobile: docs for in-app native

---

dev-docs/bidders/aja.md

AJA Bid Adapter: update bidder specification

---

dev-docs/bidders/adelement.md

* feat: add doc for adelement md

AdElement Bid Adapter: initial release doc

---

dev-docs/bidders/silvermob.md

SilverMob Adapter doc update

---

dev-docs/analytics/yandex.md

Yandex Analytics Adapter: initial release

---

dev-docs/bidders/yandex.md

Fix typo in yandex.md

---

dev-docs/bidders/yieldmo.md

Added gpp and gpp_sid to Yieldmo user sync url.
Update bid adapter
Related prebid-server PR: https://github.com/prebid/prebid-server/pull/3442

Added gpp support

---

dev-docs/modules/weboramaRtdProvider.md

fix small typos on weborama RTD documentation

---

prebid-server/developers/add-new-bidder-go.md

Requested documentation:
https://github.com/prebid/prebid-server/issues/3085#issuecomment-1766413682
Linked PR:
https://github.com/prebid/prebid-server/pull/3087/files

Add rendererurl documentation into bid meta field

---

dev-docs/modules/userid-submodules/liveintent.md

Add documentation about the LiveConnect minimal version

---

dev-docs/modules/raynRtdProvider.md

Module: Rayn RTD provider module

---

dev-docs/modules/userid-submodules/utiq.md

Utiq ID submodule: Update module parameters and contact

---

dev-docs/analytics/yandex.md
dev-docs/bidders/yandex.md

- Added more information about adapter
- Removed obsolete postfix "Analytics" causing build problems from website

Yandex Analytics Adapter: post-release docs update

---

features/firstPartyData.md

The example in [firstPartyData page](https://docs.prebid.org/features/firstPartyData.html) has been added before the [attribute names update](https://github.com/InteractiveAdvertisingBureau/openrtb/pull/158/files).
- https://github.com/prebid/Prebid.js/pull/10981#issuecomment-1919324803

DSA: update attribute names in ortb2 example

---

dev-docs/bidders/consumable-server.md
dev-docs/bidders/consumable.md

Update the documentation for prebid and prebid-server to add the additional bid parameters for app and ctv traffic.  Give more detailed examples and documentation
- [x ] new feature
- [x ] new examples

Consumable - Documentation Update

---

dev-docs/bidders/consumable-server.md
dev-docs/bidders/consumable.md

Very minor fix for a layout issue on the prebid-server bidders page.  Also make the non server related page not show

Consumable: Fix layout issue with table and showing on server page

---

dev-docs/modules/s2sTesting.md

fixes https://github.com/prebid/Prebid.js/issues/11116
This has been wrong since PBJS 5.0

Update s2sTesting hb_source instructions

---

dev-docs/bidders/pubmatic.md

PubMatic: Added support for dChain

---

dev-docs/modules/prebidServer.md

as discussed in https://github.com/prebid/Prebid.js/issues/10964

Syncing PBS timeout behavior with reality

---

dev-docs/modules/debugging.md
prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md
prebid-server/features/pbs-feature-idx.md
prebid-server/features/pbs-fpd.md
support/privacy-resources.md

- Added topics
- Added test labels
- a few other general updates/fixes

Prebid Server privacy sandbox updates

---

dev-docs/bidders/aja.md

AJA Bid Adapter: add Supply Chain Object Module support

---

dev-docs/bidders/adnuntius.md

[- [x] Related pull requests in prebid.js or server are linked -> Paste link in this list or reference it on the PR itself
https://github.com/prebid/Prebid.js/pull/11029

User Id added to documentation.

---

dev-docs/bidders/themoneytizer.md

The Moneytizer Bid Adapter: initial release

---

dev-docs/bidders/kimberlite.md

Kimberlite

---

dev-docs/bidders/oms.md

OMS Adapter: enable prebid.js adapter

---

dev-docs/modules/userid-submodules/33across.md

33Across User ID module: Change ID expiration from 90 to 30 days

---

dev-docs/bidders/adstir.md

adstirBidAdapter - add reference about the version requirement

---

dev-docs/faq.md

Also added an entry for allowAuctionWithoutConsent

Restructured PBJS FAQ

---

dev-docs/bidders/adbutler.md

Add AdButler bid adapter documentation

---

dev-docs/bidder-adaptor.md

Update location in new adapter docs to read from request

---

prebid-server/endpoints/pbs-endpoint-cookieSync.md

clarifying datatypes and location

PBS cookie_sync endpoint updates

---

dev-docs/bidders/stn.md

- Related PR: https://github.com/prebid/Prebid.js/pull/11085

stnBidAdapter: initial docs

---

dev-docs/bidders/theAdx.md

theadx prebid server support

---

dev-docs/modules/azerionedgeRtdProvider.md

Related PR:
- https://github.com/prebid/Prebid.js/pull/11134

Azerion Edge RTD Module: Initial release

---

dev-docs/bidders/bwx.md

Prebid server PR: https://github.com/prebid/prebid-server/pull/3430

BoldwinX adapter docs

---

dev-docs/bidders/adfusion.md
prebid-server/developers/add-new-bidder-go.md
prebid-server/developers/add-new-bidder-java.md

(also moving adfusion adapter doc to the right place)

fix gpp_supported instructions

---

dev-docs/publisher-api-reference/aliasBidder.md

As suggested in https://github.com/prebid/prebid.github.io/issues/5218

aliasBidder - added example

---

dev-docs/bidders/digiad.md

Adkernel: documenting digiad alias

---

dev-docs/bidders/minutemedia.md

MinuteMedia: Specify supported GPP SID

---

dev-docs/bidders/stn.md

STN: GPP Support

---

dev-docs/bidders/viant.md

Update Viant's bidder code to match the module name - https://github.com/prebid/Prebid.js/issues/11251

update viantOrtb bidder code

---

dev-docs/bidders/aso.md
dev-docs/bidders/bcmint.md
dev-docs/bidders/bidgency.md

Server adapter added

---

dev-docs/bidders/operaads.md

tired of waiting for someone to fix the conflicts in https://github.com/prebid/prebid.github.io/pull/4918 -- closing that one with the relevant fixes here

operaads: add GVLID

---

dev-docs/bidders/aso.md
dev-docs/bidders/bcmint.md
dev-docs/bidders/bidgency.md

https://github.com/prebid/Prebid.js/pull/11249

Aso Adapter: New features documented

---

prebid-server/features/pbs-storedreqs-go.md

According to the settings in the program, this part needs to be changed to the new settings.
https://github.com/prebid/prebid-server/blob/master/config/stored_requests.go#L101-L103

PBS-Go docs fix: config schema for stored requests

---

dev-docs/bidders/monetix.md

Adkernel: documenting monetix alias

---

dev-docs/publisher-api-reference/bidderSettings.md
dev-docs/publisher-api-reference/setConfig.md

Closes https://github.com/prebid/Prebid.js/issues/11273

JS: reference storageAllowed from deviceAccess

---

dev-docs/bidders/kargo.md

Kargo: fixes typo

---

dev-docs/bidders/trustedstack.md

TrustedStack Adapter: Added gvl_id

---

dev-docs/bidders/doceree.md

Fixes https://github.com/prebid/Prebid.js/issues/11329

JS: update doceree bidder code

---

dev-docs/bidders/doceree.md
dev-docs/bidders/docereeadmanager.md

Fixes https://github.com/prebid/Prebid.js/issues/11352

JS: update docereeAdManager bidder code

---

prebid-mobile/prebid-mobile.md

wording changes

---

dev-docs/bidders/doceree.md

this looks like it was a copy-paste error

Fixing doceree title

---

dev-docs/analytics/id5.md

Fixes https://github.com/prebid/Prebid.js/issues/11357

JS: fix id5 analytics adapter code

---

dev-docs/bidders/insticator.md

Insticator: Update documentation, add third party field support

---

dev-docs/bidder-adaptor.md

Change ref in docs to referer which is correct. Fix for issue -> #4010

Fix naming of ref to referer in adapter docs

---

dev-docs/bidders/openweb.md

Update OpenWeb Bidder Docs

---

prebid-server/developers/add-new-bidder-java.md

ORTB 2.6 links, misc updates. Mirrors https://github.com/prebid/prebid.github.io/pull/5281

PBS java dev doc update

---

dev-docs/floors-video-overview.md
dev-docs/modules/floors.md
overview/all-videos.md
prebid-server/features/pbs-floors.md

floors training video

---

dev-docs/bidders/stn.md

Prebid.js related PR: https://github.com/prebid/Prebid.js/pull/11429

STN Bid Adapter: Remove Multi Currency Support

---

dev-docs/bidders/minutemedia.md

Prebid.js related PR: https://github.com/prebid/Prebid.js/pull/11428

MinuteMedia Bid Adapter: Remove Multi Currency Support

---

dev-docs/bidders/rise.md
dev-docs/bidders/risexchange.md

Prebid.js related PR: https://github.com/prebid/Prebid.js/pull/11427

Rise Bid Adapter: Remove Multi Currency Support

---

dev-docs/publisher-api-reference/bidderSettings.md

fix bidderSetting inverseBidAdjustment fn name in docs

---

dev-docs/modules/anonymisedRtdProvider.md
dev-docs/modules/idWardRtdProvider.md

re-do of https://github.com/prebid/prebid.github.io/pull/4702

idward renamed to anonymised

---

dev-docs/bidders/twistDigital.md

https://github.com/prebid/Prebid.js/pull/11370

Added docs for Twist Digital bid adapter

---

dev-docs/bidders/performax.md

Documentation for this adapter https://github.com/prebid/Prebid.js/pull/11325

performax bidder

---

dev-docs/modules/userid-submodules/utiqMtp.md

Fix linting issues

---

dev-docs/modules/userId.md

User ID: Ability to store user IDs in cookie and localStorage simultaneously

---

dev-docs/bidders/seedtag.md

Seedtag Bid Adapter: updates ortb blocking supported to partial

---

dev-docs/bidders/adsyield.md

Prebid.js PR https://github.com/prebid/Prebid.js/pull/11483

AdsYield Bid Adapter: move to limelight

---

dev-docs/adzymic.md

Adzymic has obtained a GVL ID from the IAB recently. This PR will modify the listed IAB value from 32 to 723.

Adzymic Bid Adapter: Add new IAB GVL Id

---

dev-docs/bidders/adzymic.md

Moved adzymic.md to bidders subfolder and corrected TCF value to true

---

dev-docs/bidders/taboola.md

https://github.com/prebid/Prebid.js/pull/11545

support-dchain

---

dev-docs/bidders/teads.md

Update Teads documentation for supported GPP privacy laws

---

dev-docs/bidders/welect.md

Welect Bid Adapter: re-add adapter to docs

---

prebid-server/developers/add-a-module-java.md

Interaction with `ActivityInfrastructure` for modules

---

dev-docs/bidders/openweb.md

Openweb bid adapter: Make placementId parameter mandatory

---

dev-docs/bidders/algorix.md

AlgoriX: update bidder doc

---

overview/ga-analytics.md

Addresses https://github.com/prebid/prebid.github.io/issues/5360

GA Analytics: Add deprecation warning

---

dev-docs/bidders/hyperbrainz.md

Adkernel: documenting hyperbrainz alias

---

dev-docs/bidders/adliveplus.md
dev-docs/bidders/lucead.md

Here is an update of documentation of the Lucead and Adlive Plus (alias of Lucead) bid adapters.

Lucead bid adapter: Update

---

dev-docs/modules/contxtfulRtdProvider.md

- [ x ] new feature
- [ x ] new examples
- [ x ] Related pull requests in prebid.js or server are linked
Contxtful Provider Related [PR](https://github.com/prebid/Prebid.js/pull/11497)

Contxtful RTD Provider - Updated Documentation

---

dev-docs/bidders/beachfront.md

Update Beachfront doc for plcmt

Update Beachfront doc for plcmt

---

dev-docs/modules/userid-submodules/id5.md

Update id5.md disclosure

---

dev-docs/modules/userid-submodules/ftrack.md

Update ftrack.md disclosures

---

dev-docs/bidders/driftpixel.md

add driftpixel Adapter

---

dev-docs/bidders/insticator.md

Insticator Bid Adaptor: update docs for bidfloor

---

prebid-mobile/modules/rendering/ios-sdk-integration-gam.md

Addresses: https://github.com/prebid/prebid-mobile-ios/issues/940

Fixed typo (c+p error)

---

dev-docs/bidders/33across.md

33across Bid Adapter: Support for ORTB video.plcmt field

---

dev-docs/bidders/teads.md

Update list of supported GPP sids

Update list of GPP sids for Teads adapter

---

dev-docs/modules/51DegreesRtdProvider.md

51DegreesRtdProvider: add table styles

---

dev-docs/bidders/qt.md

New Adapter: QT

---

dev-docs/bidders/ringieraxelspringer.md

I have added the requested missing fields, although due to copying of the PR I can't commit in that one directly.
Link to related PR: https://github.com/prebid/prebid.github.io/pull/5386

add missing fields to ringieraxelspringer doc

---

Gemfile
faq/prebid-server-faq.md
prebid-server/developers/add-new-bidder-go.md
prebid-server/developers/add-new-bidder-java.md
prebid-server/endpoints/openrtb2/auction-request-example.md
prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md

Been asked a couple of times to publish an example Prebid Server request with lots of the options filled out.

PBS request example

---

dev-docs/analytics/growthcode.md

Found thanks t o https://github.com/prebid/prebid.github.io/issues/5359

Fix growthcode table styling #5359

---

dev-docs/modules/topLevelPaapi.md
dev-docs/publisher-api-reference/getPAAPIBids.md

Documentation for https://github.com/prebid/Prebid.js/pull/11379

Document new JS module: topLevelPaapi

---

dev-docs/modules/jwplayerRtdProvider.md

Prebid.js PR: https://github.com/prebid/Prebid.js/pull/11692

JW Player RTD Adapter: 9.0 migration

---

Gemfile
dev-docs/modules/topicsFpdModule.md

Change default iframes config

---

dev-docs/analytics/AsteriobidPbm.md

Related to 9.0 and pr -> https://github.com/prebid/Prebid.js/pull/11624

Update and rename prebidmanager.md to AsteriobidPbm.md

---

dev-docs/modules/userid-submodules/33across.md

33Across User ID sub-module: Introduce a new supplemental ID

---

dev-docs/analytics/eplanning.md
dev-docs/analytics/sigmoid.md
dev-docs/analytics/sonobi.md
dev-docs/analytics/sovrn.md
dev-docs/analytics/staq.md
dev-docs/bidders/adbookpsp.md
dev-docs/bidders/bluebillywig.md
dev-docs/bidders/ebdr.md
dev-docs/bidders/iqm.md
dev-docs/bidders/minutemediaplus.md
dev-docs/bidders/mytarget.md
dev-docs/bidders/richaudience.md
dev-docs/bidders/spotx.md
dev-docs/modules/idWardRtdProvider.md
dev-docs/modules/userid-submodules/parrable.md

Prebid 9.0 docs updates

---

dev-docs/modules/enrichmentFpdModule.md

Fix download issues pbjs 9: Update enrichmentFpdModule.md

---

dev-docs/bidders/zeta_global.md

Fix bidder code for `zetaBidAdapter`

Fix zeta global biddercode

---

dev-docs/bidders/smaato.md

Fix publisherId parameter in code example for smaato adapter

Update publisherId parameter

---

dev-docs/bidders/setupad.md

Update bid params

---

dev-docs/modules/mobianRtdProvider.md

This PR is for a new RTD module! The RTD module just exposes an API endpoint.
- [ x] new feature
- [ x] Related pull requests in prebid.js or server are linked

initialize documentation for mobian brand safety RTD module

---

dev-docs/modules/adagioRtdProvider.md

Adagio Rtd Provider: add placementSource param

---

dev-docs/bidders/cpmstar.md

- See: https://github.com/prebid/Prebid.js/pull/11881

cpmstarBidAdapter: updated gvlid and tcfeu, schain_supported flags

---

dev-docs/bidders/stailamedia.md

New adapter: stailamedia

---

dev-docs/bidders/blasto.md

Bizzclick Bid Adapter: remove deprecated params

---

dev-docs/bidders/openweb.md

Openweb adapter: PBS supported

---

dev-docs/bidders/colossus.md
dev-docs/bidders/colossusssp.md
dev-docs/bidders/kargo.md

Remove old disclosure on kargo.md and colossus

---

dev-docs/modules/anonymisedRtdProvider.md

- Corrected type
- Added required `rtdModule` module into the `gulp build` command

Corrected docs

---

dev-docs/bidders/teads.md

Add note about the Teads adapter requiring playinline.

Add note for playinline for Teads adapter

---

dev-docs/bidders/smilewanted.md

Add native support for SmileWanted Bidder Adapter

Smilewanted : add native support

---

dev-docs/bidders/inmobi.md

Updated documentation - User sync disclosure section inmobi

---

dev-docs/modules/consentManagementTcf.md

Updating which modules are required to build for tcfConsentManagement in prebid 9.x.x.

Update required build modules for consentManagementTcf

---

dev-docs/bidders/sharethrough.md

Just a small change to help emphasize to anyone reading the doc the desired uniqueness we would like to see in GPID values passed to our exchange.

GPID, make desired uniqueness of more obvious in example

---

dev-docs/bidders/voisetech.md

Adkernel: documenting voisetech alias

---

dev-docs/bidders/ix.md

Update the PAAPI section to include the new configs

Update the PAAPI section to include the new configs

---

dev-docs/bidders/1accord.md

Add 1accord Bidder docs

---

dev-docs/modules/51DegreesRtdProvider.md

- clarified the free availability of the api
- improved configuration description

51degreesRtdProvider: update doc

---

dev-docs/bidders/ownadx.md

OwnAdX PrebidJS Bidder Docs

---

dev-docs/bidders/displayio.md

Displayio: add prebid server adapter support

---

overview/all-videos.md
overview/analytics-video.md
overview/analytics.md

Philip's latest masterpiece...

analytics training video

---

dev-docs/modules/userid-submodules/id5.md

ID5 UserId - no longer requiring html storage type

---

dev-docs/analytics/adagio.md

- Related adapter changes https://github.com/prebid/Prebid.js/pull/11961

Adagio Analytics Adapter: Add new config options field examples

---

dev-docs/bidders/kimberlite.md

kimberliteBidAdapter: video support docs update

---

dev-docs/bidders/lifestreet.md

Lifestreet : remove outdated adapter note

---

dev-docs/bidders/cwire.md

Update cwire docs for prebid adapter params

---

dev-docs/bidder-adaptor.md

https://github.com/prebid/Prebid.js/pull/11998

+ onAdRenderSucceeded

---

dev-docs/bidders/ttd.md

Prebid Server PR: https://github.com/prebid/prebid-server/pull/3738

TheTradeDesk documentation

---

dev-docs/modules/userid-submodules/intentiq.md

update configuration example

---

dev-docs/analytics/advRed.md

AdvRed Analytics Adapter: update documentation css

---

dev-docs/bidders/pstudio.md

Pstudio: Change prebid body request param

---

dev-docs/bidders/vimayx.md

https://github.com/prebid/Prebid.js/pull/11874 
https://github.com/prebid/prebid-server/pull/3760

add VimayX adapter

---

dev-docs/bidders/filmzie.md

Prebid Server PR: https://github.com/prebid/prebid-server/pull/3758

New Adapter: Filmzie

---

dev-docs/bidders/metax.md

- PBS PR: https://github.com/prebid/prebid-server/pull/3712

MetaX Documentation

---

dev-docs/modules/fledgeForGpt.md

paapi gtpt module verbiage update

---

dev-docs/bidders/felixads.md

-> Prebid-server https://github.com/prebid/prebid-server/pull/3837
-> Prebid.js https://github.com/prebid/Prebid.js/pull/12072
This is new bid adapter, deprecated docs are not related to Prebid-server or Prebid.js code

New adapter FelixAds

---

dev-docs/bidders/pubrise.md

Pubrise: new adapter

---

dev-docs/bidders/global_sun.md

Adkernel: documenting global_sun alias

---

dev-docs/bidders/eclickads.md

EClickAds: new bid adapter docs

---

prebid-mobile/pbm-api/android/code-integration-android.md

Fix for broken link in mobile docs for global parameters

Fix broken link for global params in mobile code integration

---

features/firstPartyData.md

This PR adds two new entries to the table of automatically collected first-party data (FPD enrichment) and updates the descriptions of existing entries

Update table of collected FPD data

---

prebid-server/pbs-modules/51degrees-device-detection.md

* change module id and paths to flatcase according to the [review comment](https://github.com/prebid/prebid-server/pull/3650#discussion_r1690269271)
* add a warning re: free / paid data file

51d: update go module id and paths to flatcase

---

dev-docs/bidders/taboola.md

https://github.com/prebid/prebid-server/pull/3795

Taboola: pbs support app

---

dev-docs/bidders/freedomadnetwork.md

Implementation PR: https://github.com/prebid/Prebid.js/pull/12153

New Adapter: Freedom Ad Network Bidder Adapter

---

dev-docs/bidders/docereeadmanager.md

During our testing, we identified that the bidder code specified in the documentation was causing errors due to a case mismatch.
To eliminate confusion and ensure consistency, I have updated the bidder code in the documentation to match the [Bid Adapter's implementation.](https://github.com/prebid/Prebid.js/blob/9.11.0/modules/docereeAdManagerBidAdapter.js#L4)

DocereeAdManager md: Updated biddercode as per Bid Adapter file

---

dev-docs/modules/symitriDapRtdProvider.md

[Prebid.js PR](https://github.com/prebid/Prebid.js/pull/12129)

Symitri dap rtd module update documentation

---

dev-docs/bidders/criteo.md

[Criteo] Addition of the uid parameter

---

prebid-server/pbs-modules/ortb2-blocking.md

noting that enforcement is not on by default, other minor tweaks

PBS ortb2-blocking update

---

dev-docs/bidders/loopme.md

Loopme: Add Bidder

---

dev-docs/bidders/oraki.md

New Adapter: Oraki

---

dev-docs/bidders/ssp_geniee.md

Related pull requests in Prebid.js: https://github.com/prebid/Prebid.js/pull/12241

directly push

---

dev-docs/bidders/adgrid.md

New Adapter AdGrid

---

dev-docs/modules/anonymisedRtdProvider.md

anonymisedRtdProvider: documentation update

---

dev-docs/bidders/adtonos.md

New bidder adapter: AdTonos

---

dev-docs/modules/51DegreesRtdProvider.md

51DegreesRtdProvider: replace wrong URL

---

dev-docs/bidders/yandex.md

Yandex Bidder Adapter: add info about User ID Module

---

dev-docs/bidders/eskimi.md

Eskimi adapter documentation update

---

features/timeouts-video.md
features/timeouts.md
overview/all-videos.md
tools/prof-prebid-video.md
tools/professor-prebid.md

final training videos

---

dev-docs/publisher-api-reference/getEvents.md

Adding pbsAnalytics event

---

formats/video.md
prebid-video/video-getting-started.md
prebid-video/video-overview.md

Video Overview, Formats, Getting Started: documentation updates

---

prebid-server/endpoints/pbs-endpoint-admin.md
prebid-server/endpoints/pbs-endpoint-cookieSync.md
prebid-server/endpoints/pbs-endpoint-event.md
prebid-server/endpoints/pbs-endpoint-status.md
prebid-server/overview/prebid-server-overview.md

PBS: fix very minor annoyances in the Prebid Server documentation

---

dev-docs/modules/symitriDapRtdProvider.md

https://github.com/prebid/Prebid.js/pull/12311

Segment Taxonomy value changed to Symitri Registered Value

---

dev-docs/bidders/feedad.md

Added a description of the optional `sdkOptions` parameter

updated feedad adapter documentation

---

dev-docs/bidders/dexerto.md

New Bidder: dexerto

---

dev-docs/bidders/missena.md

Related PR: https://github.com/prebid/prebid-server/pull/3761

New Prebid Server Adapter: Missena

---

dev-docs/bidders/adsinteractive.md

change prebid member status

---

dev-docs/bidders/loopme.md

update loopme bidder adapter docs

---

dev-docs/bidders/tapnative.md
dev-docs/modules/ehealthcaresolutions.md

- [x ] Related pull requests in prebid.js or server are linked -> https://github.com/prebid/Prebid.js/pull/12322

New Bidder:tapnative

---

dev-docs/bidders/aniview.md

[Related PR in Prebid.js](https://github.com/prebid/Prebid.js/pull/12275)

Changed Adapter name/description; Added floor support

---

dev-docs/bidmatic.md

Bidmatic adapter: fix confusing quotes

---

prebid-server/pbs-modules/index.md
prebid-server/pbs-modules/response-correction.md

Released with PBS-Java 3.13, fix applied in 3.14

PBS response correction module

---

dev-docs/modules/humansecurityRtdProvider.md

Use relative links in humansecurityRtdProvider

---

prebid-video/video-overview.md

Video Module: Dup removal

---

dev-docs/bidmatic.md

- fixed page title
- changed userId support display value (was "none")

Bidmatic adapter: text changes 

---

dev-docs/bidders/easybid.md

Add Easybid Bidder docs

---

dev-docs/modules/gameraRtdProvider.md

Adding docs for the new Gamera Rtd Submodule.

Gamera Rtd Provider: Initial release

---

dev-docs/bidders/revbid.md

Adkernel: documenting RevBid alias

---

dev-docs/bidders/adgrid.md

Airgrid add Video Support

---

_includes/disqus_addon.html
_layouts/api_prebidjs.html
_layouts/bidder.html
_layouts/internal_api_prebidjs.html
_layouts/test.html

Removing the unused disqus plugin.

Remove unused disqus plugin

---

dev-docs/modules/wurflRtdProvider.md

WURFL RTD Module: enrich the ortb2.device object with WURFL data

---

_includes/dev-docs/fingerprinting.md
dev-docs/bidders/teads.md

Let's discuss this wording before merging

teads.md: add disclosure 

---

dev-docs/bidders/spinx.md

- https://github.com/prebid/Prebid.js/pull/12460

Adkernel: documenting SpinX alias

---

dev-docs/analytics/yandex.md

Yandex Metrica Analytics: updated links to the interface

---

dev-docs/modules/currency.md

[https://github.com/prebid/Prebid.js/pull/12364](url)

Adding auctionDelay param to currency module

---

dev-docs/bidders/spinx.md

Adkernel: updating SpinX alias doc

---

dev-docs/modules/gppControl_usnat.md

Typo in gppControl

---

_includes/code/mobile-sdk.html
docs-examples/tab-example.md

Fix tab-example

---

dev-docs/bidders/pixelpluses.md

Adkernel: documenting Pixelpluses alias

---

dev-docs/bidders/rise.md

Changes explained:
Add native support
Remove bid parameter: "is_wrapper"

Rise: Update bidder docs

---

dev-docs/bidders/blue.md

Blue: Add placementId bidder param

---

dev-docs/bidders/nextMillennium.md

https://github.com/prebid/Prebid.js/pull/12421

nextMillenniumBidAdapter: Added supply chain support

---

dev-docs/bidders/epsilon.md

Update for audio support
- [ X] update bid adapter

Epsilon: enable audio

---

dev-docs/bidders/rxnetwork.md

Adkernel: documenting RxNetwork alias

---

dev-docs/bidders/insticator.md

Insticator: Update doc to support PBS

---

dev-docs/bidders/artechnology.md

Add new alias Artechnology
Prebid.js: https://github.com/prebid/Prebid.js/pull/12609
Prebid-server: https://github.com/prebid/prebid-server/pull/4123

Attekmi: new alias Artechnology

---

dev-docs/modules/userid-submodules/lotame.md

Fix trademark typos

---

dev-docs/bidders/smartadserver.md

Confirmed in slack with @jefftmahoney on this change

Remove Equative aliasCode from Smartadserver

---

dev-docs/bidders/adport.md
dev-docs/bidders/bidsmind.md
dev-docs/bidders/mobupps.md

https://github.com/prebid/prebid-server/pull/4018

AdverxoAdapter: Change pbs to true

---

dev-docs/modules/permutiveRtdProvider.md

Ensures docs are up to date & have clear instructions
[Matching PR in Prebid.js](https://github.com/prebid/Prebid.js/pull/12660)

Permutive RTD Module: updates GDPR docs #12660 

---

dev-docs/bidders/goldbach.md

Updated Goldbach Bidder Adapter
connecting to new backend
using custom outstream video player
PR in Prebid.js repo: https://github.com/prebid/Prebid.js/pull/12540

Goldbach adapter update

---

dev-docs/bidders/madsense.md

MadSense Bidder Adapter
https://github.com/prebid/Prebid.js/pull/12546

Submit MadSense Adapter

---

dev-docs/bidders/oms.md

OMS Adapter: add video to media types list

---

dev-docs/bidders/kueezrtb.md

https://github.com/prebid/prebid-server/pull/4038

Added support for pbs in kueezrtb bid adapter.

---

dev-docs/bidders/xe.md

xeworks docs: change prebid_member flag

---

dev-docs/bidders/adnuntius.md

Adds documentation for our new support for native ads.

Adnuntius Bid Adaptor: doco on our new support for native ads

---

prebid-mobile/pbm-api/android/pbm-targeting-android.md
prebid-mobile/pbm-api/ios/pbm-targeting-ios.md

Prebid event handler feature documentation. [iOS](https://github.com/prebid/prebid-mobile-ios/pull/1035) and [Android](https://github.com/prebid/prebid-mobile-android/pull/814) PRs.

Prebid event handler for mobile platforms

---

prebid-mobile/pbm-api/android/pbm-targeting-android.md
prebid-mobile/pbm-api/ios/pbm-targeting-ios.md

* iOS PR - https://github.com/prebid/prebid-mobile-ios/pull/1092
* Android PR - https://github.com/prebid/prebid-mobile-android/pull/822

External user id documentation for mobile platforms

---

_includes/mobile/video-params.md

The associated PR in the iOS repository - https://github.com/prebid/prebid-mobile-ios/issues/1063.

Mobile: Support `plcmt` parameter

---

prebid-mobile/pbm-api/android/pbm-targeting-android.md
prebid-mobile/pbm-api/ios/pbm-targeting-ios.md

The associated PRs:
- iOS - https://github.com/prebid/prebid-mobile-ios/pull/1082
- Android - https://github.com/prebid/prebid-mobile-android/pull/823

Mobile: Support `Shared ID`

---

dev-docs/bidders/152media.md

Adkernel: documenting 152Media alias

---

dev-docs/publisher-api-reference/bidderSettings.md

JS: Update docs for `inverseBidAdjustment` -  https://github.com/prebid/Prebid.js/pull/12690

Update docs for inverseBidAdjustment

---

dev-docs/bidders/conceptx.md

Update conceptx.md with gvlId

---

dev-docs/bidders/smoot.md

https://github.com/prebid/prebid-server/pull/4148

Smoot Adapter: pbs set to true

---

_includes/astjs.html
_includes/code/web-example.html

This PR simply updates the ast.js URL used in the examples on prebid.org

update source URL for ast.js in examples

---

dev-docs/bidders/adgeneration.md

No adapter updates are required.
NovatiqID will no longer be used on the server side

update AdGeneration Doc: delete novatiq

---

dev-docs/bidders/rtbhouse.md

RTB House: updated feature list

---

_includes/disclaimers/storageAllowed.md
dev-docs/bidders/adagio.md
dev-docs/bidders/amx.md
dev-docs/bidders/bitmedia.md
dev-docs/bidders/consumable.md
dev-docs/bidders/contxtful.md
dev-docs/bidders/equativ.md
dev-docs/bidders/impactify.md
dev-docs/bidders/ix-server.md
dev-docs/bidders/ix.md
dev-docs/bidders/kargo.md
dev-docs/bidders/mediaConsortium.md
dev-docs/bidders/nexx360.md
dev-docs/bidders/taboola.md
dev-docs/bidders/triplelift.md
dev-docs/bidders/visx.md
dev-docs/modules/userid-submodules/merkle.md
prebid-mobile/pbm-api/android/pbm-targeting-android.md

also fixed a few jekyll warnings

added storageAllowed disclaimer

---

guide.md

Adds all available includes to the guide.md

Add-disclosures-to-guide

---

dev-docs/publisher-api-reference/setConfig.md

Documentation for new `allowPrerendering` and `delayPrerendering` settings - https://github.com/prebid/Prebid.js/pull/12763/

JS: prerendering settings

---

_data/sidebar.yml
dev-docs/examples/multi-format-example.md

Add an in-renderer example to the sidebar

---

prebid-server/endpoints/pbs-endpoints-pbc.md

Docs for PBC-Java 2.4 https://github.com/prebid/prebid-cache-java/releases/tag/2.4.0

PBC config updates

---

dev-docs/modules/userid-submodules/id5.md

- [x ] new feature
- [ x] Related pull requests in prebid.js or server are linked -> Paste link in this list or reference it on the PR itself
https://github.com/prebid/Prebid.js/pull/12775

ID5 UserId - added docs for canCookieSync param

---

dev-docs/modules/semantiqRtdProvider.md

https://github.com/prebid/Prebid.js/pull/12668

SemantIQ RTD Provider: initial release

---

dev-docs/bidders/cordless.md

Documenting https://github.com/prebid/Prebid.js/pull/12728

Aso Bid Adapter: documenting cordless alias

---

dev-docs/bidders/adinify.md

Prebid.js PR: https://github.com/prebid/Prebid.js/pull/12672
Prebid-server PR: https://github.com/prebid/prebid-server/pull/4164

Attekmi: add new adapter Adinify

---

dev-docs/bidders/ix.md

Updated  the PAAPI section with the module names and correct links

---

dev-docs/bidders/oms.md

OMS: added video support

---

dev-docs/bidder-adaptor.md
dev-docs/publisher-api-reference/markWinningBidAsUsed.md

Update docs related to event trackers in JS - https://github.com/prebid/Prebid.js/pull/12711

JS: update docs on `eventtrackers` and `markWinningBidAsUsed`

---

dev-docs/bidders/bidtheatre.md

Bidtheatre Bidder Adapter: pbs support

---

dev-docs/bidders/seedtag.md

Seedtag Bidder Adapter: pbs support

---

dev-docs/bidders/mediago.md

Upate mediago.md

---

dev-docs/bidders/dailymotion.md

Dailymotion bid adapter: add ortb converter and floor price support

---

dev-docs/bidders/artechnology.md

Prebid-server PR: https://github.com/prebid/prebid-server/pull/4165

Artechnology: add PBS support

---

dev-docs/modules/userid-submodules/pubmatic.md

- Documentation for the new PubMatic User ID submodule: https://github.com/prebid/Prebid.js/pull/12828

PubMatic User ID Submodule: Documentation

---

.github/workflows/code-path-changes.yml
.github/workflows/scripts/codepath-notification
.github/workflows/scripts/send-notification-on-change.js

As discussed in committee, I copied the alert notification workflow from PBS to the docs repo and seeded the config with the most active Prebid board members.

docpath change alert workflow

---

dev-docs/bidders/yieldone.md

YieldOne Bid Adapter: add UID2.0 support and update email.

---

dev-docs/bidders/zeta_global_ssp.md

Zeta Global SSP: update supported modules, media types, PBS params.

---

dev-docs/bidders/1accord.md
dev-docs/bidders/easybid.md
dev-docs/bidders/nexx360.md
dev-docs/bidders/prismassp.md

Add Prismassp Bidder docs

---

_data/sidebar.yml
dev-docs/userId-module.md

First attempt at developer docs for userID modules - https://github.com/prebid/prebid.github.io/issues/5893

JS: userID developer documentation

---

_includes/mobile/adunit-config-android.md
_includes/mobile/adunit-config-ios.md

Related issues:
- iOS: https://github.com/prebid/prebid-mobile-ios/issues/790

Mobile: Support Native Impression Tracking

---

dev-docs/bidders/epsilon.md

- [ X] update bid adapter
- [ X] Related pull requests in prebid.js or server are linked -> https://github.com/prebid/Prebid.js/pull/12851

Epsilon: add native support

---

dev-docs/bidders/illumin.md

disable download on illumin adapter

---

dev-docs/bidmatic.md

Bidmatic adapter: text changes

---

dev-docs/modules/wurflRtdProvider.md

WURFL Rtd Provider: adds Expected Behavior section

---

dev-docs/bidders/mediaeyes.md

MediaEyes Bid Adapter: initial release

---

dev-docs/bidders/inmobi.md

InMobi : Update inmobi.md for optional parameters addition 

---

dev-docs/bidders/adipolo.md

adipolo: uppercase bidder title

---

dev-docs/bidders/vistars.md

Vistars bid adapter

---

dev-docs/bidders/robusta.md

RobustaBidAdapter: docs

---

dev-docs/modules/debugging.md

Spell mistake fixed in the debugging module

---

dev-docs/bidders/mobilefuse.md

Related PRs:
- https://github.com/prebid/Prebid.js/pull/13034
- https://github.com/prebid/prebid-server/pull/4320

Indicate MobileFuse support for pbjs

---

dev-docs/analytics/browsi.md
dev-docs/modules/browsiRtdProvider.md

browsi rtd provider updates

---

dev-docs/modules/enrichmentLiftMeasurement.md

[https://github.com/prebid/Prebid.js/pull/12980](https://github.com/prebid/Prebid.js/pull/12980)

Enrichment lift measurement module

---

_includes/body-end.html

Unclear how the Algolia changed, but this key works better in my local environment.

updating algolia api key

---

dev-docs/bidders/adtrgtme.md

Adtrgtme Bid Adapter: documentation changes

---

dev-docs/bidders/mediaforce.md

Mediaforce Bid Adapter: add documentation for video support

---

dev-docs/modules/browsiRtdProvider.md

browsi rtd provider fixes

---

dev-docs/bidders/logicad.md

https://github.com/prebid/Prebid.js/pull/13077

Adding supported schain to logicad bid adapter documentation

---

dev-docs/bidders/eplanning.md

EPlanning: Update bidder docs information

---

dev-docs/bidders/taboola.md
dev-docs/modules/userid-submodules/taboola.md

add taboolaId user id submodule documentation

---

dev-docs/bidders/fwssp.md

Update fwssp bid adapter dev-docs for new fwsspBidAdapter.
- [x ] new bid adapter
- [x ] Related pull requests in prebid.js or server are linked - https://github.com/prebid/Prebid.js/pull/13381
- [x ] For new adapters check [submitting your adapter docs](https://docs.prebid.org/dev-docs/bidder-adaptor.html#submitting-your-adapter)

Update fwssp dev-docs for Prebid.js fwsspBidAdapter

---

dev-docs/modules/userid-submodules/pubmatic.md

PubMatic ID System: Fixed typo in config example

---

dev-docs/bidders/ogury.md

Related pull request on PR on Prebid Server side https://github.com/prebid/prebid-server/pull/4314

Ogury: set pbs_app_supported to true

---

dev-docs/bidders/relevatehealth.md

relevatehealth : removed user_id compulsion and used common library

---

dev-docs/bidders/zeta_global_ssp.md

- [ X] new feature
- Related pull requests in prebid.js or server are linked:
https://github.com/prebid/Prebid.js/pull/13341
https://github.com/prebid/prebid-server/pull/4389

Zeta SSP Adapter: add GPP support.

---

dev-docs/modules/userid-submodules/utiq.md

fix typo on bidRequestUserId on utiq.md

---

dev-docs/bidders/kuantyx.md

Kuantyx Adapter: endpoint example update

---

.github/workflows/scripts/codepath-notification

Add Teads to the codepath-notification to be notified of changes to our bidder doc

Add Teads to codepath-notification

---

dev-docs/bidders/criteo.md

Remove mentions of "alpha phase" in prebid server documentation of Criteo bid adapter.

Criteo bid adapter - Update prebid server documentation

---

dev-docs/bidders/dailymotion.md

Update contact email for public Dailymotion bid adapter docs
No items apply, we'll update our MD doc on Prebid.js repo to align with this PR in the short future to include new documentation for our support of oRTB fields

Dailymotion bid adapter: update contact email

---

dev-docs/bidders/showheroes-bs.md

Prebid.js PR: https://github.com/prebid/Prebid.js/pull/13694

add banner support for showheroes

---

dev-docs/bidders/adipolo.md

PR: https://github.com/prebid/Prebid.js/pull/13660

Adipolo Bid Adapter: update tcfeu support

---

dev-docs/modules/floors.md

Typo in floors.md

---

dev-docs/bidders/bwx.md

Update: bwx.md

---

prebid-mobile/pbm-api/android/pbm-plugin-renderer.md

added inmobi mobile plugin renderer

---

dev-docs/bidders/valuad.md

- https://github.com/prebid/Prebid.js/pull/13832

Valuad Bid Adapter: Update tcf support

---

dev-docs/modules/userId.md

Fix typo in userId.md

---

dev-docs/bidders/mediayo.md

MediaYo: new adapter

---

dev-docs/bidders/uniquestWidget.md

UNIQUEST Widget Bid Adapter: initial release 
