dev-docs/examples/custom-price-bucket.md

Fix typo in custom pricing example

---

dev-docs/bidders.md

This param was supported in the adapter, but not listed in the docs.

added 'position' to rubicon params

---

_includes/default-keyword-targeting.md
adops/before-you-start.md
dev-docs/publisher-api-reference.md

- Moved default keyword targeting into a shared page so maintenance can
occur in one place.
- Revised section 2, on one set of line items for all bidders vs.
one set per bidder.
Addresses issue #15.

Update ad ops intro page with ad server key-values

---

dev-docs/bidders.md

Added bidfloor and server params, added example network id, reshuffled all params in vague order of importance.

Updated AOL Adapter docs with bidfloor and server fields

---

dev-docs/bidders.md

Also updated example to string to be consistent with Prebid release notes (although bidFloor param can accept both string or decimal), and to acknowledge that it was added in 0.8.1.

Updated AOL docs to correct bidFloor parameter capitalization

---

_layouts/example.html
dev-docs/examples/simplified-price-bucket-setup.md
dev-docs/publisher-api-reference.md

Also:
- Update examples template with a link
- Update API reference so `pbjs.setPriceGranularity()` links to the
example
Addresses https://github.com/prebid/prebid.github.io/issues/50

Add 'Simplified Price Bucket Setup' example

---

dev-docs/bidders/aardvark.md
download.md
index.md

Update to:
- Reference to supported adapters on home page
- Reference to Bidder dev documentation 
- Add Aardvark checkbox for HB adapter option in Download section

Add RTK Aardvark bidder information to Prebid Documentation

---

download.md
index.md

When I tested the download from localhost, I do get the email to download but the JS doesn't contain the bidder code for any of the existing bidders or the new addition for AdMedia. 
Production download works for existing bidders. Not sure if the Parse backend needs to be updated but can you guys test if AdMedia's bidder code gets downloaded and make necessary changes?
Thanks!

Added Admedia to home and download pages

---

dev-docs/publisher-api-reference.md

If you modify `bidderSettings`, you can't use the `setPriceGranularity`
method (it doesn't work).
Addresses https://github.com/prebid/prebid.github.io/issues/88

Note what happens if you modify `bidderSettings`

---

dev-docs/bidders/piximedia.md

Hello Team!
Based on your request to comment on our default currency, I noticed the “currency” field for our bidder was missing from our documentation.
Here is the fix!
Thanks you all!

Add currency field to Piximedia bidder documentation

---

dev-docs/bidders/roxot.md
download.md
index.md

Update to:
- Reference to supported adapters on home page
- Reference to Bidder dev documentation
- Add Roxot checkbox for HB adapter option in Download section

Add Roxot bidder information to Prebid Documentation

---

dev-docs/bidder-adaptor.md

Changes:
- Updated intro
- Added info about adding video info to your bid params, with links to
AST adaptor docs and implemntation for reference
- Light copy-edits throughout the page, added some more reference links

Update 'How to Add a New Bidder' with video info

---

dev-docs/bidder-adaptor.md
dev-docs/how-to-add-a-new-video-bidder-adaptor.md

Also update 'How to Add a New Bidder Adaptor' as follows:
- Add links to the new page
- Remove most of the video-related content in favor of linking to the
new video-specific page

Add 'How to add a new video bidder adaptor'

---

dev-docs/add-video-support-to-an-existing-bidder-adaptor.md
dev-docs/integrate-with-the-prebid-analytics-api.md

This is basically "How to add a new video bidder adaptor" with the "make
a new adaptor" steps removed.
Oh, and we bump the PID on the Prebid Analytics page to preserve ordering in the left nav.

Document adding video support to existing adapter

---

download.md

Now users can also choose which analytics adapter declaration to include as part of their custom prebid build.
This will add the field *analytics: ['analytics-adapter']* to the form data for the fownload request
Julien

adding support for analytics adapter selection in download page

---

dev-docs/bidders/inneractive.md

@rmloveland, adding a new pull request for Inneractive's adapter - instead of: https://github.com/prebid/prebid.github.io/pull/200/

docs: adding inneractive.md - Inneractive Adapter Documentation

---

dev-docs/show-prebid-ads-on-amp-pages.md

(Specifically, with a better implementation of `draw3p` that doesn't
mess with other, non-Prebid AMP units.)

Update AMP docs for pages with multiple AMP ads

---

dev-docs/analytics-ga.md

this corresponds to Prebid.js pull request 1011 - https://github.com/prebid/Prebid.js/pull/1011/files
that PR hasn't been merged yet, so this doc shouldn't be accepted until Prebid 0.22 is released

document GA sampling feature for PBJS 0.22

---

download.md

Hey guys,
Please rename "Roxot" analytics adapter to "Prebid Analytics by Roxot". It's the official name for our analytics product and we want to be consistent across different platforms. Otherwise, publishers might be confused when seeing the same product under different names. 
Could you merge it to the master as soon as the 0.22.0 prebid.js is released?
Thanks in advance.

Rename roxot adapter

---

dev-docs/publisher-api-reference.md

tweaking the wording here based on a conversation with @mkendall07 from last week
I had formerly been under the impression that the existence of _any_ bidderSetting invalidated the use of setPriceGranularity, but it's really the existence of adserverTargeting within bidderSettings.

clarifying bidderSettings/setPriceGranularity message

---

_includes/sizemapping-and-screen-widths.md
dev-docs/examples/size-mapping.md
dev-docs/publisher-api-reference.md

Add a note describing the edge cases that may occur when:
- screen size can be detected, but no mapping is defined
- screen size cannot be detected

Sizemapping: what happens when no size is defined?

---

_includes/main_nav.html
overview/analytics.md
overview/ga-analytics.md

re-wiring the Analytics menu option to point to a new landing page that lists both GA and Roxot.
It has a section for 'managed services' which is aimed at laying out the choices publishers have for other analytics and managed offerings. AppNexus may want to add an enquiry link.

updated Analytics landing page

---

dev-docs/bidders/adyoulike.md
index.md

Documentation for prebid/Prebid.js#1155

Add Adyoulike adapter

---

dev-docs/publisher-api-reference.md

@aneuway2 mind taking a look at these docs for the `aliasBidder` method?
@mkendall07 can you verify the technical accuracy of this description W.R.T. IDs registered with Prebid.js allowing you to load two adapters with the same names?
Happy to update if there is a clearer/simpler way to think about how this works, or if something is off base technically.

Add docs for `pbjs.aliasBidder()`

---

dev-docs/show-outstream-video-ads.md

Specifically, update 'Show Outstream Video Ads' to include the "no-ad-server" case as an option.

Add outstream video without an ad server docs

---

dev-docs/analytics-ga.md
dev-docs/integrate-with-the-prebid-analytics-api.md
overview/analytics.md
overview/ga-analytics.md

Specifically:
- Remove the dev instructions for integrating with GA, move towards neutrality
- Leave the GA overview because it's somewhat instructive and ripping it out would be more work
- Bring formatting/layout of analytics pages in line with newer/standard pages (TOC, general structure, 'Further Reading' links, etc.)
- Caught a few typos, etc.

Remove (some/most?) vendor-specific analytics instructions

---

index.md

SpotX was previously added to the bidder documentation via #280, but wasn't added to the list of supported partners on the Prebid homepage. Adding here...

Add SpotX to the Partners list on Prebid homepage

---

dev-docs/bidders/criteo.md

Add documentation to the [bidders' params page](http://prebid.org/dev-docs/bidders.html) for the Criteo bidder.
Fixes #326

Add Criteo bidder docs

---

dev-docs/show-video-with-a-dfp-video-tag.md
examples/video/bc-demo.html
examples/video/jwPlatformPrebidDemo.html
examples/video/jwPlayerPrebid.html
examples/video/jwPlaylistUniqueAds.html
examples/video/klt-demo.html
examples/video/ooyala-demo.html
examples/video/prebid_video_videojs_new.html

Adds video demo pages to `examples/video` directory, and updates links on `show-video-with-a-dfp-video-tag` page to point to them

Add video demo pages

---

dev-docs/bidders/aerserv.md

Adding bidder params for the AerServ adapter.
For: https://github.com/prebid/Prebid.js/pull/1538

AerServ bidder documentation

---

dev-docs/bidders.md
dev-docs/bidders/districtm.md
download.md

Hides bidders that don't have a client side JS library.

Omit s2s only adapters from the download page

---

dev-docs/publisher-api-reference.md

Answers the question "why is a bid able to get into the auction after
the timeout I set with Prebid.js?"

Add note on 'Bid Timeouts and JavaScript Timers'

---

dev-docs/prebid-1.0-API.md

Add some missing deprecations for 1.0

---

dev-docs/get-started-with-prebid-server.md

Doc update for https://github.com/prebid/Prebid.js/pull/1655

Adding secure option to s2sConfig

---

dev-docs/modules/digitrust.md

Digitrust now requires the callback argument to initialize(). Also, testing showed that putting the init code at the top is necessary for the ID to be there in time for the auctions.

Streamlining and fixing the digitrust init code

---

adops/setting-up-prebid-video-in-dfp.md

Specifically:
- Add note to Video ad ops page describing why the creative URL is a link to Prebid Cache
- Link from there to the longer (existing) description of why the cache is needed

Make it more clear that Prebid Cache is needed

---

dev-docs/modules/digitrust.md

A test found that the adapters weren't aligned with these instructions. Fixed.

DigiTrust module update

---

dev-docs/bidder-adapter-1.md

Documenting the changes from https://github.com/prebid/Prebid.js/pull/1748

Adding server response examples

---

dev-docs/bidder-adapter-1.md

When looking over https://github.com/prebid/Prebid.js/pull/1722, I realized that https://github.com/prebid/Prebid.js/pull/1748 also changed the `getUserSyncs` format.
When I went to update them in the docs here, I found that we never actually mentioned that param at all. This addresses that.

Better getUserSync docs

---

dev-docs/show-native-ads.md

Scope of work here is:
- add info on `cta` field
- update example code to use `mediaTypes: { native ...` API
- add some links to our list of bidders with native support
Let me know what you think - thanks!

Doc native params on `mediaTypes` (incl. `cta`)

---

examples/video/bc-demo.html
examples/video/ooyala-demo.html

Skippable videos are not supported in IMA3 SDK on iPhone devices. A logic to play either skippabe or not skippable video added to demo html depend on the client device.

VIDNY-244. Not skippable video will be targeted on iOS.

---

examples/video/videojs-demo.html

Many fixes happened since 5.9.x in videojs in particular for iOS support:
https://github.com/wikimedia/mediawiki-extensions-TimedMediaHandler/commit/69c91c59fb4034a55d8aa6cbc41fe7c285b8ae13
Updated version of the videojs script from 5.9.2 to 6.4.0 in the html... that fixed issue.

VIDNY-261. Updated version of the videojs in html's href.

---

dev-docs/get-started-with-prebid-server.md

Add section with example showing that in order to show video ads from
your Prebid Server setup you need to use OpenRTB params in your ad unit
setup.
Added a couple of anchor links to subsections to make things a little
easier.

Document Prebid Server video requests

---

dev-docs/publisher-api-reference.md

This PR marks deprecated methods, & notes that they will be removed with the 1.0 release.
It also:
- Notes that the 1.0 release is scheduled for Q4 2017
- Notes that pre-1.0 method docs will be deleted, likely in early 2018
- Adds docs for the only missing deprecated method, `pbjs.addBidResponse`, for completeness

Update Publisher API Reference to mark which methods are deprecated and shall be removed in 1.0

---

dev-docs/publisher-api-reference.md

Relates to https://github.com/prebid/Prebid.js/pull/1663
@matthewlane Would you mind taking a look at these docs?  They still need some refinement and shortening.  I'm trying to figure out how to make them shorter given the interaction of `options.params` vs. `options.url` vs. Prebid Cache being enabled or not.
In the meantime, I'd appreciate if you could take a look!  Specifically:
- Are there any technical errors in what I've written?
- Are you able to answer my questions marked with 'FIXME' in this PR?
- I'm a little confused about the interaction of cache with URL usage - sounds like the big thing is that the bidder must return a `vastUrl` if cache is disabled, right?  Any thoughts on how to make that explanation simpler, or just a comment on how you tend to think about how it works, …

Document `pbjs.adServers.dfp.buildVideoUrl` update to accept ad server URL

---

dev-docs/bidder-adapter-1.md

Adds a new subsection to the 'Supporting Video' section of the bidder adapter instructions describing how to check ad units for the outstream context so you can return a renderer as needed.

Tell adapters how to serve outstream ads

---

dev-docs/examples/adunit-refresh.md
examples/adunit_refresh_example.html

This code sample was submitted by an AppNexus colleague to address the following issues in
the old example:
- It was using the old DFP initalization code (loading 'gpt.js' in `initAdServer`), which will cause higher latency.  New best practice is to use `disableInitialLoad`.
- It declared 2 ad units, but only loaded one.
- Implementation code was not following the usual code implementation (order of code, etc.) which can be confusing.

Update infinite scroll example

---

dev-docs/integrate-with-the-prebid-analytics-api.md

@rmloveland On http://prebid.org/dev-docs/integrate-with-the-prebid-analytics-api.html it looks like I didn't get the formatting quite right for the analytics 1.0 note because the two points aren't inside the warning box. Added a blank line which I think separates two lists in markdown, hoping this fixes it

Fix analytic note formatting

---

overview/analytics.md

A refresh of links for preferred pages. The pricing page at this moment is basically empty, but will have content by the time this is released on the Prebid.org site. The content will only be a description of pricing structure and high level terms.

Update Links for Analytics Page

---

dev-docs/bidders/prebidServer.md
dev-docs/get-started-with-prebid-server.md

These are changes per new 1.0 requirements, specifically the `endpoint` url no longer has a default value and needs to be specified. 
Also added a link since we had duplicate information.

Prebid Server dev docs updated per 1.0 changes

---

dev-docs/prebid-1.0-API.md

This PR includes:
- Various copy edits
- A few minor spelling fixes
- Rewording a few sections slightly for clarity
- Bigger: Remove all uses of the word "deprecated", state that functions/variables "will be removed", since "deprecated" implies that they [will be removed in the future (per Wikipedia)](https://en.wikipedia.org/wiki/Deprecation#Software_deprecation), but in this case they are being removed as part of the 1.0 release (IIUC)

Updates to 'Prebid 1.0 Publisher API changes'

---

dev-docs/modules/currency.md
dev-docs/modules/dfp_express.md
dev-docs/modules/dfp_video.md
dev-docs/modules/digitrust.md
dev-docs/modules/index.md
dev-docs/modules/s2sTesting.md
download.md

This adds an option for bundling modules when you compile prebid.js
Note: This needs a corresponding change on the download endpoint. Please don't merge directly

Added modules to download page

---

dev-docs/publisher-api-reference.md

User syncing is now controlled via a call to `pbjs.setConfig()`.
This PR moves the existing user sync docs into a subsection of that method's documentation.
The description of the default behavior was changed to match the behavior of the code.
In addition, some copy editing and cleanup was done.

Move user sync docs into appropriate section of API reference

---

dev-docs/prebid-1.0-API.md

A few suggestions towards making the document easier to understand, and also adding the "default endpoint" section.

Default Endpoints, minor revisions

---

dev-docs/bidders/adsparc.md
dev-docs/bidders/connectad.md
dev-docs/bidders/insticator.md
dev-docs/bidders/onefiftytwo.md

Adding documentation for aliases: AdSparc and Insticator.
Should be merged once: https://github.com/prebid/Prebid.js/pull/1802 is accepted.

Add AdSparc and Insticator.

---

dev-docs/show-video-with-a-dfp-video-tag.md

Was originally going to add this info in
https://github.com/prebid/prebid.github.io/pull/422
but it fits better here.

Update Prebid Video docs: cache is now toggle-able

---

dev-docs/show-video-with-a-dfp-video-tag.md

This PR addresses https://github.com/prebid/prebid.github.io/issues/482
However, it cannot be merged unless/until we update the Prebid.js version that is on the CDN at 
https://acdn.adnxs.com/prebid/not-for-prod/prebid.js
to 1.0
(Unless there is another CDN URL we are using for 1.0, and we're leaving that one pre-1.0 for now, in which case I will update this PR to use the new URL.)

Update prebid cache usage to follow 1.0

---

dev-docs/show-native-ads.md
dev-docs/show-outstream-video-ads.md
dev-docs/show-video-with-a-dfp-video-tag.md
examples/index.html
examples/native/index.html
examples/video/index.html

This makes it easier for a reader to click through and see all of the
video/native/etc. examples in one place.

Add index files to hosted examples

---

dev-docs/bidders/tremor.md

There was a stray `|` character in there that was causing my editor's
table formatting mode to go astray.

Fix Tremor bidder params table

---

_config.yml

When running through the initial setup steps in the repo's README, I was encountering an error when attempting the run the server with the latest version of Jekyll 3.3.0.
This error was addressed by adding `vendor` to the exclude list in the `_config.yml` file.  Submitting this change so it's part of master and addresses this issue going forward.
See related issue #521.

update exclude list in _config.yml

---

adops.md
dev-docs/publisher-api-reference.md

@rmloveland 
I attempted to start adding some docs here. I have a feeling I missed about 20 places this is probably documented but I wasn't sure what the grep for...

add some hb_source docs

---

.gitignore

As a follow-up to the changes introduced through #522 & #523, I'd to submit this change to the .gitignore file to include to new directories that don't need to be tracked.  
These directories are made as a result of the `bundle install --path vendor/bundle` command and are not relevant to the master branch when doing commits.

update gitignore file 

---

dev-docs/bidder-adaptor.md

Related to confusion here: https://github.com/prebid/Prebid.js/pull/1908

clarified interpretResponse requestId

---

dev-docs/bidder-adaptor.md
dev-docs/publisher-api-reference.md

Docs for https://github.com/prebid/Prebid.js/pull/1991. Let me know if there are other areas of the documentation I missed that I can update as well

Add multiformat ad unit information

---

dev-docs/bidder-adaptor.md

Feedback requested on wording, alert severity [danger/warning/info] and location of note

Add note about non-1.0 adapters

---

dev-docs/bidders/medianet.md
index.md

Documentation for Media.net PR :  [prebid/Prebid.js#2038  ](https://github.com/prebid/Prebid.js/pull/2038)

Media.net bidder added

---

dev-docs/bidders/pubmatic.md

Updates for PubMatic 1.0 adapter

PubMatic 1.0 Adapter Updates

---

dev-docs/bidders/gumgum.md

Hi Prebid.
GumGum would like to update the dev-doc for its Adapter, now that we support prebid 1.0

Update dev-docs gumgum.md file to include prebid 1.0 support flag

---

dev-docs/show-outstream-video-ads.md

Docs update for https://github.com/prebid/Prebid.js/pull/2025

Add section on renderer.options

---

dev-docs/examples/adjust-price.md
dev-docs/examples/adunit-refresh.md
dev-docs/examples/basic-example.md
dev-docs/examples/brightcove-example.md
dev-docs/examples/custom-price-bucket-using-setpricegranularity.md
dev-docs/examples/custom-price-bucket.md
dev-docs/examples/full-page-refresh.md
dev-docs/examples/jw-cloud-example.md
dev-docs/examples/jw-selfhost-example.md
dev-docs/examples/kaltura-example.md
dev-docs/examples/ooyala-example.md
dev-docs/examples/outstream-video-example.md
dev-docs/examples/send-all-bids.md
dev-docs/examples/simplified-price-bucket-setup.md
dev-docs/examples/size-mapping.md
dev-docs/examples/use-prebid-with-appnexus-ad-server.md
dev-docs/examples/videojs-example.md
dev-docs/getting-started.md
examples/adunit_refresh_example.html

As a follow-up to the #528, these are additional updates for the multiformat changes - notably updates to the various JSFiddles used across the dev-docs/examples area of the site.

updates to JSFiddle examples for multiformat updates

---

dev-docs/bidders/yieldlab.md

This is the documentation for new prebid Adapter - Yieldlab. Related to this PR - https://github.com/prebid/Prebid.js/pull/1967

Add Yieldlab adapter docs to website

---

dev-docs/bidders/c1x.md

We've upgraded our adapter to Prebid v1.0 so we need to update the bidder's param doc

Update C1X Adapter docs 

---

dev-docs/modules/index.md
dev-docs/modules/pubCommonId.md

Add doc for Publisher Common ID module.  This creates and stores a unique user id in the publisher's (first party) domain.  When enabled, the ID is appended to the bid requests for all adapters, which can pass the id for server-side user matching.

Add doc for Publisher Common ID module

---

dev-docs/bidders/ias.md

Adding a new adapter for IAS. The adapter code change PR: https://github.com/prebid/Prebid.js/pull/2056

Pet 214 add ias adapter doc

---

dev-docs/bidders/beachfront.md

Removes note about video only support. The beachfront bidder will also support banner ads.

Update beachfront doc

---

dev-docs/bidders/yieldbot.md

Adds metadata field `prebid_1_0_supported` to Yieldbot bidder developer docs.
***Ref:***
- https://github.com/prebid/Prebid.js/pull/2135#issuecomment-369955633

Yieldbot bidder doc pbjs 1.0 support metadata

---

dev-docs/get-started-with-prebid-server.md

Missing commas in the example for copy/pasters (like myself).

fixed typo of missing commas in json for example

---

dev-docs/bidder-adaptor.md

Adapters may not override standard ad server targeting: Do not override, or set default values for any of the standard targeting variables: hb_adid, hb_bidder, hb_pb, hb_deal, or hb_size.

Added adapter rule

---

dev-docs/bidders/yieldlab.md

Changed params to the actual naming used by Yieldlab to avoid confusion from customers. 
Corresponding to Pull Request: https://github.com/prebid/Prebid.js/pull/2231

Update Yieldlab params with new naming

---

dev-docs/bidders/freewheel.md

When updating our bidder adaptor to our new company name, there was some mistake in the documentation,.
I've remove the stickyadtv md file, replacing it with freesheel-ssp doc.
also added **prebid_1_0_supported:true** in it.
(as suggested by Roffray in this thread: https://github.com/prebid/prebid.github.io/issues/620#issuecomment-371770251 )

update freewheel bider adapter doc

---

dev-docs/show-prebid-ads-on-amp-pages.md

Moved load-cookie file to different cdn since jsdelivr serves html file with content type text/plain.

Update user sync file cdn location

---

dev-docs/bidder-adaptor.md

Documentation for  [Prebid.js#2279](https://github.com/prebid/Prebid.js/pull/2279)

Adding onTimeout added in Bidder spec

---

adops/setting-up-prebid-video-in-dfp.md
dev-docs/publisher-api-reference.md

Update docs in reference to https://github.com/prebid/Prebid.js/pull/2273 -- video hb_cache_id and hb_uuid.
Note that this shows more diffs than there really are -- the original adops/setting-up-prebid-video-in-dfp.md file was DOS-formatted with ^M chars at the end of each line, which I removed. Focus on the ## Creative Setup section.

video hb_cache_id and hb_uuid

---

dev-docs/bidders.md

Currently on the http://prebid.org/dev-docs/bidders.html page, when you mouse over any of the bidders (where they have the their param details) the text displays lines as if it's a link.
This PR fixes the anchor tag that wasn't being closed properly and allows the bidder details information to appear as normal text.

fixed unclosed anchor on bidders page

---

dev-docs/modules/consentManagement.md

Adding note to encourage adapters to submit a docs PR along with their adapter changes PR when they add support for GDPR.

add note to update docs repo for new gdpr adapters

---

dev-docs/bidders/adform.md

Update the Adform bidders page to flag they now support GDPR.
original PR in PBJS: https://github.com/prebid/Prebid.js/pull/2396

update adform bidders page for GDPR support

---

_includes/send-all-bids-keyword-targeting.md
adops/deals.md
dev-docs/bidders/indexExchange.md
dev-docs/publisher-api-reference.md

Updated the references on the following pages:
* http://prebid.org/adops/send-all-bids-adops.html
* http://prebid.org/adops/deals.html
* http://prebid.org/dev-docs/bidders.html
* http://prebid.org/dev-docs/publisher-api-reference.html

Updated docs for Index Exchange's Prebid 1.0 adapter + GDPR support

---

dev-docs/bidders/rubicon.md

This adds documentation about new bidder param `latLong` for the rubicon adapter added here: https://github.com/prebid/Prebid.js/pull/2508

added latLong documentation for rubicon

---

dev-docs/bidders/sharethrough.md

Since the Sharethrough adapter is up to date here: https://github.com/prebid/Prebid.js/pull/2563#pullrequestreview-121911292
This updates the sharethrough bidder README.

Add Sharethrough GDPR compliance info

---

_includes/main_nav.html

Rename Videos option under Support menu to "Training Videos" to avoid confusion, per Issue #712

Issue #712, Support/Videos menu option was confusing

---

dev-docs/bidders/prebidServer.md
dev-docs/get-started-with-prebid-server.md
dev-docs/prebid-1.0-API.md
dev-docs/publisher-api-reference-old.md
dev-docs/publisher-api-reference.md

`/auction` on PBS was replaced by `/openrtb2/auction` quite a while ago.
This just updates the docs to fix it. Looks like my IDE trimmed a bunch of trailing whitespace too. I can undo this if it makes review easier, but... we probably shouldn't have trailing whitespace anyway.

Update s2sconfig references

---

dev-docs/bidders/brealtime.md

Submitting approval to list bRealTime as a GDPR supported adapter on the Prebid GDPR consent management module page. We are leveraging the Appnexus adapter which has GDPR support included and also have a number of initiatives internally to be our company is fully GDPR complaint prior to the 25th. 
Please let me know if anything else is needed to be listed. Thank you!

adding gdpr support flag to brt alias of apn

---

dev-docs/bidders/indexExchangeLegacy.md

This is for support on the download page.

added index legacy back

---

dev-docs/modules/consentManagement.md

* Inject __cmpLocator iframe
* Add mandatory ping function
* Stringify JSON if required
* Add support for IE8 and below
* Wrap into anonymous self-executing function
* Add cmpLoaded flag

Update non-IAB compliant CMP example

---

dev-docs/publisher-api-reference-old.md
dev-docs/publisher-api-reference.md

These same examples are also in adunit-reference.md but they were correct in that file, so I copied them to publisher-api-reference.md and publisher-api-reference-old.md where they were incorrect.
More generally, it might make sense to reorganize the docs so the same information is not copy/pasted in multiple places, but I wouldn't want to do that in my first PR :)

Fix typos in examples (bids is not a child of mediaTypes)

---

dev-docs/publisher-api-reference.md

Adds additional examples and information on `onEvent` handlers and also details out what the value of the prebid server timeout should be and how that relates to Prebid.js

API Reference: Adding additional info on onEvent handlers, and PBS timeout

---

dev-docs/bidder-adaptor.md

"RealVu Analytics" row added in front of "Vuble" in accordance with the analytic adapters order on http://prebid.org/download.html

Add "RealVu Analytics" row  to "Analytics for Prebid" table

---

dev-docs/bidders/underdogmedia.md

underdogmedia bid adapter now supports gdpr module.
relevant pull request:
https://github.com/prebid/Prebid.js/pull/2679

gdpr-support for underdogmedia

---

assets/js/prebid-server-api.js
dev-docs/get-started-with-prebid-server.md

This is a proof-of-concept to show how docs can be dynamically generated using the Prebid Server API.
This just adds a list of Prebid Server bidders to the top of the page. When we release new versions, it will update automatically.
I know @jeanstemp plans to revamp the PBS pages in general, so I'm sure there are better places than this... but at the moment, I don't really know where they would be :x.

Added a list of Prebid Server adapters

---

dev-docs/bidders/gambid.md

This PR adds documentation for Gamoshi's Gambid adapter, recently merged back to Prebid.js and released in [`1.13.0`](https://github.com/prebid/Prebid.js/releases/tag/1.13.0) via PR [#2625](https://github.com/prebid/Prebid.js/pull/2625).

Add Gamoshi's Gambid adapter documentation

---

dev-docs/publisher-api-reference.md

Documentation for https://github.com/prebid/Prebid.js/pull/2743

setConfig max requests per origin documentation

---

dev-docs/get-started-with-prebid-server.md

Documentation updates related to https://github.com/prebid/Prebid.js/pull/2704
Add notes about how to handle PBS only bidders for anyone using PBS.

add notes on handling pbs only bidders

---

dev-docs/publisher-api-reference.md

Update the userSync API and examples to reflect new field called `filterSettings` and to remove references to following eventually-deprecated fields:
- iframeEnabled
- pixelEnabled
- enabledBidders
Related to proposed changes in:
https://github.com/prebid/Prebid.js/pull/2499

update usersync documentation with new filterSettings config object

---

dev-docs/bidders/gambid.md

This is a minor change to the adapter title from "Gamoshi Gambid" to simply "Gamoshi" as it's commonly used.
This will also affect the checkbox in the Download page, right? (in addition to the "Bidder's Params" page)

Change 'Gamoshi Gambid' to simply Gamoshi

---

assets/js/prebid-server-api.js
dev-docs/prebid-server-bidders.md

Adds another option to the PBS Bidders dropdown.
This one shows the contact email and supported media types per platform.

Add PBS bidder info

---

dev-docs/show-prebid-ads-on-amp-pages.md

- Update Prebid Ads documentation with fallback image for iframe to prevent the AMP requirement for 600px/7% from top.
- Add additional information on how to debug

Updated User Sync, Add Debugging to AMP setup doc

---

dev-docs/publisher-api-reference.md

See https://github.com/prebid/Prebid.js/pull/2772

Document the new timedOut parameter for bidsBackHandler

---

dev-docs/bidders/rubicon.md

also removed the 'version' column from the parameter table.

documenting Rubicon SRA support

---

dev-docs/publisher-api-reference.md

Docs for https://github.com/prebid/Prebid.js/pull/2864

Disable ajax timeout docs

---

dev-docs/bidders/sortable.md

Adapter PR: https://github.com/prebid/Prebid.js/pull/2824

Add documentation on Sortable adapter

---

examples/video/jwplatform-pbserver-demo.html
examples/video/jwplayer-pbserver-demo.html
examples/video/jwplayer7-pbserver-demo.html
examples/video/jwplaylist-pbserver-demo.html
examples/video/kaltura-pbserver-demo.html
examples/video/ooyala-pbserver-demo.html
examples/video/videojs-pbserver-demo.html

The Prebid Server Video examples weren't actually using Prebid Server, because `s2sconfig.enabled` wasn't set to true.
This fixes that.

Set the s2sconfig to enabled in the video examples.

---

README.md
dev-docs/publisher-api-reference.md
dev-docs/show-video-with-a-dfp-video-tag.md

Documentation for a new (global) function pbjs.markWinningBidAsUsed(adUnitCode) as discussed in https://github.com/prebid/Prebid.js/issues/2282

pbjs.markWinningBidAsUsed(adUnitCode) documentation

---

prebid-mobile/code-integration-android.md

Important to add PrebidServerAdapter package in proguard exemptions or you will get an error during the Prebid initialisation:
UNABLE_TO_INITIALIZE_DEMAND_SOURCE("Unable to instantiating the adapter.")
It is indeed failing to access PrebidServerAdapter package and raise an error when trying to create an instance of the class "org.prebid.mobile.prebidserver.PrebidServerAdapter" (line 141 of prebid.java)

Proguard exemptions

---

dev-docs/bidders/aja.md

This adds documentation to the AJA bidder adapter, in relation to https://github.com/prebid/Prebid.js/pull/2934

Add AJA adapter docs

---

dev-docs/faq.md

In lieu of updated timeouts used on the http://prebid.org/dev-docs/examples/basic-example.html page, we should update the blurb we have on timeout usage on the FAQ page (to give some additional context as to what's going on).
Also should help to address the question raised in: https://github.com/prebid/Prebid.js/issues/3007

update timeout information on faq

---

dev-docs/bidders/aol.md

Add mobile bid parameters to the AOL adapter - these have been supported since May 2017 but were only documented against the ONE Mobile alias.

AOL adapter - add mobile bidder parameters

---

dev-docs/bidder-adaptor.md

@jaiminpanchal27 Please take a look and let me know if I got this right or I missed anything. Thanks!

RAD-2446: add referrer detection info for new refererInfo property

---

dev-docs/modules/pubCommonId.md

Add a section for the publisher common id that describe the usage of individual user opt-out.

Support publisher common id opt_out cookie

---

dev-docs/modules/currency.md
dev-docs/publisher-api-reference.md

@jeanstemp and @mkendall07 - please take a look at this modification to the publisher API doc ... thought it would be nice to have all the setConfig() options linked from the main API doc, and the currency options were over in the module-specific page.

adding defaultRates, a FAQ, and linking to setConfig documentation

---

dev-docs/bidders.md

This section on PBS bidders has its own page now... and it's misleading for several reasons.
1. `districtm` isn't a Bidder... it's an alias (albeit a well-known one)
2. The list is based on legacy bidders, which is way out of date.
2. None of the links point to code which still exists.

Removing some stale PBS docs

---

dev-docs/publisher-api-reference.md

Updated documentation to reference `adUnit.mediaTypes` for size config over`adUnit.sizes` for updated code here: https://github.com/prebid/Prebid.js/pull/3134

update size config to mention mediaTypes over sizes

---

dev-docs/bidders/pubnx.md

Merged into Prebid.js in https://github.com/prebid/Prebid.js/pull/3064

Add docs for new Serverbid bidder alias PubNX

---

dev-docs/publisher-api-reference.md

Removed `cookieSyncDelay` from `config` since we have more configuration options now with the `userSync` object. 
Documents https://github.com/prebid/Prebid.js/issues/3061.

removed `cookieSyncDelay` from `config`

---

dev-docs/bidders/prebidServer.md
dev-docs/publisher-api-reference.md

Related to https://github.com/prebid/Prebid.js/issues/2998

removing references to cookieSet

---

adops/setting-up-prebid-video-in-dfp.md
dev-docs/publisher-api-reference.md

- removing Rubicon URL in advance of our coming platform change
- hb_cache_id was never implemented for video - removing that for now until all the pieces are in place

update cache URL

---

dev-docs/modules/currency.md

Referenced in this issue: https://github.com/prebid/Prebid.js/issues/3176
I think it was a copy and paste error that should say currency, not DFP express.

Fix mistype in currency docs reference DFP express code

---

_layouts/bidder.html
assets/css/style.css

The bidder layout is missing a wrapping column for the left nav which causes them to render incorrectly, like here: http://prebid.org/dev-docs/bidders/rubicon.html 
Adding the `col-md-3` around the left nav fixes the problem.
Also added fix for anchor links.  Currently, clicking an anchor link to a fragment causes the target to fall underneath the fixed header.  The css fix in this pull-request causes the targets to be positioned so they're not underneath the fixed header when navigated to.

Fix for bidder layout and anchors tags

---

dev-docs/bidders/yieldone.md

We would like to add media_types to YIELDONE docs.
This is the code: prebid/Prebid.js#3227

YIELDONE docs - add media_types

---

dev-docs/bidders.md

"Bidders with Native and Video Demand" table was showing bidders for all media types, then listing native, video, or blank. Removed all those that were blank (not native or video).

only show bidders with native or video demand

---

dev-docs/publisher-api-reference.md

Docs for this Prebid.js change:
https://github.com/prebid/Prebid.js/pull/3291
Also changed the formatting around this section to make it a proper bullet list.

update to s2sconfig properties notes

---

dev-docs/bidders/appnexus.md

Documentation for Prebid.js PR: https://github.com/prebid/Prebid.js/pull/3314

Docs for AppNexus Debug auction

---

dev-docs/publisher-api-reference.md

Documentation for new API method added in https://github.com/prebid/Prebid.js/pull/3286

added new API method pbjs.getNoBids()

---

dev-docs/modules/pubCommonId.md
examples/modules/pub_common_id_optout.html

Update the opt-out instruction and add an example.

Add pubCommonId optout example

---

dev-docs/bidders/prebidServer.md
dev-docs/publisher-api-reference.md

[Prebid.js PR-3394](https://github.com/prebid/Prebid.js/pull/3394)
Documentation for new `setConfig` pbs option `adapterOptions`
```
setConfig({
adapterOptions: {
rubicon: { key: 'value' },
appnexus: { key: 'value' }
}
})
```

Added new setConfig option for pbs adapterOptions

---

dev-docs/modules/currency.md

Also refined the FAQ entry for "What happens if the file doesn't load on time or not at all or doesn't contain a necessary conversion"

changing currency file location

---

_data/dropdown_v2.yml
_data/sidebar.yml

proposal for updating the top and side menus as a result of https://github.com/prebid/Prebid.js/issues/3538
1) rename the 'Prebid.js/Adapter' left menu to 'Adding an Adapter'
2) with the philosophy that the top menu should have the most commonly used documents, I propose that we remove "plugins" from the Product menu and add "Publisher API" and "Bidder Params". Our new GA metrics prove these are the two most popular pages besides Download.
3) Move the "Debugging Extension" from the Product menu to the Support menu

menu tweaks

---

dev-docs/bidder-adaptor.md

Add requirement that **DFP slots may not be modified directly**. A pull request for an adapter was doing this, and the behavior was deemed not allowed.
https://github.com/prebid/Prebid.js/pull/3550#discussion_r256545608

Add required adapter convention

---

dev-docs/bidders/vmg.md

Adapter that allows VMG's publisher partners to connect DFP to the 'VMG Predict' Engine.

New Adapter VMG

---

dev-docs/bidders/indexExchange.md
dev-docs/bidders/openx.md

two bidders utilized H1, which gave them large orange headers. downgraded to H2.

Remove h1 bidders

---

dev-docs/bidders/yieldlab.md

The External Id is a dynamic reporting dimension, that can be passed through Yieldlab's adtag via the "id"-parameter. E.g. https://ad.yieldlab.net/d/1111/2222/728x90?ts=123456789&id=abc

Add External Id to the Yieldlab Bidder Doc

---

dev-docs/adunit-reference.md
dev-docs/bidders/rubicon.md

coordinate with PBJS 2.5 release

updating Rubicon video params

---

_data/sidebar.yml
dev-docs/bidder-adaptor.md
dev-docs/modules/categoryTranslation.md
dev-docs/modules/freewheel.md
dev-docs/publisher-api-reference.md
prebid-video/video-long-form.md

Fixed api typos, code blocks, added tables and updated description at some places

Long form doc updates

---

dev-docs/bidders/jcartermarketing.md

There appears to be a typo in the docs for jcm bidder params. I changed the docs to match what is in the adapter.

changed bidder param in docs to match what is in the jcmbidAdapter

---

dev-docs/bidder-adaptor.md

Clarify policy that adapters are not allowed to make their own network requests or fire their own pixels

Clarify Adapter Network Requests Policy

---

dev-docs/show-native-ads.md

`privacyUrl` is written in docs, but `privacyLink` in source code. ↓
https://github.com/prebid/Prebid.js/blob/c060a5ce9087f48f257c4a383f854e989e49dab4/src/constants.json#L74

maybe typo privacyUrl -> privacyLink

---

download.md
overview/analytics.md

[Finteza Analytics Adapter](https://github.com/prebid/Prebid.js/blob/master/modules/fintezaAnalyticsAdapter.md)
Because analytics adapters should be added manually

Add Finteza Analytics Adapter to download and overview pages

---

dev-docs/modules/pubCommonId.md

Add support for localStorage in PubCommondId module.  This is for publishers who have not yet made the switch to the new user id module.

PubCommonId - Add support for local storage

---

README.md

also removed an extra reference to PaulY. Do we really need this list. While we really do appreciate the community's input to Prebid products, this list is a pain to keep up-to-date. :-/

Removing stray suraniewiki reference

---

adops/send-all-bids-adops.md

This PR modifies the UC creative templates on http://prebid.org/adops/send-all-bids-adops.html to demonstrate how to use bidder specific targeting keys instead of the generic targeting keys.
While it may not be common, these alternate setups would allow publishers to be able to support certain use-cases where they specifically want to show the bid of a particular bidder (even if they didn't win the auction).
Beyond this - it would also give publishers assurance that the ads rendered from a bidder targeted line-item are actually from that bidder.

update set of UC templates to use bidder keys

---

_layouts/home.html

The homepage is missing a container for the layout, this causes a small horizontal scroll to be present (due to the -15px margins of .row without .container)

Fix horizontal scroll on Prebid.org homepage

---

dev-docs/show-prebid-ads-on-amp-pages.md

Related to https://github.com/prebid/prebid-universal-creative/pull/58 -- we've expanded the Prebid Universal Creative load-cookie.html to support multiple bidders.
So this doc change outlines how to set up load-cookie.html for appnexus and rubicon. Other bidders can be added in the future.
Also made a few other minor tweaks for wording and formatting.

refining the load-cookie docs

---

prebid-server/endpoints/version.md

This CL introduces documentation for the `/version` admin endpoint.
Original PR on prebid server side: https://github.com/prebid/prebid-server/pull/825
Issue: #1197

[Docs][PrebidServer] Adding `/version` doc

---

prebid-mobile/pbm-api/ios/pbm-targeting-ios.md

For the Prebid Mobile iOS page, added the following:
- New storeURL field
- Added heading for itunesID

Prebid SDK iOS: Added Store URL field and itunesID heading

---

download.md
overview/analytics.md

PR for the docs repo to add appier analytics adapter:
https://github.com/prebid/Prebid.js/pull/3871
Thank you :)

Add appier analytics adapter doc info to analytics page

---

dev-docs/bidders/beachfront.md

Adds documentation for optional outstream player params.

Add player params to beachfront doc

---

dev-docs/bidders/ozone.md

We're no longer including this attribute in our adapter and so we'll be removing it from developer documentation.

ozone bidder docs - removing references to ozoneData

---

dev-docs/modules/index.md
dev-docs/modules/userId.md

Docs update for the ID5 ID in the user id module, based on the prebid.js PR 3798 (https://github.com/prebid/Prebid.js/pull/3798). Includes the Digitrust docs updates (to `userId.md` only) from https://github.com/prebid/prebid.github.io/pull/1298 as requested by @bretg to avoid conflicts

ID5 ID user id module docs

---

dev-docs/modules/userId.md

There was a typo in the link to register for an ID5 ID

fix typo in id5 registration link

---

adops/send-all-bids-adops.md
adops/step-by-step.md

This PR updates some of the wording when setting up creatives in DFP.
Specifically it's meant to illustrate that adops traffickers need to have a copy of the Prebid creative for each potential ad slot they use on a page.  They can multiple sizes available on each creative (so they can resize given the request's context) but having a physical creative for each slot is the key.
**Context for the wording update**
There were some questions raised internally about how the pagview logic from the linked article affects the number of creatives that need to be setup in a line-item given the slot/size combinations.  For example, if they used 5 sizes and 3 ad slots - did they need to make 15 creatives?  
The answer is they need to make enough creatives to fill the ad slots.  The sizes will handle …

update wording on setting up creatives in a DFP line item

---

dev-docs/bidders/pulsepoint.md

Video support was added to PulsePoint adapter and is available with this release - https://github.com/prebid/Prebid.js/releases/tag/2.23.0

PulsePoint adapter: Video support

---

dev-docs/publisher-api-reference.md

This is a PR for the updates introduced by this Prebid.js fix:
https://github.com/prebid/Prebid.js/pull/3938
Add some clarifying notes about how sizeConfig works with multi-format type bids; namely that it only applies when the `banner` mediaType is part of the adUnit.

add notes on sizeconfig and multiformat

---

dev-docs/bidders/triplelift.md

**Context**
Updating bidder doc to include new `userIds: unifiedId/tradedesk` support. Looking to include triplelift in list here: [http://prebid.org/dev-docs/modules/userId.html#adapters-supporting-the-user-id-sub-modules](http://prebid.org/dev-docs/modules/userId.html#adapters-supporting-the-user-id-sub-modules)
Prebid.js PR = [Triplelift adapter tdid support #3983](https://github.com/prebid/Prebid.js/pull/3983)

Update docs for Triplelift tdid support

---

dev-docs/bidders/synacormedia.md

- Added more video parameters
- Added video example
- Fixed table so that it renders correctly
Link to PR: https://github.com/prebid/Prebid.js/pull/3885

Synacormedia bid adapter updates:

---

prebid-server/developers/coppa.md

https://github.com/prebid/prebid-server/pull/973 adds COPPA support and this is the documentation for same.

Add Prebid-Server COPPA support dicumentation

---

dev-docs/bidders/playgroundxyz.md

Replaces https://github.com/prebid/prebid.github.io/pull/1203 and uses the new `prevBiddercode` attribute. It works because the PBJS adapter has both pxyz as an alias. Here's what is produces:

pxyz adding short biddercode

---

dev-docs/bidders/adsparc.md

Hi there, this PR addresses this issue https://github.com/prebid/Prebid.js/issues/4113 
Adsparc is an alias for Aardvark. Previous Adsparc documentation contained wrong parameter definitions.  With this PR we set the parameters to be the same of Aardvark.

fix adsparc adapter parameters in documentation

---

dev-docs/modules/userId.md

Add documentation for a new storage parameter to force refreshes of the user id before the cookie expires, related to https://github.com/prebid/Prebid.js/pull/4082

add docs for the `storage.refreshInSeconds` configuration parameter

---

dev-docs/modules/userId.md

Making it clear that downloading the base module pulls in Unified and PubCommon

Turning text on download page

---

adops/deals.md
dev-docs/publisher-api-reference.md

@jeanstemp - a fairly dramatic revision of the send-all-bids section. Please feel free to edit directly.

refactored enableSendAllBids docs

---

dev-docs/modules/schain.md

This PR is to fix a small typo in the schain example (was missing a `{` character) and the formatting of the code.

fix small typo and formatting on schain example

---

dev-docs/bidders/sharethrough.md

- Documentation change to indicate that Sharethrough's bid adapter has been updated to support the schain module and to check for and send the `bidfloor` parameter when building bid requests.
- pubgrowth.engineering@sharethrough.com
- See related prebid.js PR: https://github.com/prebid/Prebid.js/pull/4271

Sharethrough: Schain bidfloor adapter docs update

---

dev-docs/modules/userId.md

User.id storage.expires is actually a required property.  Without it, the cookies are stored as session cookies due to not having a proper date, and local storage has invalid date.
Also fix recommend name for pubCommondID so when transition from old module, then id is retained.

UserID storage.expires is a required property

---

dev-docs/bidders/smms.md

add docs for SMMS Bid Adapter
https://github.com/prebid/Prebid.js/pull/4439

Add smms adapter

---

dev-docs/bidders/adastaMedia.md
dev-docs/bidders/viewdeos.md

Reverts prebid/prebid.github.io#1563
Deleting these files wasn't the proper approach for either. Adasta is now an alias of AppNexus, and viewdeos has their own adapter.

Revert "Gamoshi: Remove unsupported aliases"

---

troubleshooting/troubleshooting.md

It was still referring to the legacy endpoint.

Troubleshooting: fixing prebid server debug

---

dev-docs/bidders/aol.md

Documentation update for CCPA support for AOL bidder.
Ref:
https://github.com/prebid/Prebid.js/pull/4536

AOL: Document CCPA support

---

dev-docs/publisher-api-reference.md

Updated with new values for `video-instream` and `video-outstream`

add video-instream and video-outstream to the media type price granularities

---

dev-docs/modules/userId.md

Source is supposed to be a domain in 3.0 ORTB spec

Update userId.md - CNVR source

---

dev-docs/bidders/astraone.md

Added documentation for AstraOne Adapter to dev-docs

Added documentation for AstraOne Adapter

---

dev-docs/bidders/indexExchange.md

Updated docs to include `usp_supported` parameter.
This doc change is associated with this Prebid.js PR: https://github.com/prebid/Prebid.js/pull/4655

Index Exchange: CCPA support

---

dev-docs/bidders/underdogmedia.md

Updated docs to include usp_supported parameter.
This doc change is associated with this Prebid.js PR: prebid/Prebid.js#4675

UnderDog Media: CCPA Support

---

dev-docs/modules/schain.md
dev-docs/publisher-api-reference.md

These updates tie into https://github.com/prebid/Prebid.js/pull/4551 which allow publishers to setup bidder specific schain configs.

add bidder schain docs

---

dev-docs/bidders/aardvark.md

Add support for schain in aardvark bid adapter.
Here is pull request on prebid.js repository:
https://github.com/prebid/Prebid.js/pull/4636

Aardvark: add schain support

---

dev-docs/bidders/criteo.md

Remove mention of zoneId.
Updated networkId is now a required parameter.

Criteo - Updated doc regarding bidder parameters

---

dev-docs/plugins/cross-player-prebid-component/about-cross-player-prebid-component.md
dev-docs/plugins/cross-player-prebid-component/cross-player-communication.md

This PR addresses the following issues: 
[1735: Default url is missing from the doc](https://github.com/prebid/prebid.github.io/issues/1735)
[1736: Need to replace the word TBA on the Communication page](https://github.com/prebid/prebid.github.io/issues/1736)
[1737: Would prefer a more obvious visual separation between Steps](https://github.com/prebid/prebid.github.io/issues/1737)
[1738: Add some clarifying text to Communications page](https://github.com/prebid/prebid.github.io/issues/1738)
[1739: Add Sample Code for requestHandler on the Communications page](https://github.com/prebid/prebid.github.io/issues/1739)

Added changes per developer's comments.

---

dev-docs/bidders/rubicon.md
dev-docs/modules/userId.md

Spoke with Prebid legal counsel, and we agreed that each user ID module should include a link to their privacy policy.
As FYI, adding github handles for people who've been involved with each of the modules: @bansawbanchee, @Swiiip , @goosemanjack , @smenzer , @jankoulaga , @mamatic , @icflournoy , @pycnvr
Will leave this open for a few days for any corrections.

adding links to user id privacy policies

---

dev-docs/show-outstream-video-ads.md

Very small link update.
On this page: https://prebid.org/dev-docs/show-outstream-video-ads.html
in the body under "Step 2: Show ads in the page body" in "Option 1" there is a link to see the example for "Outstream with Google Ad Manager" - that link returns a 404.  The edit made in this commit points to the working page showing that example.

fix outstream-dfp link

---

dev-docs/bidders/indexExchange.md

Updated docs to specify Schain module support and video caching clarification
This doc change has associated code changes in the following Prebid.js PR: 
- Master PR: https://github.com/prebid/Prebid.js/pull/4770
- Legacy PR: https://github.com/prebid/Prebid.js/pull/4771

Index Exchange: Add Schain and video caching to docs

---

dev-docs/bidders/aardvark.md

Declare CCPA support for aardvark adapter.  
Declare utilization of unifiedId.

aardvark - declare ccpa support

---

prebid-server/endpoints/openrtb2/video.md

Appears to be a typo, based on:
https://github.com/prebid/prebid-server/blob/d64c98bf8422d3c5810c3cf10d1e5ebda4b00b6a/openrtb_ext/regs.go#L11

Fix us privacy param

---

dev-docs/bidders/criteo.md

Notice publishers relying on Placeholder sendID for Native Ad

Criteo - Add note for native sendId parameter

---

_includes/adops/adops-gam-setup.html
_includes/adops/adops-gam-video-setup.html

Remove stray HTML tags. You can see the problem at the bottom of these two pages:
http://prebid.org/adops/step-by-step.html
http://prebid.org/adops/setting-up-prebid-video-in-dfp.html

remove stray HTML tags, fixes #1852

---

overview/getting-started.md

Page overview/getting-started was linking to itself before. This pull request fixes this small issue.

Fix for wrong link in overview/getting-started

---

dev-docs/modules/userId.md

Documentation for https://github.com/prebid/Prebid.js/pull/4916

UserId module will provide sub-module ids in ORTB eids format

---

dev-docs/bidders/windtalker.md

Docs for Windtalker prebid adapter

Windtalker adapter docs

---

dev-docs/bidder-adaptor.md

Taking a first step on https://github.com/prebid/Prebid.js/issues/3115

adding meta object to bidder adapter docs

---

dev-docs/bidders/quantcast.md

Added flags for TCF v2 and COPPA support to the Quantcast adapter documentation.

Quantcast: Added flags for TCF v2 and COPPA support.

---

examples/video/instream/brid/pb-ve-brid.html

The example did not display the ad and the reason was that it didn't send the POST request to prebid cache to save the vast xml. Hence added the cache url in setConfig().

add cache url to post ad data to cache

---

download.md
overview/analytics.md

Tercept's Analytics adapter went live with the 3.17 release of Prebid.js.

Add Tercept Analytics adapter to download page and analytics page

---

_includes/adops/adops-gam-video-setup.html

update key to hb_cache_id

---

dev-docs/bidders/conversant.md

Override the destination URL in the Conversant adapter with the white_label_url parameter

Add a conversant parameter to override the destination URL

---

dev-docs/bidders/pubgenius.md

@kevinstubbs for peer awareness

New bidder adapter: pubgenius

---

dev-docs/bidder-adaptor.md

Expecting this is definetely a bug that bidderRequest is not holding this data, but still want to fix misleading info for new developers. 
**userId** and **schain** abjects are not available under **bidderRequest**, only available across bidRequests

Fix misleading documentation about schain and userId

---

prebid-mobile/prebid-mobile-pbs.md

Correct me if I'm missing something, but the Prebid Mobile setup instructions for PBS are referencing the prebid.js bidder list, which I've corrected here.

Updated URL to reference the correct bidder list

---

dev-docs/bidders/beachfront.md

Adds documentation for optional video `tagid` param.

Add tagid param to Beachfront doc

---

dev-docs/bidder-adaptor.md
dev-docs/bidders.md
dev-docs/bidders/adform.md
dev-docs/bidders/adformOpenRTB.md
dev-docs/bidders/beachfront.md
dev-docs/bidders/connectad.md
dev-docs/bidders/conversant.md
dev-docs/bidders/medianet.md
dev-docs/bidders/rakuten.md
dev-docs/bidders/rubicon.md
dev-docs/bidders/sovrn.md

For https://github.com/prebid/prebid.github.io/issues/2014 - added 'safeframes_ok' field. Next step is to figure out how to surface this info on the AdOps pages.
For https://github.com/prebid/prebid.github.io/issues/1659 - added support for a "no-display" value for media_types
Also updated the prebid_member values for a number of adapters.

safeframe and tcf2 fields

---

dev-docs/modules/index.md

This is the docs PR update to reflect changes to our ID system managing its own cookies. Parrable is moving to a "compound cookie" - one with both our ID value and our optout statuses encoded within.
The ID system will be reading legacy and new cookies, and writing a single cookie with consistent data.
To stay consistent with Parrable's Non-Prebid implementation the cookie name should remain the same in the event that Prebid and Parrable's implementation ever reside in the same page.

Parrable ID System: Remove cookie storage configuration option

---

dev-docs/bidders/adagio.md

Related Prebid.js PR: https://github.com/prebid/Prebid.js/pull/5347

Adagio: update scope params

---

dev-docs/bidders/appier.md
dev-docs/bidders/appierBR.md
dev-docs/bidders/appierExt.md
dev-docs/bidders/appierGM.md

add aliases for Appier adapter

Appier: Add appier bid adapter aliases

---

download.md

ATS bug fix.
When try to check ATS Analytics and download:
- The downloaded file does not contain the built JavaScript, but rather {"error":"Prebid file not built properly","requestId":"2f7a1640-9762-433a-8af8-97749c3918e4"}. Look at the network request; the POST contains: modules[]: atsAnalyticsAnalyticsAdapter.
Name of the module is not correct, there is two 'Analytics' in name.
@bretg

ATS-fix download link

---

dev-docs/bidders/truereach.md

This new bidder documentation PR is related to new bidder [TrueReach PR](https://github.com/prebid/Prebid.js/pull/5423).

TrueReach Bidder Document

---

dev-docs/bidders/smaato.md

This is the accompanying PR for the doc update for a new bid adapter create for Smaato Inc.

New bid adapter for Smaato

---

dev-docs/bidders/medianet.md

- Medianet video doc updates.
- Added some examples.  
- Added tcf2_supported: true

Medianet doc updates

---

dev-docs/bidder-adaptor.md

Implements https://github.com/prebid/Prebid.js/issues/5237 for Prebid 4.0
fyi @mike-chowla @ehoch

4.0 changes to video params

---

dev-docs/bidders.md

Hello, we noticed that our (SpotX) changes (safeframes_ok: false and adding "no-display" to media_types) weren't displaying correctly (http://prebid.org/dev-docs/bidders.html#spotx).  safeframes_ok false still shows as "check with bidder" and no-display has an extra comma before "video".  These changes to the template should make it behave correctly.

Bidder adapter template: fix safeframes_ok and no-display

---

dev-docs/bidders/triplelift.md

Triplelift now supports TCFv2 so we would like to add it to our bidder md file

Update triplelift.md to show tcf2 support

---

dev-docs/bidders/rtbsape.md

Add a new bidder adapter for RtbSape

RtbSape adapter

---

dev-docs/integrate-with-the-prebid-analytics-api.md
dev-docs/modules/gdprEnforcement.md
dev-docs/publisher-api-reference.md

Docs PR for https://github.com/prebid/Prebid.js/pull/5444

tcf2 purpose7

---

dev-docs/bidders/visx.md

VIS.X Adapter - Added TCF v2.0 support to the documentation

---

_data/sidebar.yml
dev-docs/bidder-adaptor.md
dev-docs/integrate-with-the-prebid-analytics-api.md
dev-docs/module-rules.md
dev-docs/publisher-api-reference.md
prebid-server/developers/add-new-bidder-go.md
prebid-server/developers/add-new-bidder-java.md
prebid-server/developers/pbs-build-an-analytics-adapter.md

We're finally ready to publish the module rules to the website. Original doc was https://docs.google.com/document/d/1kK0ifXV-vzyV7VchPKoyGuz375H7fzbTJFt_oWeCiRo/edit# -- this PR converts the GDoc to Markdown and peppers links to it around various pages.

module rules

---

dev-docs/bidder-adaptor.md
dev-docs/bidders.md
dev-docs/bidders/aardvark.md
dev-docs/bidders/adagio.md
dev-docs/bidders/adform.md
dev-docs/bidders/adformOpenRTB.md
dev-docs/bidders/adhese.md
dev-docs/bidders/adtelligent.md
dev-docs/bidders/aol.md
dev-docs/bidders/appnexus.md
dev-docs/bidders/apstream.md
dev-docs/bidders/beintoo.md
dev-docs/bidders/conversant.md
dev-docs/bidders/criteo.md
dev-docs/bidders/districtm.md
dev-docs/bidders/emx_digital.md
dev-docs/bidders/fidelity.md
dev-docs/bidders/improvedigital.md
dev-docs/bidders/indexExchange.md
dev-docs/bidders/medianet.md
dev-docs/bidders/openx.md
dev-docs/bidders/openxoutstream.md
dev-docs/bidders/pubmatic.md
dev-docs/bidders/pulsepoint.md
dev-docs/bidders/rubicon.md
dev-docs/bidders/spotx.md
dev-docs/bidders/sublime.md
dev-docs/modules/gdprEnforcement.md

The GDPR Enforcement modules requires bid adapters, userid submodules and analytics adapters to provide GVL ID, otherwise the module will be blocked by default unless its present in `vendorExceptions`.
Related PR: https://github.com/prebid/Prebid.js/pull/5643

Add supported modules table for GDPR Enforcement module.

---

dev-docs/bidders/criteo.md

Following this request : https://github.com/prebid/prebid.github.io/issues/1929
Restored the param in the doc, specifying that it is deprecated.

Restored zoneId parameter in criteo bid adapter doc

---

faq/prebid-server-faq.md

Quick typo fix - says 'privay' instead of 'privacy'

Typo fix, 'privay' instead of 'privacy'

---

dev-docs/modules/userId.md

Provides documentation for https://github.com/prebid/Prebid.js/pull/5727.

Add Quantcast userId submodule documentation

---

dev-docs/publisher-api-reference.md

Related to https://github.com/prebid/Prebid.js/pull/5703

doc: add getEvents method to the public API 

---

dev-docs/modules/userId.md

This PR includes documentation for the Audigent HaloId userId submodule.  The Prebid.js PR for the code is located here:
https://github.com/prebid/Prebid.js/pull/5524

Audigent HaloId Documentation

---

dev-docs/show-outstream-video-ads.md

Documents https://github.com/prebid/Prebid.js/pull/5638

Backup only renderers

---

dev-docs/bidders/apstream.md

Move `test` and `publisherId` parameters to bidder specific config

Add additional parameters to config

---

prebid-mobile/pbm-api/android/pbm-adunit-android.md
prebid-mobile/pbm-api/android/pbm-targeting-params-android.md
prebid-mobile/pbm-api/ios/pbm-adunit-ios.md
prebid-mobile/pbm-api/ios/pbm-targeting-ios.md

Documentation support for OMSDK and 3rd party ad server support using callback on fetchDemand for both iOS and Android

Prebid SDK 1.8: bid response callback and OMSDK

---

dev-docs/bidders/quantumdex.md
dev-docs/bidders/valueimpression.md

I have added TCF v2.0 support for Quantumdex and Valueimpression bid adapter to the documentation
tcf2_supported: true
Support is handled on the endpoint side so I haven't changed anything in the prebid.js code.
Thanks!

Added TCF v2.0 support to the documentation

---

dev-docs/bidders/yieldlab.md

Schain Support for Yieldlab was merged and released via: https://github.com/prebid/Prebid.js/pull/5521
Thanks!

Yieldlab: Add Supply Chain Support to Docs

---

dev-docs/bidders/smaato.md

Related to this PR for Prebid.js: https://github.com/prebid/Prebid.js/pull/5765
In addition we now support tcf2.
We have clients who want to use Prebid.js inside an app's webview and transmit geo info or device ids that they may be able to use in this case.
In order to support this, we accept a new `app` object as an optional bidder param where they can add this additional info.
The params object of an adUnit making use of this feature would look like this:
```
params: {
publisherId: 'publisherId',
adspaceId: 'adspaceId',
app: {
ifa: 'aDeviceId',
geo: {
lat: 33.3,
lon: -88.8
}
}
}
```

Smaato bid adapter: Optional bidder params to support in-app webview use cases

---

dev-docs/modules/userId.md
download.md

adding documentation for the Pubprovided user id module

Add pubProvided to userId.md

---

dev-docs/bidder-adaptor.md

Related: https://github.com/prebid/Prebid.js/pull/4846
Also fixes incorrect spec for the `stack` property.

Update refererInfo spec to match AMP updates

---

prebid-server/versions/pbs-versions-java.md

Labels were referencing the Go version of PBS

Wrong label in PBS Java page

---

dev-docs/bidders/smartyads.md
dev-docs/modules/userId.md
download.md

Added IDx documentation for User ID. https://github.com/prebid/Prebid.js/pull/5826

add IDx User Id docs

---

dev-docs/bidders/triplelift.md
download.md

Driven by a [specific adapter issue](https://github.com/prebid/Prebid.js/pull/5872), this is a new piece of optional metadata. e.g.:
```
pbjs_version_notes: v4.13+
```

pbjs_version_notes feature

---

dev-docs/modules/userId.md

Module name was incorrect in the example

Fix pubProvidedId example

---

prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md

Addresses https://github.com/prebid/prebid-server/issues/1517
Currently the documentation says that native asset object's ID is not to be defined in the request. However, both Prebid Server Go and Prebid Server Java treat this as an optional field such that if the asset's ID isn't provided in the request, it assigns it based on the asset's index value in the array of assets. This behavior makes sense because if the request is requesting two types of data assets such as `sponsored` (type: `1`) and `desc` (type: `2`), and if the assets in the response don't have the types set (Based on the openrtb native spec the `type` field in the data asset response object is optional) then there's no way for the Publisher to know which data asset is of which type. Therefore, updating the documentation …

Update docs to reflect that native asset's ID field is optional

---

dev-docs/modules/reconciliationRtdProvider.md

Docs for Reconciliation Real Time Data module.
Main PR: https://github.com/prebid/Prebid.js/pull/5774

Add Reconciliation RTD Module docs

---

dev-docs/modules/jwplayerRtdProvider.md

Required for https://github.com/prebid/Prebid.js/pull/5844

[AD-963] Add documentation for JW Player RTD Provider

---

dev-docs/modules/userId.md

Add docs related to https://github.com/prebid/Prebid.js/pull/5874 to require publishers to use `html5` storage with the name `id5id`.

ID5 requires html5 storage with id5id name

---

dev-docs/modules/userId.md

Update PubCommon ID doc
* Add missing doc for params create, extend, and pixelUrl
* Add section for built-in shared ID support

Update PubCommon ID doc to include missing params and sharedid support

---

adops/before-you-start.md

Followup to https://github.com/prebid/prebid.github.io/issues/2014 - highlighting bidders that don't support safeframes.

AdOps overview: adding safeframe section

---

dev-docs/bidders/sharethrough.md

- Related feature PR [here](https://github.com/prebid/Prebid.js/pull/5871)
- pubgrowth.engineering@sharethrough.com

Add support for Publisher Common ID Module in Sharethrough bid adapter docs

---

dev-docs/bidders/triplelift.md

Video bug fixes in effect starting 4.15: https://github.com/prebid/Prebid.js/releases/tag/4.15.0

[Triplelift] Avoid versions 4.3-4.14

---

dev-docs/bidders/beachfront.md

Adds documentation for optional video params `skip`, `skipmin`, and `skipafter`.

Add skip params to Beachfront doc

---

dev-docs/modules/jwplayerRtdProvider.md

Updates the documentation for API change introduced in https://github.com/prebid/Prebid.js/pull/5950
As of the linked PR, targeting information is set to `bid.rtd.jwplayer.targeting` instead of `bid.jwTargeting`.

[AD-1023] JW Player - Set targeting info to bid.rtd

---

dev-docs/modules/userId.md

The example code omitted the word System from the module name

Update the name of the lotamePanoramaIdSystem module to be accurate

---

prebid-server/developers/add-new-bidder-go.md

This is a complete rewrite of the PBS-Go New Adapter doc to include a lot of much needed detail. It's written with the changes introduced in https://github.com/prebid/prebid-server/pull/1532.

Rewrite PBS-Go New Adapter Doc

---

prebid-server/developers/add-new-bidder-go.md

The Jekyll/Kramdown/Liquid stack used by the website suppress {{}} macros. Fixed by adding the {%raw%} tags.

PBS Go docs escaping {{}}

---

dev-docs/bidders/deepintent.md

DeepIntent: PBS docs added

---

dev-docs/modules/geoedgeRtdProvider.md

This PR adds publisher docs for Geoedge RTD provider. Relevant Prebid.js PR: [#5689](https://github.com/prebid/Prebid.js/pull/5869)

Add docs for Geoedge Rtd provider

---

dev-docs/bidders/beachfront.md

Adds documentation for optional video `responseType` param.

Add video response type param to Beachfront doc

---

dev-docs/bidders/yieldmo.md

This is a documentation update after https://github.com/prebid/Prebid.js/pull/5973

yieldmo.md: video support is documented

---

dev-docs/bidders/between.md

added missed parameters and update their description. see https://github.com/prebid/prebid-server/pull/1587

Updated Between adapter dev docs

---

dev-docs/bidders/grid.md
dev-docs/bidders/pubmatic.md
dev-docs/bidders/rubicon.md
dev-docs/bidders/smartadserver.md
dev-docs/bidders/vidazoo.md

Setting rubicon and pubmatic to support 'all' user IDs as per issue https://github.com/prebid/prebid.github.io/issues/2492
Removing digitrust from remaining adapters

userId updates

---

dev-docs/bidders/pubgenius.md

@kevinstubbs for team awareness

pubGENIUS bidder: update doc to add video params

---

dev-docs/bidders/adagio.md

Related to : https://github.com/prebid/Prebid.js/pull/6038

Adagio: add video support

---

dev-docs/bidders/zemanta.md

Hi, this is the PR related to https://github.com/prebid/Prebid.js/pull/6039

Add zemanta.md

---

dev-docs/bidders/fidelity.md
dev-docs/bidders/kubient.md

Adding native Kubient pbjs adapter, removing alias from Fidelity adapter.

Kubient and Fidelity bid adapters. Update Gvlid, Parameters, Alias.

---

dev-docs/bidders/inmar.md

Inmar bidder adapter documentation

Add Inmar bidder adapter

---

dev-docs/bidders/readpeak.md

Adds documentation for the optional tagId parameter for the Readpeak bidder.  Also adds the IAB Global Vendor List ID.
Related PR: https://github.com/prebid/Prebid.js/pull/6133

Readpeak: Add tagId to documentation

---

dev-docs/publisher-api-reference.md

Added text to cover the `sampling` option in the analytics adapter base class. See https://github.com/prebid/prebid.github.io/issues/2504 and https://github.com/prebid/Prebid.js/pull/1011

added sampling option to enableAnalytics function

---

dev-docs/bidders/revcontent.md

Prebid server support is being added for Revcontent, and this is the accompanying documentation.
Regarding the gdpr_supported, etc changes, while our company does not do anything with the data that would be out of band with the regulations, we didn't see https://docs.prebid.org/dev-docs/modules/consentManagement.html previously, and so I'm setting false for these values until we have a chance to review that.

Updating Revcontent documentation to include prebid-server

---

dev-docs/bidders/appnexus.md

Based on https://github.com/prebid/Prebid.js/pull/6114
Adding netId as a supported userId for the appnexus bidder.

appnexus - add netid

---

dev-docs/bidders/houseofpubs.md

Adding on behalf of a client alias

Create houseofpubs.md bidder instructions

---

dev-docs/bidders/indexExchange.md

With our latest PBS adapter update, IX now supports mobile app supply. Updated the pbs_app_supported flag to reflect that.

Updated IX pbs_app_supported flag

---

dev-docs/bidders/beachfront.md

Added the pbs_app_supported flag, corrected a spelling variant to match other usage, and some minor formatting for improved readability of the md source.

added the pbs_app_supported flag

---

dev-docs/bidders/appnexus.md
dev-docs/show-prebid-ads-on-amp-pages.md
faq/prebid-server-faq.md
prebid-server/developers/pbs-cookie-sync.md

Docs for https://github.com/prebid/prebid-universal-creative/pull/123

load-cookie-with-consent docs

---

dev-docs/bidder-adaptor.md

Not sure about format of this info

Add aliases info to "build adapter" section

---

dev-docs/add-rtd-submodule.md
dev-docs/modules/index.md
dev-docs/publisher-api-reference.md

A recent PR found a gap in the Real-Time Data documentation that this aims to close.

RTD auctionDelay and waitForIt flag

---

dev-docs/modules/userId.md

A minor tweak to clarify some confusion clients had that crwdcntrl.net is Lotame's domain.

Clarify that crwdcntrl.net is Lotame

---

dev-docs/bidders/outbrain.md

Hey!
This PR renames the Zemanta adapter to Outbrain. We only want Outbrain to be seen to publishers so the biddercode and naming in the source code stays the same.

Rename Zemanta to Outbrain

---

dev-docs/bidders/appnexus.md

This PR fixes a small typo in one of the listed values for the video params table.

appnexus video params - fix typo

---

dev-docs/modules/userId.md

adding description of the new user id permission schema.

Update permission documentation userId.md

---

download.md
overview/analytics.md

Relevant Yield analytics adapter added in overview/analytics.md + download.md.
**Notice:** The adapter itself is not merged yet at the time of writing this, so the documentation depends on this pull request being merged: [https://github.com/prebid/Prebid.js/pull/6195](https://github.com/prebid/Prebid.js/pull/6195) (therefore the download isn't working when selecting the Relevant Yield checkbox)

Relevant Yield Analytics adapter added

---

dev-docs/modules/bidViewable.md
dev-docs/modules/instreamTracking.md

Refer PrebidJS PR: https://github.com/prebid/Prebid.js/pull/6206
Also added an API fix in documentation of Instream tracking module

Bid Viewability module documentation

---

dev-docs/bidders/appnexus.md
dev-docs/show-prebid-ads-on-amp-pages.md
prebid-server/developers/pbs-cookie-sync.md

Based on a slack conversation, publishers need an extra parameter in the `sandbox` attribute of the amp-iframe.
@jeanstemp - I tweaked the appnexus.md file, so looking for your approval. Just linking it out to the full doc.

Adding note to AMP about load-cookie-with-consent

---

dev-docs/modules/bidViewable.md

Reported here:
https://github.com/prebid/Prebid.js/pull/6206#issuecomment-784018822
Seems like the module code set for this new bidViewable module isn't consistent with the filename in the Prebid.js repo.
This is causing any builds made with this module from the Download page to not work.
This PR should fix the issue (it shouldn't need any fixes from the Prebid.js side).

fix module_code for bidViewable module

---

dev-docs/bidders/adhash.md

Documentation for the AdHash Bidder Adapter.
PR for the adapter changes - https://github.com/prebid/Prebid.js/pull/6274

AdHash Bidder Adapter: initial prebid.js integration

---

dev-docs/bidders/sortable.md

This is to declare TCF2 support and add the GVL id. There is no corresponding code change to our adaptor - it was just noted that our documentation is out of date.

Update Sortable features table

---

_includes/adops/adops-gam-video-setup.html
_includes/send-all-bids-keyword-targeting.md
adops/send-all-bids-adops.md
dev-docs/publisher-api-reference.md

Related to https://github.com/prebid/Prebid.js/issues/6078

added ignoreBidderCacheKey docs

---

dev-docs/bidders/outbrain.md

Hey! This PR just adds a note for publishers about enabling usersync on aliased adapters so we can avoid potential issues.

Add note about aliasSyncEnabled on Outbrain adapter

---

prebid/native-implementation.md

This is the documentation related to https://github.com/prebid/Prebid.js/pull/6220.
After reading the whole documentation, I think it is the best place to add it, but let me know if you have another suggestion.

Native: add Native Custom Assets section

---

dev-docs/bidders/jixie.md

as we are adding the prebid-server adaptor and introduced a few extra params there, they are added here too.
(note: those 3 new params would also reach the headerbid adserver in the case of prebid "clientside HB" too. So all good)

jixie: param updates

---

prebid-server/developers/add-new-bidder-go.md

Doc update for https://github.com/prebid/prebid-server/pull/1721.

Update For GDPR Vendor ID Changes

---

dev-docs/bidders/adagio.md

Related to PR: https://github.com/prebid/Prebid.js/pull/6368

Adagio: add support for Native

---

dev-docs/bidder-adaptor.md

Documents https://github.com/prebid/Prebid.js/pull/6383 and https://github.com/prebid/Prebid.js/pull/6380

Document demand chain objects

---

dev-docs/bidder-adaptor.md

The documentation for `interpretResponse` outlines the fields required in a bid response, but is missing the top-level `mediaType` field.

bidder-adaptor.md: missing required field in bid response

---

dev-docs/modules/index.md
dev-docs/modules/multibid.md
prebid-server/endpoints/openrtb2/pbs-endpoint-amp.md
prebid-server/endpoints/openrtb2/pbs-endpoint-auction.md

Docs for the multibid feature, covering:
PBJS - https://github.com/prebid/Prebid.js/issues/6317
PBS - https://github.com/prebid/prebid-server/issues/1715

multibid docs

---

dev-docs/bidders/openx.md

Clarify that platform and delDomain can both be passed.

OpenX docs update

---

dev-docs/bidders/ix.md

IX bid adapter supports priceFloors module , since prebid version 4.32.0.

IX adapter has priceFloors module support

---

dev-docs/bidders/roundel.md

Adding documentation to support aliased roundel bidder.
This is in relation to the following PR: https://github.com/prebid/Prebid.js/pull/6473

Roundel Alias Documentation 

---

dev-docs/bidders/rubicon.md

Either string or int works for client-side calls, but PBS requires integers

rubicon: updating preferred data type

---

dev-docs/bidders/criteo.md

Update Criteo adapter doc for PBS support:
- PBS support flag
- PBS activation note about reaching to PBS point of contact
PBS adapter pull request: https://github.com/prebid/prebid-server/pull/1775

Update Criteo adapter doc for PBS support

---

dev-docs/bidders/impactify.md

Adding documentation to support impactify bidder.
This is in relation to the following PR: https://github.com/prebid/Prebid.js/pull/6518

Add Impactify bidder documentation

---

dev-docs/modules/userId.md

Google deprecated this feature, perhaps temporarily; see https://developers.google.com/authorized-buyers/rtb/request-guide

Indicate userid module can no longer pass to ob

---

dev-docs/analytics/adloox.md

Policy dictates documentation to be added to the prebid website, as discussed in https://github.com/prebid/Prebid.js/pull/6308#discussion_r589585261
This commit adds details about the Adloox Prebid Analytics Adapter to the Prebid website.

dev-docs: describe Adloox Prebid Analytics Adapter

---

dev-docs/modules/gpt-pre-auction.md

Resolves issue https://github.com/prebid/prebid.github.io/issues/2833

gpt-pre-auction ORTB2 updates

---

dev-docs/bidders/pubgenius.md

Flagged by https://github.com/prebid/Prebid.js/issues/6465
Code https://github.com/prebid/Prebid.js/pull/6555

pubGENIUS bid adapter: support floor module

---

dev-docs/modules/userId.md

ATS-identityLinkIdSystem - add another config parameter to control firing of 3P envelope endpoint, in order to get identity envelope.

ATS-identityLinkIdSystem - add explanation for new use3P config parameter

---

dev-docs/cmp-best-practices.md
dev-docs/modules/sirdataRtdProvider.md

We explain how to use the new Sirdata Real-time Data Module. We also updated cmp-best-practices.md to provide guidelines for Sirdata CMP.

Sirdata Real-time Data Module documentation

---

dev-docs/modules/userId.md

Change name of config parameter from use3P to notUse3P in order to have required behaviour, by default 3P endpoint will be triggered. 
@smenzer

ATS-identityLinkIdSystem - add explanation for new notUse3P config parameter

---

dev-docs/bidders/spotx.md

Adding a note about the videoCacheKey issue discussed in https://github.com/prebid/Prebid.js/pull/6413 affecting spotx from 4.31-4.35

spotx: adding ignoreCacheKey note

---

dev-docs/bidders/triplelift.md

Removing disclaimer as these versions are no longer available for download.
https://docs.prebid.org/download.html

Triplelift: Removing disclaimer

---

dev-docs/bidders/outbrain.md
dev-docs/bidders/outbrain_old.md

Hey,
please see the linked PR for the reasoning behind this. In short, the issue is that the non-aliased outbrain adapter only exists in the lastest prebid.js version where it was released so trying to download it with a previous version fails.
If you agree with the proposed changes, would it be possible for this to be merged as soon as possible? Because if it is, only the latest version would not work with outbrain and not the other way around and we would not have to wait for the next prebid.js release. Any issues here?

Outbrain adapter: reinstate as alias for zemanta

---

dev-docs/bidders/nativo.md

Adding documentation for the Nativo Bidder Adapter.

Nativo Bidder Adapter

---

dev-docs/modules/userId.md
download.md

Deepintent DPES ID user module docs are added.

deepintent docs added

---

dev-docs/bidders/adf.md
dev-docs/bidders/adformOpenRTB.md

Due to the prebid-server adapter naming conventions, adformOpenRTB adapter renamed.

Adf prebid-server adapter added

---

dev-docs/modules/userId.md

Fixed formatting for table for Deepintent Configuration. 
mostly fixes the Issue #2893

fixed formatting

---

dev-docs/adunit-reference.md

https://github.com/prebid/Prebid.js/issues/5237

Update video params listed at adunit-reference.md

---

dev-docs/modules/userId.md

update the userid module docs to indicate that a cookie is used to store the consent string for managing id submodule refreshes
related to the conversation here: https://github.com/prebid/Prebid.js/issues/6386#issuecomment-802371824

update the userid module docs to indicate that a cookie is used

---

dev-docs/modules/userId.md

Update the Lotame userId docs to reference some URLs and a support email.

Update Lotame link and email

---

dev-docs/bidders/districtmdmx.md

Reverts prebid/prebid.github.io#2888
See https://github.com/prebid/Prebid.js/issues/6799
I think what happened here was confusion around case-sensitivity. There was, at one point, two copies of this file: districtmdmx and districtmDMX. This causes problems. I don't know why both versions are gone now, but anyhow restoring.

Revert "remove duplicate copy of districtmdmx"

---

dev-docs/bidders/invibes.md

Adds Unified ID 2.0 to the list of supported userIds: uid2, zeotapIdPlus, id5id
Removed bid param from doc (this was no longer used since prebid 1)

InvibesBidAdapter - update doc for userid: uid2, zeotapIdPlus, id5id

---

dev-docs/bidders/appnexus.md

Small change to note the appnexus bidder supports the `flocId` userId.
Related to:
https://github.com/prebid/Prebid.js/pull/6801

appnexus bid adapter: flocid support

---

dev-docs/bidders/dmx.md

Update server side  params to reflect supported params for DMX

DMX:  Update params

---

prebid/native-implementation.md

`<style>` tag was not wrapped in `` ` `` and this caused the end of the sentence to disappear from rendered page.

escape <style> tag

---

dev-docs/modules/userId.md

We moved our documentation to a new domain, so updating links
https://github.com/prebid/Prebid.js/pull/6824

ID5 User Id Module: update docs links

---

dev-docs/bidders/apacdex.md
dev-docs/bidders/quantumdex.md
dev-docs/bidders/valueimpression.md

This PR updates documentation regarding the Apacdex adapter and its alias (Quantumdex, Valueimpression)
- Support User ID Module for all User ID Sub-Modules has been updated in PR https://github.com/prebid/Prebid.js/pull/6378
- Support Price Floors Module has been updated in PR https://github.com/prebid/Prebid.js/pull/6711
- Update Bid Params, Video Ad Unit reference and Sample Ad Unit with Table of Contents
- Reference alias document to Apacdex adapter doc

Apacdex, Quantumdex, Valueimpression docs update

---

dev-docs/modules/floors.md

Clarification on adUnit floors and a warning for bid adapters who read floors.

Floors updates

---

dev-docs/bidders/adagio.md

This PR just add the support of `getFloor`
Related to : https://github.com/prebid/Prebid.js/pull/6867

AdagioBidAdapter: support priceFloors module

---

dev-docs/bidders/eplanning.md

Updated Eplanning docs to add mobile app support and gvl_id

Eplanning Bid Adapter: add support for mobile apps and gvl_id

---

dev-docs/bidders/conversant.md

Update Conversant doc to say that video params could include mediaType.video.

Conversant adapter include mediaTypes.video

---

dev-docs/bidders/aduptech.md

* Add Support for `native` mediaType
* Fixup description
* Updated parameters
- Related prebid.js PR:  https://github.com/prebid/Prebid.js/pull/6800

Update docs for AdUp Technology bid adapter

---

dev-docs/modules/userId.md

Adding documentation for the FLoC user id module.

Update dev-docs with floc

---

dev-docs/examples/adunit-refresh.md
dev-docs/publisher-api-reference/setConfig.md

Added usage on config auctionOptions.suppressStaleRender
See prebid/Prebid.js#6707

Add auctionOptions.suppressStaleRender

---

dev-docs/modules/dgkeywordRtdProvider.md

Thank you for merging our dgkeyword rtd module to muster.
Now I checked prebid.js download site, and I found that dgkeyword real time
sub-module can not select.
I think dgkeyword real time sub-module can use only when using gulp build.
https://docs.prebid.org/download.html
So I want to change, our dgkeyword real time sub-module can download from
the prebid.js download site.

I want to add dgkeyword rtd module page.

---

dev-docs/modules/categoryTranslation.md

This documents the fix to https://github.com/prebid/Prebid.js/issues/4048 on https://github.com/prebid/Prebid.js/pull/6464

Update categoryTranslation.md change to dfp video module hook

---

dev-docs/bidders/triplelift.md

Added 'pubCommonId' to TripleLift Prebid.org dev docs (User IDs)
https://docs.prebid.org/dev-docs/bidders/triplelift

TripeLift: Add pubCommonId to User Ids

---

dev-docs/bidders/pulsepoint.md

Related to changes made in https://github.com/prebid/Prebid.js/pull/6857

PulsePoint Adapter: Removing video params (using them from mediaTypes.video instead)

---

dev-docs/modules/optimeraRtdProvider.md

This is for the Optimera  Real Time Data Module.
The main PR is here: [PR #6962](https://github.com/prebid/Prebid.js/pull/6962)

Adding the OptimeraRTD provider Doc.

---

dev-docs/bidders/winr.md

Docs includes a general overview and information on required and optional adUnits parameters.

Adding WINR bid adapter docs

---

dev-docs/modules/userId.md

IdentityLink is being rebranded to RampID. As a first step only textual changes will be applied.

Rebranding IdentityLink to RampID

---

dev-docs/bidders/gnet.md

Gnet Bid Adapter: update to Prebid 5.x and remove externalId parameter

Gnet Bid Adapter: update to Prebid 5.x and remove externalId parameter

---

dev-docs/bidders/unruly.md

Updating the unruly adapter params and supported features according to the consolidated adapter with rhythm one adapter and unruly adapter.

Unruly r1 consolidated adapter

---

dev-docs/modules/userId.md

Documentation for a new userId submodule, akamaiDAPId

akamaiDAPIdSystem doc Update

---

dev-docs/publisher-api-reference/setConfig.md

Related to https://github.com/prebid/Prebid.js/pull/7076
Add info about the object config option available for the `s2sConfig` `endpoint` and `syncEndpoint` fields.
Also adds `openx` as an available `defaultVendor`.

update s2sconfig for endpoint object config and add openx defaultVendor

---

dev-docs/bidders/audiencerun.md

Hi,
Due to our last developement, `adId` is unique and is no longer set by our adapter (https://github.com/prebid/Prebid.js/issues/6381) . We can therefore remove the disclosure.
Related Prebid.js PR (https://github.com/prebid/Prebid.js/pull/6919)

AudienceRun v1.1.0: remove adId disclosure

---

dev-docs/bidders/pixfuture.md

replaces #3108 
In the future, allowing us to modify your fork would make fixing conflicts like this easier.

pixfuture: fixing data type, PBJS flag

---

dev-docs/modules/userId.md

The example for specifying eids to PubProvidedId in the getConfig() was broken.  This PR fixes it

Fix broken PubProvidedId example

---

dev-docs/bidders/projectLimelight.md

Hello,
We (Limelight Digital formerly known as Project Limelight) have new Limelight Digital Bidder Adaptor in latest 5.x Prebid.js releases. Unfortunately, many of our clients continue to use 4.x Prebid.js releases and want to download Prebid.js releases from https://docs.prebid.org/download.html page with our deprecated Project Limelight Bidder Adaptor. We need add deprecated Project Limelight Bidder Adaptor on https://docs.prebid.org/download.html page.
Thanks.

Add deprecated Project Limelight Bidder Adaptor

---

dev-docs/modules/userId.md
identity/sharedid.md

updating the table and text of Sharedid (FKA pubcommon's) entry in the user id section.

Update SharedId docs with Conversant content

---

download.md

Adding AMX RTB ID system to the downloads page. The module was originally added here: https://github.com/prebid/prebid.github.io/pull/3026

adding AMX RTB ID system to downloads page

---

dev-docs/modules/haloRtdProvider.md
dev-docs/modules/userId.md

Updates to match the Prebid.js module md files.

Halo ID & RTD Documentation Update

---

dev-docs/bidders/teads.md

Update the Teads adapter documentation to add support for **FLoC ID** (`flocId`) and **Unified ID v2** (`uid2Id`) user ID systems.

Update Teads bidder doc with support for some userIds

---

dev-docs/bidders/gumgum.md

Updates Server Side params to include the new `slot` param - a placement ID that will be used to identify flex-slot placements

Gumgum: ADJS-1059 Update prebid documentation for flex slot Placement ID

---

dev-docs/publisher-api-reference/getEvents.md
dev-docs/publisher-api-reference/offEvent.md
dev-docs/publisher-api-reference/onEvent.md

Resolves issue https://github.com/prebid/prebid.github.io/issues/3112

event API doc updates

---

dev-docs/bidders/ix.md

In this PR, we resolve the issue with markdown formatting where the table was not rendering correctly:

IX Bid Adapter: clean up table formatting

---

dev-docs/bidders/ix.md

In this PR, we are updating our documentation to reflect upcoming changes to https://github.com/prebid/Prebid.js/pull/6784

IX Bid Adapter: FPD

---

dev-docs/analytics/malltv.md

Adapter pull request: https://github.com/prebid/Prebid.js/pull/7218

Added malltv analytics docs

---

dev-docs/show-prebid-ads-on-amp-pages.md

Couple of updates:
- added arbitrary endpoint support (see issue https://github.com/prebid/prebid-universal-creative/issues/122)
- added "source=amp" parameter to get the iframe-excluded passed through
- fleshed out the custom RTC URL section

AMP load-cookie updates

---

dev-docs/bidders/smarthub.md

Hello, production [docs for the SmartHub adapter](https://docs.prebid.org/dev-docs/pbs-bidders.html#smarthub) displays wrong now. This PR fixes displaying.
Brefore:
After:

SmartHub adapter: fix docs displaying

---

prebid-server/developers/add-new-bidder-go.md
prebid-server/developers/add-new-bidder-java.md

As discussed in last week's PBS PMC:
1) bid metadata should be in seatbid.bid.ext.prebid.meta
2) There's no need for advertiserDomains there -- that field needs to be in seatbid.bid.adomain

PBS dev docs and metadata

---

dev-docs/bidders/unruly.md

Updating vendor id to the RhythmOne id since the consolidation adapter.

Unruly consolidated adapter - vendor id update

---

dev-docs/publisher-api-reference/getConfig.md
dev-docs/publisher-api-reference/readConfig.md

Documents https://github.com/prebid/Prebid.js/pull/7237

Document readConfig function

---

dev-docs/modules/userId.md
download.md

Adding companion docs pr for the kinesso user id module : https://github.com/prebid/Prebid.js/pull/7077

Update userId.md add kinesso id docs

---

dev-docs/bidders/bliink.md

This PR is associated with this one : [https://github.com/prebid/Prebid.js/pull/7297](prebid adaptor)

BLIINK Bidder adaptor docs

---

dev-docs/bidders/adyoulike.md

This page id showing "Floors Module Support: no"  for adyoulike bidder which is wrong now.
https://docs.prebid.org/dev-docs/bidders/adyoulike
I've updated the getFloor flag to 'true'. 
Will the be sufficient ? 
Thanks for any advice.

Add getFloor support for adyoulike bidder

---

dev-docs/modules/weboramaRtdProvider.md

the module can be found here
https://github.com/prebid/Prebid.js/pull/7437
available since Prebid.js 5.15 (latest)

add weborama RTD doc

---

features/firstPartyData.md

solves https://github.com/prebid/Prebid.js/issues/7415

Update firstPartyData.md with app.content.data example

---

dev-docs/bidders/between.md

— update information about safeframes_ok; remove «w» and «h» in required parameters
• contact email of the adapter’s maintainer khaylov@betweenx.com

Between adapter: safeframes_ok and require parameters

---

dev-docs/modules/index.md

I can't get the build to 100% run right on my machine, but this seems to fix #3295

fix links on modules/index.html

---

dev-docs/bidders/amx.md

We are now requiring the `tagId` parameter on new integrations. Changing the parameter here & adding a note about the test tagId to resolve a potential confusion.

AMX Bid Adapter: change to required parameters

---

dev-docs/bidders/yieldmo.md

* schain support for video ads
* device.ip support
* gpid support

yieldmo: multiple changes

---

dev-docs/modules/timeoutRtdProvider.md

Adding doc file for the timeout rtd module. Prebid.js PR: https://github.com/prebid/Prebid.js/pull/7395

Add doc for timeout rtd module

---

troubleshooting/pbs-troubleshooting.md

As suggested in https://github.com/prebid/Prebid.js/issues/5986, documenting that the ortb `test` flag can be created with a setConfig.

added setconfig for PBS test flag

---

dev-docs/bidders/seedtag.md

Update doc for seedtag adapter : 
- change `adunit` to `adUnit`
- add gdpr compliance and provide gvl id

update bidder doc for seedtag

---

download.md

This change was missed in the previous changes. 
To recap: Verizon Media branding has been replaced with Yahoo branding. The newly branded user identity module is here: 
https://github.com/prebid/Prebid.js/blob/master/modules/connectIdSystem.js
Here is the previous PR for the rebranding: https://github.com/prebid/prebid.github.io/pull/3334
We would really appreciate this change going through quickly.

Yahoo ConnectID user ID module: Updated the download page

---

dev-docs/bidders/yieldone.md

YieldOne Bid Adapter: Update doc.

YieldOne Bid Adapter: Update doc.

---

_data/sidebar.yml
dev-docs/examples/legacy-browser-example.md

This is not the right js fiddle yet, please lmk if I am putting this in the correct place / modifying the correct files.

Prebid 6 legacy code deploy example

---

dev-docs/bidders/criteo.md

There was an error in the documentation about the video playbackmethod parameter : it stated it should be an int whereas the backend expects an array of int (as it is described in openrtb)

Updated criteo bidder doc for video playbackmethod

---

dev-docs/publisher-api-reference/bidderSettings.md

Adds documentation for the new bidderSettings field `allowZeroCpmBids`.
Related Prebid.js PR: https://github.com/prebid/Prebid.js/pull/7633

new bidderSettings field - allowZeroCpmBids
